

/* This file was generated by JSON Schema to C.
 * Any changes made to it will be lost on regeneration. 

 * Copyright (C) 2021-2023  TMLake(Beijing) Technology Co., Ltd.
 */

#include "njt_stream_dyn_lua_parser.h"
#include "njt_core.h"
#include "js2c_njet_builtins.h"
/* ========================== Generated parsers ========================== */


static bool parse_dynstreamlua_upstreams_item(njt_pool_t *pool, parse_state_t *parse_state, dynstreamlua_upstreams_item_t *out, js2c_parse_error_t *err_ret) {
    njt_uint_t i;

    js2c_check_type(JSMN_OBJECT);
    const int object_start_token = parse_state->current_token;
    const uint64_t n = parse_state->tokens[parse_state->current_token].size;
    parse_state->current_token += 1;
    for (i = 0; i < n; ++i) {
        js2c_key_children_check_for_obj();
        if (current_string_is(parse_state, "name")) {
            js2c_check_field_set(out->is_name_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "name";
            int token_size =  CURRENT_STRING_LENGTH(parse_state) ;
            ((&out->name))->data = (u_char*)njt_pcalloc(pool, (size_t)(token_size + 1));
            js2c_malloc_check(((&out->name))->data);
            ((&out->name))->len = token_size;
            if (builtin_parse_string(pool, parse_state, (&out->name), 0, ((&out->name))->len, err_ret)) {
                return true;
            }
            out->is_name_set = 1;
            parse_state->current_key = saved_key;
        } else if (current_string_is(parse_state, "balancer_by")) {
            js2c_check_field_set(out->is_balancer_by_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "balancer_by";
            int token_size =  CURRENT_STRING_LENGTH(parse_state) ;
            ((&out->balancer_by))->data = (u_char*)njt_pcalloc(pool, (size_t)(token_size + 1));
            js2c_malloc_check(((&out->balancer_by))->data);
            ((&out->balancer_by))->len = token_size;
            if (builtin_parse_string(pool, parse_state, (&out->balancer_by), 0, ((&out->balancer_by))->len, err_ret)) {
                return true;
            }
            out->is_balancer_by_set = 1;
            parse_state->current_key = saved_key;
        } else {
            LOG_ERROR_JSON_PARSE(UNKNOWN_FIELD_ERR, parse_state->current_key, CURRENT_TOKEN(parse_state).start, "Unknown field in '%s': %.*s", parse_state->current_key, CURRENT_STRING_FOR_ERROR(parse_state));
            return true;
        }
    }
    const int saved_current_token = parse_state->current_token;
    parse_state->current_token = object_start_token;
    if (!out->is_name_set) {
        LOG_ERROR_JSON_PARSE(MISSING_REQUIRED_FIELD_ERR, parse_state->current_key, CURRENT_TOKEN(parse_state).start, "Missing required field in '%s': name", parse_state->current_key);
        return true;
    }
    if (!out->is_balancer_by_set) {
        LOG_ERROR_JSON_PARSE(MISSING_REQUIRED_FIELD_ERR, parse_state->current_key, CURRENT_TOKEN(parse_state).start, "Missing required field in '%s': balancer_by", parse_state->current_key);
        return true;
    }
    parse_state->current_token = saved_current_token;
    return false;
}


static bool parse_dynstreamlua_upstreams(njt_pool_t *pool, parse_state_t *parse_state, dynstreamlua_upstreams_t *out, js2c_parse_error_t *err_ret) {
    int i;
    js2c_check_type(JSMN_ARRAY);
    const int n = parse_state->tokens[parse_state->current_token].size;
    parse_state->current_token += 1;
    for (i = 0; i < n; ++i) {
        ((dynstreamlua_upstreams_item_t**)out->elts)[i] = njt_pcalloc(pool, sizeof(dynstreamlua_upstreams_item_t));
        memset(((dynstreamlua_upstreams_item_t**)out->elts)[i], 0, sizeof(dynstreamlua_upstreams_item_t));
        if (parse_dynstreamlua_upstreams_item(pool, parse_state, ((dynstreamlua_upstreams_item_t**)out->elts)[i], err_ret)) {
            return true;
        }
        out->nelts ++;
    }
    return false;
}


static bool parse_dynstreamlua_servers_item_listens(njt_pool_t *pool, parse_state_t *parse_state, dynstreamlua_servers_item_listens_t *out, js2c_parse_error_t *err_ret) {
    int i;
    js2c_check_type(JSMN_ARRAY);
    const int n = parse_state->tokens[parse_state->current_token].size;
    parse_state->current_token += 1;
    for (i = 0; i < n; ++i) {
        int token_size =  CURRENT_STRING_LENGTH(parse_state) ;
        ((&((dynstreamlua_servers_item_listens_item_t*)out->elts)[i]))->data = (u_char*)njt_pcalloc(pool, (size_t)(token_size + 1));
        js2c_malloc_check(((&((dynstreamlua_servers_item_listens_item_t*)out->elts)[i]))->data);
        ((&((dynstreamlua_servers_item_listens_item_t*)out->elts)[i]))->len = token_size;
        if (builtin_parse_string(pool, parse_state, (&((dynstreamlua_servers_item_listens_item_t*)out->elts)[i]), 0, ((&((dynstreamlua_servers_item_listens_item_t*)out->elts)[i]))->len, err_ret)) {
            return true;
        }
        out->nelts ++;
    }
    return false;
}


static bool parse_dynstreamlua_servers_item_serverNames(njt_pool_t *pool, parse_state_t *parse_state, dynstreamlua_servers_item_serverNames_t *out, js2c_parse_error_t *err_ret) {
    int i;
    js2c_check_type(JSMN_ARRAY);
    const int n = parse_state->tokens[parse_state->current_token].size;
    parse_state->current_token += 1;
    for (i = 0; i < n; ++i) {
        int token_size =  CURRENT_STRING_LENGTH(parse_state) ;
        ((&((dynstreamlua_servers_item_serverNames_item_t*)out->elts)[i]))->data = (u_char*)njt_pcalloc(pool, (size_t)(token_size + 1));
        js2c_malloc_check(((&((dynstreamlua_servers_item_serverNames_item_t*)out->elts)[i]))->data);
        ((&((dynstreamlua_servers_item_serverNames_item_t*)out->elts)[i]))->len = token_size;
        if (builtin_parse_string(pool, parse_state, (&((dynstreamlua_servers_item_serverNames_item_t*)out->elts)[i]), 0, ((&((dynstreamlua_servers_item_serverNames_item_t*)out->elts)[i]))->len, err_ret)) {
            return true;
        }
        out->nelts ++;
    }
    return false;
}


static bool parse_dynstreamlua_servers_item_lua(njt_pool_t *pool, parse_state_t *parse_state, dynstreamlua_servers_item_lua_t *out, js2c_parse_error_t *err_ret) {
    njt_uint_t i;

    js2c_check_type(JSMN_OBJECT);
    const int object_start_token = parse_state->current_token;
    const uint64_t n = parse_state->tokens[parse_state->current_token].size;
    parse_state->current_token += 1;
    for (i = 0; i < n; ++i) {
        js2c_key_children_check_for_obj();
        if (current_string_is(parse_state, "content_by")) {
            js2c_check_field_set(out->is_content_by_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "content_by";
            js2c_null_check();
            int token_size =  CURRENT_STRING_LENGTH(parse_state) ;
            ((&out->content_by))->data = (u_char*)njt_pcalloc(pool, (size_t)(token_size + 1));
            js2c_malloc_check(((&out->content_by))->data);
            ((&out->content_by))->len = token_size;
            if (builtin_parse_string(pool, parse_state, (&out->content_by), 0, ((&out->content_by))->len, err_ret)) {
                return true;
            }
            out->is_content_by_set = 1;
            parse_state->current_key = saved_key;
        } else if (current_string_is(parse_state, "preread_by")) {
            js2c_check_field_set(out->is_preread_by_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "preread_by";
            js2c_null_check();
            int token_size =  CURRENT_STRING_LENGTH(parse_state) ;
            ((&out->preread_by))->data = (u_char*)njt_pcalloc(pool, (size_t)(token_size + 1));
            js2c_malloc_check(((&out->preread_by))->data);
            ((&out->preread_by))->len = token_size;
            if (builtin_parse_string(pool, parse_state, (&out->preread_by), 0, ((&out->preread_by))->len, err_ret)) {
                return true;
            }
            out->is_preread_by_set = 1;
            parse_state->current_key = saved_key;
        } else {
            LOG_ERROR_JSON_PARSE(UNKNOWN_FIELD_ERR, parse_state->current_key, CURRENT_TOKEN(parse_state).start, "Unknown field in '%s': %.*s", parse_state->current_key, CURRENT_STRING_FOR_ERROR(parse_state));
            return true;
        }
    }
    const int saved_current_token = parse_state->current_token;
    parse_state->current_token = object_start_token;
    // set default
    if (!out->is_content_by_set) {
        size_t token_size = strlen("None");
        (out->content_by).data = (u_char*)njt_pcalloc(pool, token_size + 1);
        js2c_malloc_check((out->content_by).data);
        (out->content_by).len = token_size;
        if (out->content_by.len == 0) {
            (out->content_by).data[0] = 0;
        }
        if (token_size > 0) {
            njt_memcpy(out->content_by.data, "None", token_size);
        }
    }
    // set default
    if (!out->is_preread_by_set) {
        size_t token_size = strlen("None");
        (out->preread_by).data = (u_char*)njt_pcalloc(pool, token_size + 1);
        js2c_malloc_check((out->preread_by).data);
        (out->preread_by).len = token_size;
        if (out->preread_by.len == 0) {
            (out->preread_by).data[0] = 0;
        }
        if (token_size > 0) {
            njt_memcpy(out->preread_by.data, "None", token_size);
        }
    }
    parse_state->current_token = saved_current_token;
    return false;
}


static bool parse_dynstreamlua_servers_item(njt_pool_t *pool, parse_state_t *parse_state, dynstreamlua_servers_item_t *out, js2c_parse_error_t *err_ret) {
    njt_uint_t i;

    js2c_check_type(JSMN_OBJECT);
    const int object_start_token = parse_state->current_token;
    const uint64_t n = parse_state->tokens[parse_state->current_token].size;
    parse_state->current_token += 1;
    for (i = 0; i < n; ++i) {
        js2c_key_children_check_for_obj();
        if (current_string_is(parse_state, "listens")) {
            js2c_check_field_set(out->is_listens_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "listens";
            out->listens = njt_array_create(pool, parse_state->tokens[parse_state->current_token].size ,sizeof(njt_str_t));
            js2c_malloc_check(out->listens);

            if (parse_dynstreamlua_servers_item_listens(pool, parse_state, (out->listens), err_ret)) {
                return true;
            }
            out->is_listens_set = 1;
            parse_state->current_key = saved_key;
        } else if (current_string_is(parse_state, "serverNames")) {
            js2c_check_field_set(out->is_serverNames_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "serverNames";
            out->serverNames = njt_array_create(pool, parse_state->tokens[parse_state->current_token].size ,sizeof(njt_str_t));
            js2c_malloc_check(out->serverNames);

            if (parse_dynstreamlua_servers_item_serverNames(pool, parse_state, (out->serverNames), err_ret)) {
                return true;
            }
            out->is_serverNames_set = 1;
            parse_state->current_key = saved_key;
        } else if (current_string_is(parse_state, "lua")) {
            js2c_check_field_set(out->is_lua_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "lua";
            out->lua = njt_pcalloc(pool, sizeof(dynstreamlua_servers_item_lua_t));
            js2c_malloc_check(out->lua);
            memset(out->lua, 0, sizeof(dynstreamlua_servers_item_lua_t));

            if (parse_dynstreamlua_servers_item_lua(pool, parse_state, (out->lua), err_ret)) {
                return true;
            }
            out->is_lua_set = 1;
            parse_state->current_key = saved_key;
        } else {
            LOG_ERROR_JSON_PARSE(UNKNOWN_FIELD_ERR, parse_state->current_key, CURRENT_TOKEN(parse_state).start, "Unknown field in '%s': %.*s", parse_state->current_key, CURRENT_STRING_FOR_ERROR(parse_state));
            return true;
        }
    }
    const int saved_current_token = parse_state->current_token;
    parse_state->current_token = object_start_token;
    if (!out->is_listens_set) {
        LOG_ERROR_JSON_PARSE(MISSING_REQUIRED_FIELD_ERR, parse_state->current_key, CURRENT_TOKEN(parse_state).start, "Missing required field in '%s': listens", parse_state->current_key);
        return true;
    }
    if (!out->is_serverNames_set) {
        LOG_ERROR_JSON_PARSE(MISSING_REQUIRED_FIELD_ERR, parse_state->current_key, CURRENT_TOKEN(parse_state).start, "Missing required field in '%s': serverNames", parse_state->current_key);
        return true;
    }
    if (!out->is_lua_set) {
        LOG_ERROR_JSON_PARSE(MISSING_REQUIRED_FIELD_ERR, parse_state->current_key, CURRENT_TOKEN(parse_state).start, "Missing required field in '%s': lua", parse_state->current_key);
        return true;
    }
    parse_state->current_token = saved_current_token;
    return false;
}


static bool parse_dynstreamlua_servers(njt_pool_t *pool, parse_state_t *parse_state, dynstreamlua_servers_t *out, js2c_parse_error_t *err_ret) {
    int i;
    js2c_check_type(JSMN_ARRAY);
    const int n = parse_state->tokens[parse_state->current_token].size;
    parse_state->current_token += 1;
    for (i = 0; i < n; ++i) {
        ((dynstreamlua_servers_item_t**)out->elts)[i] = njt_pcalloc(pool, sizeof(dynstreamlua_servers_item_t));
        memset(((dynstreamlua_servers_item_t**)out->elts)[i], 0, sizeof(dynstreamlua_servers_item_t));
        if (parse_dynstreamlua_servers_item(pool, parse_state, ((dynstreamlua_servers_item_t**)out->elts)[i], err_ret)) {
            return true;
        }
        out->nelts ++;
    }
    return false;
}


static bool parse_dynstreamlua(njt_pool_t *pool, parse_state_t *parse_state, dynstreamlua_t *out, js2c_parse_error_t *err_ret) {
    njt_uint_t i;

    js2c_check_type(JSMN_OBJECT);
    const int object_start_token = parse_state->current_token;
    const uint64_t n = parse_state->tokens[parse_state->current_token].size;
    parse_state->current_token += 1;
    for (i = 0; i < n; ++i) {
        js2c_key_children_check_for_obj();
        if (current_string_is(parse_state, "upstreams")) {
            js2c_check_field_set(out->is_upstreams_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "upstreams";
            out->upstreams = njt_array_create(pool, parse_state->tokens[parse_state->current_token].size ,sizeof(dynstreamlua_upstreams_item_t*));
            js2c_malloc_check(out->upstreams);

            if (parse_dynstreamlua_upstreams(pool, parse_state, (out->upstreams), err_ret)) {
                return true;
            }
            out->is_upstreams_set = 1;
            parse_state->current_key = saved_key;
        } else if (current_string_is(parse_state, "servers")) {
            js2c_check_field_set(out->is_servers_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "servers";
            out->servers = njt_array_create(pool, parse_state->tokens[parse_state->current_token].size ,sizeof(dynstreamlua_servers_item_t*));
            js2c_malloc_check(out->servers);

            if (parse_dynstreamlua_servers(pool, parse_state, (out->servers), err_ret)) {
                return true;
            }
            out->is_servers_set = 1;
            parse_state->current_key = saved_key;
        } else {
            LOG_ERROR_JSON_PARSE(UNKNOWN_FIELD_ERR, parse_state->current_key, CURRENT_TOKEN(parse_state).start, "Unknown field in '%s': %.*s", parse_state->current_key, CURRENT_STRING_FOR_ERROR(parse_state));
            return true;
        }
    }
    const int saved_current_token = parse_state->current_token;
    parse_state->current_token = object_start_token;
    if (!out->is_upstreams_set) {
        LOG_ERROR_JSON_PARSE(MISSING_REQUIRED_FIELD_ERR, parse_state->current_key, CURRENT_TOKEN(parse_state).start, "Missing required field in '%s': upstreams", parse_state->current_key);
        return true;
    }
    if (!out->is_servers_set) {
        LOG_ERROR_JSON_PARSE(MISSING_REQUIRED_FIELD_ERR, parse_state->current_key, CURRENT_TOKEN(parse_state).start, "Missing required field in '%s': servers", parse_state->current_key);
        return true;
    }
    parse_state->current_token = saved_current_token;
    return false;
}


static void get_json_length_dynstreamlua_upstreams_item_name(njt_pool_t *pool, dynstreamlua_upstreams_item_name_t *out, size_t *length, njt_int_t flags) {
    njt_str_t *dst = handle_escape_on_write(pool, out);
    *length += dst->len + 2; //  "str" 
}

static void get_json_length_dynstreamlua_upstreams_item_balancer_by(njt_pool_t *pool, dynstreamlua_upstreams_item_balancer_by_t *out, size_t *length, njt_int_t flags) {
    njt_str_t *dst = handle_escape_on_write(pool, out);
    *length += dst->len + 2; //  "str" 
}

static void get_json_length_dynstreamlua_upstreams_item(njt_pool_t *pool, dynstreamlua_upstreams_item_t *out, size_t *length, njt_int_t flags) {
    if (out == NULL) {
        *length += 4; // null
        return;
    }
    *length += 1;
    njt_int_t omit;
    njt_int_t count = 0;
    omit = 0;
    omit = out->is_name_set ? 0 : 1;
    omit = (flags & OMIT_NULL_STR) && (out->name.data) == NULL ? 1 : omit;
    if (omit == 0) {
        *length += (4 + 3); // "name": 
        get_json_length_dynstreamlua_upstreams_item_name(pool, (&out->name), length, flags);
        *length += 1; // ","
        count++;
    }
    omit = 0;
    omit = out->is_balancer_by_set ? 0 : 1;
    omit = (flags & OMIT_NULL_STR) && (out->balancer_by.data) == NULL ? 1 : omit;
    if (omit == 0) {
        *length += (11 + 3); // "balancer_by": 
        get_json_length_dynstreamlua_upstreams_item_balancer_by(pool, (&out->balancer_by), length, flags);
        *length += 1; // ","
        count++;
    }
    if (count != 0) {
        *length -= 1; // "\b"
    }
    *length += 1;
}

static void get_json_length_dynstreamlua_upstreams(njt_pool_t *pool, dynstreamlua_upstreams_t *out, size_t *length, njt_int_t flags) {
    njt_uint_t i;
    njt_uint_t omit;
    njt_int_t count = 0;
    if (out == NULL) {
        *length += 2; // "[]"
        return;
    }
    *length += 2; // "[]"
    for (i = 0; i < out->nelts; ++i) {
        omit = 0;
        omit = ((flags & OMIT_NULL_OBJ) && ((dynstreamlua_upstreams_item_t**)out->elts)[i] == NULL) ? 1 : 0;
        if (omit == 0) {
            get_json_length_dynstreamlua_upstreams_item(pool, ((dynstreamlua_upstreams_item_t**)out->elts)[i], length, flags);
            *length += 1; // ","
            count++; // ","
        }
    }
    if (count != 0) {
        *length -= 1; // "\b"
    }
}

static void get_json_length_dynstreamlua_servers_item_listens_item(njt_pool_t *pool, dynstreamlua_servers_item_listens_item_t *out, size_t *length, njt_int_t flags) {
    njt_str_t *dst = handle_escape_on_write(pool, out);
    *length += dst->len + 2; //  "str" 
}

static void get_json_length_dynstreamlua_servers_item_listens(njt_pool_t *pool, dynstreamlua_servers_item_listens_t *out, size_t *length, njt_int_t flags) {
    njt_uint_t i;
    njt_uint_t omit;
    njt_int_t count = 0;
    if (out == NULL) {
        *length += 2; // "[]"
        return;
    }
    *length += 2; // "[]"
    for (i = 0; i < out->nelts; ++i) {
        omit = 0;
        omit = ((flags & OMIT_NULL_STR) && (&((dynstreamlua_servers_item_listens_item_t*)out->elts)[i])->data == NULL) ? 1 : 0;
        if (omit == 0) {
            get_json_length_dynstreamlua_servers_item_listens_item(pool, (&((dynstreamlua_servers_item_listens_item_t*)out->elts)[i]), length, flags);
            *length += 1; // ","
            count++; // ","
        }
    }
    if (count != 0) {
        *length -= 1; // "\b"
    }
}

static void get_json_length_dynstreamlua_servers_item_serverNames_item(njt_pool_t *pool, dynstreamlua_servers_item_serverNames_item_t *out, size_t *length, njt_int_t flags) {
    njt_str_t *dst = handle_escape_on_write(pool, out);
    *length += dst->len + 2; //  "str" 
}

static void get_json_length_dynstreamlua_servers_item_serverNames(njt_pool_t *pool, dynstreamlua_servers_item_serverNames_t *out, size_t *length, njt_int_t flags) {
    njt_uint_t i;
    njt_uint_t omit;
    njt_int_t count = 0;
    if (out == NULL) {
        *length += 2; // "[]"
        return;
    }
    *length += 2; // "[]"
    for (i = 0; i < out->nelts; ++i) {
        omit = 0;
        omit = ((flags & OMIT_NULL_STR) && (&((dynstreamlua_servers_item_serverNames_item_t*)out->elts)[i])->data == NULL) ? 1 : 0;
        if (omit == 0) {
            get_json_length_dynstreamlua_servers_item_serverNames_item(pool, (&((dynstreamlua_servers_item_serverNames_item_t*)out->elts)[i]), length, flags);
            *length += 1; // ","
            count++; // ","
        }
    }
    if (count != 0) {
        *length -= 1; // "\b"
    }
}

static void get_json_length_dynstreamlua_servers_item_lua_content_by(njt_pool_t *pool, dynstreamlua_servers_item_lua_content_by_t *out, size_t *length, njt_int_t flags) {
    njt_str_t *dst = handle_escape_on_write(pool, out);
    *length += dst->len + 2; //  "str" 
}

static void get_json_length_dynstreamlua_servers_item_lua_preread_by(njt_pool_t *pool, dynstreamlua_servers_item_lua_preread_by_t *out, size_t *length, njt_int_t flags) {
    njt_str_t *dst = handle_escape_on_write(pool, out);
    *length += dst->len + 2; //  "str" 
}

static void get_json_length_dynstreamlua_servers_item_lua(njt_pool_t *pool, dynstreamlua_servers_item_lua_t *out, size_t *length, njt_int_t flags) {
    if (out == NULL) {
        *length += 4; // null
        return;
    }
    *length += 1;
    njt_int_t omit;
    njt_int_t count = 0;
    omit = 0;
    omit = out->is_content_by_set ? 0 : 1;
    omit = (flags & OMIT_NULL_STR) && (out->content_by.data) == NULL ? 1 : omit;
    if (omit == 0) {
        *length += (10 + 3); // "content_by": 
        get_json_length_dynstreamlua_servers_item_lua_content_by(pool, (&out->content_by), length, flags);
        *length += 1; // ","
        count++;
    }
    omit = 0;
    omit = out->is_preread_by_set ? 0 : 1;
    omit = (flags & OMIT_NULL_STR) && (out->preread_by.data) == NULL ? 1 : omit;
    if (omit == 0) {
        *length += (10 + 3); // "preread_by": 
        get_json_length_dynstreamlua_servers_item_lua_preread_by(pool, (&out->preread_by), length, flags);
        *length += 1; // ","
        count++;
    }
    if (count != 0) {
        *length -= 1; // "\b"
    }
    *length += 1;
}

static void get_json_length_dynstreamlua_servers_item(njt_pool_t *pool, dynstreamlua_servers_item_t *out, size_t *length, njt_int_t flags) {
    if (out == NULL) {
        *length += 4; // null
        return;
    }
    *length += 1;
    njt_int_t omit;
    njt_int_t count = 0;
    omit = 0;
    omit = out->is_listens_set ? 0 : 1;
    omit = (flags & OMIT_NULL_ARRAY) && (out->listens) == NULL ? 1 : omit;
    if (omit == 0) {
        *length += (7 + 3); // "listens": 
        get_json_length_dynstreamlua_servers_item_listens(pool, (out->listens), length, flags);
        *length += 1; // ","
        count++;
    }
    omit = 0;
    omit = out->is_serverNames_set ? 0 : 1;
    omit = (flags & OMIT_NULL_ARRAY) && (out->serverNames) == NULL ? 1 : omit;
    if (omit == 0) {
        *length += (11 + 3); // "serverNames": 
        get_json_length_dynstreamlua_servers_item_serverNames(pool, (out->serverNames), length, flags);
        *length += 1; // ","
        count++;
    }
    omit = 0;
    omit = out->is_lua_set ? 0 : 1;
    omit = (flags & OMIT_NULL_OBJ) && (out->lua) == NULL ? 1 : omit;
    if (omit == 0) {
        *length += (3 + 3); // "lua": 
        get_json_length_dynstreamlua_servers_item_lua(pool, (out->lua), length, flags);
        *length += 1; // ","
        count++;
    }
    if (count != 0) {
        *length -= 1; // "\b"
    }
    *length += 1;
}

static void get_json_length_dynstreamlua_servers(njt_pool_t *pool, dynstreamlua_servers_t *out, size_t *length, njt_int_t flags) {
    njt_uint_t i;
    njt_uint_t omit;
    njt_int_t count = 0;
    if (out == NULL) {
        *length += 2; // "[]"
        return;
    }
    *length += 2; // "[]"
    for (i = 0; i < out->nelts; ++i) {
        omit = 0;
        omit = ((flags & OMIT_NULL_OBJ) && ((dynstreamlua_servers_item_t**)out->elts)[i] == NULL) ? 1 : 0;
        if (omit == 0) {
            get_json_length_dynstreamlua_servers_item(pool, ((dynstreamlua_servers_item_t**)out->elts)[i], length, flags);
            *length += 1; // ","
            count++; // ","
        }
    }
    if (count != 0) {
        *length -= 1; // "\b"
    }
}

static void get_json_length_dynstreamlua(njt_pool_t *pool, dynstreamlua_t *out, size_t *length, njt_int_t flags) {
    if (out == NULL) {
        *length += 4; // null
        return;
    }
    *length += 1;
    njt_int_t omit;
    njt_int_t count = 0;
    omit = 0;
    omit = out->is_upstreams_set ? 0 : 1;
    omit = (flags & OMIT_NULL_ARRAY) && (out->upstreams) == NULL ? 1 : omit;
    if (omit == 0) {
        *length += (9 + 3); // "upstreams": 
        get_json_length_dynstreamlua_upstreams(pool, (out->upstreams), length, flags);
        *length += 1; // ","
        count++;
    }
    omit = 0;
    omit = out->is_servers_set ? 0 : 1;
    omit = (flags & OMIT_NULL_ARRAY) && (out->servers) == NULL ? 1 : omit;
    if (omit == 0) {
        *length += (7 + 3); // "servers": 
        get_json_length_dynstreamlua_servers(pool, (out->servers), length, flags);
        *length += 1; // ","
        count++;
    }
    if (count != 0) {
        *length -= 1; // "\b"
    }
    *length += 1;
}

dynstreamlua_upstreams_item_name_t* get_dynstreamlua_upstreams_item_name(dynstreamlua_upstreams_item_t *out) {
    return &out->name;
}

dynstreamlua_upstreams_item_balancer_by_t* get_dynstreamlua_upstreams_item_balancer_by(dynstreamlua_upstreams_item_t *out) {
    return &out->balancer_by;
}
dynstreamlua_upstreams_item_t* get_dynstreamlua_upstreams_item(dynstreamlua_upstreams_t *out, size_t idx) {
    return ((dynstreamlua_upstreams_item_t**)out->elts)[idx];

}
dynstreamlua_servers_item_listens_item_t* get_dynstreamlua_servers_item_listens_item(dynstreamlua_servers_item_listens_t *out, size_t idx) {
    return &((dynstreamlua_servers_item_listens_item_t*)out->elts)[idx];

}
dynstreamlua_servers_item_serverNames_item_t* get_dynstreamlua_servers_item_serverNames_item(dynstreamlua_servers_item_serverNames_t *out, size_t idx) {
    return &((dynstreamlua_servers_item_serverNames_item_t*)out->elts)[idx];

}

dynstreamlua_servers_item_lua_content_by_t* get_dynstreamlua_servers_item_lua_content_by(dynstreamlua_servers_item_lua_t *out) {
    return &out->content_by;
}

dynstreamlua_servers_item_lua_preread_by_t* get_dynstreamlua_servers_item_lua_preread_by(dynstreamlua_servers_item_lua_t *out) {
    return &out->preread_by;
}

dynstreamlua_servers_item_listens_t* get_dynstreamlua_servers_item_listens(dynstreamlua_servers_item_t *out) {
    return out->listens;
}

dynstreamlua_servers_item_serverNames_t* get_dynstreamlua_servers_item_serverNames(dynstreamlua_servers_item_t *out) {
    return out->serverNames;
}

dynstreamlua_servers_item_lua_t* get_dynstreamlua_servers_item_lua(dynstreamlua_servers_item_t *out) {
    return out->lua;
}
dynstreamlua_servers_item_t* get_dynstreamlua_servers_item(dynstreamlua_servers_t *out, size_t idx) {
    return ((dynstreamlua_servers_item_t**)out->elts)[idx];

}

dynstreamlua_upstreams_t* get_dynstreamlua_upstreams(dynstreamlua_t *out) {
    return out->upstreams;
}

dynstreamlua_servers_t* get_dynstreamlua_servers(dynstreamlua_t *out) {
    return out->servers;
}
void set_dynstreamlua_upstreams_item_name(dynstreamlua_upstreams_item_t* obj, dynstreamlua_upstreams_item_name_t* field) {
    njt_memcpy(&obj->name, field, sizeof(njt_str_t));
    obj->is_name_set = 1;
}
void set_dynstreamlua_upstreams_item_balancer_by(dynstreamlua_upstreams_item_t* obj, dynstreamlua_upstreams_item_balancer_by_t* field) {
    njt_memcpy(&obj->balancer_by, field, sizeof(njt_str_t));
    obj->is_balancer_by_set = 1;
}
dynstreamlua_upstreams_item_t* create_dynstreamlua_upstreams_item(njt_pool_t *pool) {
    dynstreamlua_upstreams_item_t* out = njt_pcalloc(pool, sizeof(dynstreamlua_upstreams_item_t));
    return out;
}
int add_item_dynstreamlua_upstreams(dynstreamlua_upstreams_t *src, dynstreamlua_upstreams_item_t* item) {
    void *new = njt_array_push(src);
    if (new == NULL) {
        return NJT_ERROR;
    }
    njt_memcpy(new, &item, src->size);
    return NJT_OK;
}

dynstreamlua_upstreams_t* create_dynstreamlua_upstreams(njt_pool_t *pool, size_t nelts) {
    return njt_array_create(pool, nelts, sizeof(dynstreamlua_upstreams_item_t*));
}
void set_dynstreamlua_upstreams(dynstreamlua_t* obj, dynstreamlua_upstreams_t* field) {
    obj->upstreams = field;
    obj->is_upstreams_set = 1;
}
int add_item_dynstreamlua_servers_item_listens(dynstreamlua_servers_item_listens_t *src, dynstreamlua_servers_item_listens_item_t* item) {
    void *new = njt_array_push(src);
    if (new == NULL) {
        return NJT_ERROR;
    }
    njt_memcpy(new, item, src->size);
    return NJT_OK;
}

dynstreamlua_servers_item_listens_t* create_dynstreamlua_servers_item_listens(njt_pool_t *pool, size_t nelts) {
    return njt_array_create(pool, nelts, sizeof(dynstreamlua_servers_item_listens_item_t));
}
void set_dynstreamlua_servers_item_listens(dynstreamlua_servers_item_t* obj, dynstreamlua_servers_item_listens_t* field) {
    obj->listens = field;
    obj->is_listens_set = 1;
}
int add_item_dynstreamlua_servers_item_serverNames(dynstreamlua_servers_item_serverNames_t *src, dynstreamlua_servers_item_serverNames_item_t* item) {
    void *new = njt_array_push(src);
    if (new == NULL) {
        return NJT_ERROR;
    }
    njt_memcpy(new, item, src->size);
    return NJT_OK;
}

dynstreamlua_servers_item_serverNames_t* create_dynstreamlua_servers_item_serverNames(njt_pool_t *pool, size_t nelts) {
    return njt_array_create(pool, nelts, sizeof(dynstreamlua_servers_item_serverNames_item_t));
}
void set_dynstreamlua_servers_item_serverNames(dynstreamlua_servers_item_t* obj, dynstreamlua_servers_item_serverNames_t* field) {
    obj->serverNames = field;
    obj->is_serverNames_set = 1;
}
void set_dynstreamlua_servers_item_lua_content_by(dynstreamlua_servers_item_lua_t* obj, dynstreamlua_servers_item_lua_content_by_t* field) {
    njt_memcpy(&obj->content_by, field, sizeof(njt_str_t));
    obj->is_content_by_set = 1;
}
void set_dynstreamlua_servers_item_lua_preread_by(dynstreamlua_servers_item_lua_t* obj, dynstreamlua_servers_item_lua_preread_by_t* field) {
    njt_memcpy(&obj->preread_by, field, sizeof(njt_str_t));
    obj->is_preread_by_set = 1;
}
dynstreamlua_servers_item_lua_t* create_dynstreamlua_servers_item_lua(njt_pool_t *pool) {
    dynstreamlua_servers_item_lua_t* out = njt_pcalloc(pool, sizeof(dynstreamlua_servers_item_lua_t));
    return out;
}
void set_dynstreamlua_servers_item_lua(dynstreamlua_servers_item_t* obj, dynstreamlua_servers_item_lua_t* field) {
    obj->lua = field;
    obj->is_lua_set = 1;
}
dynstreamlua_servers_item_t* create_dynstreamlua_servers_item(njt_pool_t *pool) {
    dynstreamlua_servers_item_t* out = njt_pcalloc(pool, sizeof(dynstreamlua_servers_item_t));
    return out;
}
int add_item_dynstreamlua_servers(dynstreamlua_servers_t *src, dynstreamlua_servers_item_t* item) {
    void *new = njt_array_push(src);
    if (new == NULL) {
        return NJT_ERROR;
    }
    njt_memcpy(new, &item, src->size);
    return NJT_OK;
}

dynstreamlua_servers_t* create_dynstreamlua_servers(njt_pool_t *pool, size_t nelts) {
    return njt_array_create(pool, nelts, sizeof(dynstreamlua_servers_item_t*));
}
void set_dynstreamlua_servers(dynstreamlua_t* obj, dynstreamlua_servers_t* field) {
    obj->servers = field;
    obj->is_servers_set = 1;
}
dynstreamlua_t* create_dynstreamlua(njt_pool_t *pool) {
    dynstreamlua_t* out = njt_pcalloc(pool, sizeof(dynstreamlua_t));
    return out;
}

static void to_oneline_json_dynstreamlua_upstreams_item_name(njt_pool_t *pool, dynstreamlua_upstreams_item_name_t *out, njt_str_t *buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    njt_str_t *dst = handle_escape_on_write(pool, out);
    cur = njt_sprintf(cur, "\"%V\"", dst);
    buf->len = cur - buf->data;
}

static void to_oneline_json_dynstreamlua_upstreams_item_balancer_by(njt_pool_t *pool, dynstreamlua_upstreams_item_balancer_by_t *out, njt_str_t *buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    njt_str_t *dst = handle_escape_on_write(pool, out);
    cur = njt_sprintf(cur, "\"%V\"", dst);
    buf->len = cur - buf->data;
}

static void to_oneline_json_dynstreamlua_upstreams_item(njt_pool_t *pool, dynstreamlua_upstreams_item_t *out, njt_str_t* buf, njt_int_t flags) {
    njt_int_t omit;
    u_char* cur = buf->data + buf->len;
    if (out == NULL) {
        cur = njt_sprintf(cur, "null");
        buf->len += 4;
        return;
    }
    cur = njt_sprintf(cur, "{");
    buf->len ++;
    omit = 0;
    omit = out->is_name_set ? 0 : 1;
    omit = (flags & OMIT_NULL_STR) && (out->name.data) == NULL ? 1 : omit;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"name\":");
        buf->len = cur - buf->data;
        to_oneline_json_dynstreamlua_upstreams_item_name(pool, (&out->name), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    omit = 0;
    omit = out->is_balancer_by_set ? 0 : 1;
    omit = (flags & OMIT_NULL_STR) && (out->balancer_by.data) == NULL ? 1 : omit;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"balancer_by\":");
        buf->len = cur - buf->data;
        to_oneline_json_dynstreamlua_upstreams_item_balancer_by(pool, (&out->balancer_by), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    cur--;
    if (cur[0] == ',') {
        buf->len --;
    } else {
        cur ++;
    }
    cur = njt_sprintf(cur, "}");
    buf->len ++;
}

static void to_oneline_json_dynstreamlua_upstreams(njt_pool_t *pool, dynstreamlua_upstreams_t *out, njt_str_t* buf, njt_int_t flags) {
    njt_int_t omit;
    u_char *cur = buf->data + buf->len;
    njt_uint_t i;
    if (out == NULL || out->nelts == 0) {
        cur = njt_sprintf(cur, "[]");
        buf->len += 2;
        return;
    }
    cur = njt_sprintf(cur,  "[");
    buf->len ++;
    for (i = 0; i < out->nelts; ++i) {
        omit = 0;
        omit = ((flags & OMIT_NULL_OBJ) && ((dynstreamlua_upstreams_item_t**)out->elts)[i] == NULL) ? 1 : 0;
        if (omit == 0) {
            to_oneline_json_dynstreamlua_upstreams_item(pool, ((dynstreamlua_upstreams_item_t**)out->elts)[i], buf, flags);
            cur = buf->data + buf->len;
            cur = njt_sprintf(cur, ",");
            buf->len ++;
        }
    }
    cur--;
    if (cur[0] == ',') {
        buf->len --;
    } else {
        cur ++;
    }
    cur = njt_sprintf(cur,  "]");
    buf->len ++;
}

static void to_oneline_json_dynstreamlua_servers_item_listens_item(njt_pool_t *pool, dynstreamlua_servers_item_listens_item_t *out, njt_str_t *buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    njt_str_t *dst = handle_escape_on_write(pool, out);
    cur = njt_sprintf(cur, "\"%V\"", dst);
    buf->len = cur - buf->data;
}

static void to_oneline_json_dynstreamlua_servers_item_listens(njt_pool_t *pool, dynstreamlua_servers_item_listens_t *out, njt_str_t* buf, njt_int_t flags) {
    njt_int_t omit;
    u_char *cur = buf->data + buf->len;
    njt_uint_t i;
    if (out == NULL || out->nelts == 0) {
        cur = njt_sprintf(cur, "[]");
        buf->len += 2;
        return;
    }
    cur = njt_sprintf(cur,  "[");
    buf->len ++;
    for (i = 0; i < out->nelts; ++i) {
        omit = 0;
        omit = ((flags & OMIT_NULL_STR) && (&((dynstreamlua_servers_item_listens_item_t*)out->elts)[i])->data == NULL) ? 1 : 0;
        if (omit == 0) {
            to_oneline_json_dynstreamlua_servers_item_listens_item(pool, (&((dynstreamlua_servers_item_listens_item_t*)out->elts)[i]), buf, flags);
            cur = buf->data + buf->len;
            cur = njt_sprintf(cur, ",");
            buf->len ++;
        }
    }
    cur--;
    if (cur[0] == ',') {
        buf->len --;
    } else {
        cur ++;
    }
    cur = njt_sprintf(cur,  "]");
    buf->len ++;
}

static void to_oneline_json_dynstreamlua_servers_item_serverNames_item(njt_pool_t *pool, dynstreamlua_servers_item_serverNames_item_t *out, njt_str_t *buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    njt_str_t *dst = handle_escape_on_write(pool, out);
    cur = njt_sprintf(cur, "\"%V\"", dst);
    buf->len = cur - buf->data;
}

static void to_oneline_json_dynstreamlua_servers_item_serverNames(njt_pool_t *pool, dynstreamlua_servers_item_serverNames_t *out, njt_str_t* buf, njt_int_t flags) {
    njt_int_t omit;
    u_char *cur = buf->data + buf->len;
    njt_uint_t i;
    if (out == NULL || out->nelts == 0) {
        cur = njt_sprintf(cur, "[]");
        buf->len += 2;
        return;
    }
    cur = njt_sprintf(cur,  "[");
    buf->len ++;
    for (i = 0; i < out->nelts; ++i) {
        omit = 0;
        omit = ((flags & OMIT_NULL_STR) && (&((dynstreamlua_servers_item_serverNames_item_t*)out->elts)[i])->data == NULL) ? 1 : 0;
        if (omit == 0) {
            to_oneline_json_dynstreamlua_servers_item_serverNames_item(pool, (&((dynstreamlua_servers_item_serverNames_item_t*)out->elts)[i]), buf, flags);
            cur = buf->data + buf->len;
            cur = njt_sprintf(cur, ",");
            buf->len ++;
        }
    }
    cur--;
    if (cur[0] == ',') {
        buf->len --;
    } else {
        cur ++;
    }
    cur = njt_sprintf(cur,  "]");
    buf->len ++;
}

static void to_oneline_json_dynstreamlua_servers_item_lua_content_by(njt_pool_t *pool, dynstreamlua_servers_item_lua_content_by_t *out, njt_str_t *buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    njt_str_t *dst = handle_escape_on_write(pool, out);
    cur = njt_sprintf(cur, "\"%V\"", dst);
    buf->len = cur - buf->data;
}

static void to_oneline_json_dynstreamlua_servers_item_lua_preread_by(njt_pool_t *pool, dynstreamlua_servers_item_lua_preread_by_t *out, njt_str_t *buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    njt_str_t *dst = handle_escape_on_write(pool, out);
    cur = njt_sprintf(cur, "\"%V\"", dst);
    buf->len = cur - buf->data;
}

static void to_oneline_json_dynstreamlua_servers_item_lua(njt_pool_t *pool, dynstreamlua_servers_item_lua_t *out, njt_str_t* buf, njt_int_t flags) {
    njt_int_t omit;
    u_char* cur = buf->data + buf->len;
    if (out == NULL) {
        cur = njt_sprintf(cur, "null");
        buf->len += 4;
        return;
    }
    cur = njt_sprintf(cur, "{");
    buf->len ++;
    omit = 0;
    omit = out->is_content_by_set ? 0 : 1;
    omit = (flags & OMIT_NULL_STR) && (out->content_by.data) == NULL ? 1 : omit;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"content_by\":");
        buf->len = cur - buf->data;
        to_oneline_json_dynstreamlua_servers_item_lua_content_by(pool, (&out->content_by), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    omit = 0;
    omit = out->is_preread_by_set ? 0 : 1;
    omit = (flags & OMIT_NULL_STR) && (out->preread_by.data) == NULL ? 1 : omit;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"preread_by\":");
        buf->len = cur - buf->data;
        to_oneline_json_dynstreamlua_servers_item_lua_preread_by(pool, (&out->preread_by), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    cur--;
    if (cur[0] == ',') {
        buf->len --;
    } else {
        cur ++;
    }
    cur = njt_sprintf(cur, "}");
    buf->len ++;
}

static void to_oneline_json_dynstreamlua_servers_item(njt_pool_t *pool, dynstreamlua_servers_item_t *out, njt_str_t* buf, njt_int_t flags) {
    njt_int_t omit;
    u_char* cur = buf->data + buf->len;
    if (out == NULL) {
        cur = njt_sprintf(cur, "null");
        buf->len += 4;
        return;
    }
    cur = njt_sprintf(cur, "{");
    buf->len ++;
    omit = 0;
    omit = out->is_listens_set ? 0 : 1;
    omit = (flags & OMIT_NULL_ARRAY) && (out->listens) == NULL ? 1 : omit;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"listens\":");
        buf->len = cur - buf->data;
        to_oneline_json_dynstreamlua_servers_item_listens(pool, (out->listens), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    omit = 0;
    omit = out->is_serverNames_set ? 0 : 1;
    omit = (flags & OMIT_NULL_ARRAY) && (out->serverNames) == NULL ? 1 : omit;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"serverNames\":");
        buf->len = cur - buf->data;
        to_oneline_json_dynstreamlua_servers_item_serverNames(pool, (out->serverNames), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    omit = 0;
    omit = out->is_lua_set ? 0 : 1;
    omit = (flags & OMIT_NULL_OBJ) && (out->lua) == NULL ? 1 : omit;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"lua\":");
        buf->len = cur - buf->data;
        to_oneline_json_dynstreamlua_servers_item_lua(pool, (out->lua), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    cur--;
    if (cur[0] == ',') {
        buf->len --;
    } else {
        cur ++;
    }
    cur = njt_sprintf(cur, "}");
    buf->len ++;
}

static void to_oneline_json_dynstreamlua_servers(njt_pool_t *pool, dynstreamlua_servers_t *out, njt_str_t* buf, njt_int_t flags) {
    njt_int_t omit;
    u_char *cur = buf->data + buf->len;
    njt_uint_t i;
    if (out == NULL || out->nelts == 0) {
        cur = njt_sprintf(cur, "[]");
        buf->len += 2;
        return;
    }
    cur = njt_sprintf(cur,  "[");
    buf->len ++;
    for (i = 0; i < out->nelts; ++i) {
        omit = 0;
        omit = ((flags & OMIT_NULL_OBJ) && ((dynstreamlua_servers_item_t**)out->elts)[i] == NULL) ? 1 : 0;
        if (omit == 0) {
            to_oneline_json_dynstreamlua_servers_item(pool, ((dynstreamlua_servers_item_t**)out->elts)[i], buf, flags);
            cur = buf->data + buf->len;
            cur = njt_sprintf(cur, ",");
            buf->len ++;
        }
    }
    cur--;
    if (cur[0] == ',') {
        buf->len --;
    } else {
        cur ++;
    }
    cur = njt_sprintf(cur,  "]");
    buf->len ++;
}

static void to_oneline_json_dynstreamlua(njt_pool_t *pool, dynstreamlua_t *out, njt_str_t* buf, njt_int_t flags) {
    njt_int_t omit;
    u_char* cur = buf->data + buf->len;
    if (out == NULL) {
        cur = njt_sprintf(cur, "null");
        buf->len += 4;
        return;
    }
    cur = njt_sprintf(cur, "{");
    buf->len ++;
    omit = 0;
    omit = out->is_upstreams_set ? 0 : 1;
    omit = (flags & OMIT_NULL_ARRAY) && (out->upstreams) == NULL ? 1 : omit;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"upstreams\":");
        buf->len = cur - buf->data;
        to_oneline_json_dynstreamlua_upstreams(pool, (out->upstreams), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    omit = 0;
    omit = out->is_servers_set ? 0 : 1;
    omit = (flags & OMIT_NULL_ARRAY) && (out->servers) == NULL ? 1 : omit;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"servers\":");
        buf->len = cur - buf->data;
        to_oneline_json_dynstreamlua_servers(pool, (out->servers), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    cur--;
    if (cur[0] == ',') {
        buf->len --;
    } else {
        cur ++;
    }
    cur = njt_sprintf(cur, "}");
    buf->len ++;
}
dynstreamlua_t* json_parse_dynstreamlua(njt_pool_t *pool, const njt_str_t *json_string, js2c_parse_error_t *err_ret) {
    dynstreamlua_t* out;
    parse_state_t parse_state_var;
    parse_state_t *parse_state = &parse_state_var;
    uint64_t max_token_number = 1024;
    jsmntok_t *token_buffer;
    int parse_result;
    for ( ; /* parse unsuccessful */; ) {
        token_buffer = njt_pcalloc(pool, sizeof(jsmntok_t)*max_token_number);
        parse_result = builtin_parse_json_string(pool, parse_state, token_buffer, max_token_number, (char *)json_string->data, json_string->len, err_ret);
        if (parse_result == JSMN_ERROR_INVAL) {
            LOG_ERROR_JSON_PARSE(INVALID_JSON_CHAR_ERR, "", -1, "%s", "Invalid character inside JSON string");
            return NULL;
        }
        if (parse_result == JSMN_ERROR_PART) {
            LOG_ERROR_JSON_PARSE(PARTIAL_JSON_ERR, "", -1, "%s", "The string is not a full JSON packet, more bytes expected");
            return NULL;
        }
        if (parse_result == JSMN_ERROR_NOMEM) {
            max_token_number += max_token_number;
            continue;
        }
        if (parse_result == 0) {
            LOG_ERROR_JSON_PARSE(NULL_JSON_ERR, "", 0, "String did not contain %s JSON tokens", "any");
            return NULL;
        }
        break; // parse success
    }
    out = njt_pcalloc(pool, sizeof(dynstreamlua_t));;
    if (parse_dynstreamlua(pool, parse_state, out, err_ret)) {
        return NULL;
    }
    return out;
}

njt_str_t* to_json_dynstreamlua(njt_pool_t *pool, dynstreamlua_t* out, njt_int_t flags) {
    njt_str_t *json_str;
    json_str = njt_pcalloc(pool, sizeof(njt_str_t));
    size_t str_len = 0;
    get_json_length_dynstreamlua(pool, out, &str_len, flags);
    json_str->data = (u_char*)njt_pcalloc(pool, str_len + 1);
    json_str->len = 0;
    to_oneline_json_dynstreamlua(pool, out, json_str, flags);
    return json_str;
}
