

/* This file was generated by JSON Schema to C.
 * Any changes made to it will be lost on regeneration. 

 * Copyright (C) 2021-2023  TMLake(Beijing) Technology Co., Ltd.
 */

#ifndef PARSER_CACHE_API_H
#define PARSER_CACHE_API_H
#include <stdint.h>
#include <stdbool.h>
#include "njt_core.h"
#include "js2c_njet_builtins.h"
/* ===================== Generated type declarations ===================== */
typedef enum cache_api_type_t_e{
    CACHE_API_TYPE_ADD,
    CACHE_API_TYPE_DEL,
    CACHE_API_TYPE_DOWNLOAD_STATUS
} cache_api_type_t;

typedef njt_str_t cache_api_location_name_t;

typedef njt_str_t cache_api_backend_server_t;

typedef struct cache_api_t_s {
    cache_api_type_t type;
    cache_api_location_name_t location_name;
    cache_api_backend_server_t backend_server;
    unsigned int is_type_set:1;
    unsigned int is_location_name_set:1;
    unsigned int is_backend_server_set:1;
} cache_api_t;

cache_api_type_t get_cache_api_type(cache_api_t *out);
cache_api_location_name_t* get_cache_api_location_name(cache_api_t *out);
cache_api_backend_server_t* get_cache_api_backend_server(cache_api_t *out);
void set_cache_api_type(cache_api_t* obj, cache_api_type_t field);
void set_cache_api_location_name(cache_api_t* obj, cache_api_location_name_t* field);
void set_cache_api_backend_server(cache_api_t* obj, cache_api_backend_server_t* field);
cache_api_t* create_cache_api(njt_pool_t *pool);
cache_api_t* json_parse_cache_api(njt_pool_t *pool, const njt_str_t *json_string, js2c_parse_error_t *err_ret);
njt_str_t* to_json_cache_api(njt_pool_t *pool, cache_api_t *out, njt_int_t flags);
#endif /* PARSER_CACHE_API_H */
