

/* This file was generated by JSON Schema to C.
 * Any changes made to it will be lost on regeneration. 

 * Copyright (C) 2021-2023  TMLake(Beijing) Technology Co., Ltd.
 */

#ifndef PARSER_CACHE_DEL_LOC_H
#define PARSER_CACHE_DEL_LOC_H
#include <stdint.h>
#include <stdbool.h>
#include "njt_core.h"
#include "js2c_njet_builtins.h"
/* ===================== Generated type declarations ===================== */
typedef enum cache_del_dyn_location_type_t_e{
    CACHE_DEL_DYN_LOCATION_TYPE_DEL
} cache_del_dyn_location_type_t;

typedef njt_str_t cache_del_dyn_location_addr_port_t;

typedef njt_str_t cache_del_dyn_location_server_name_t;

typedef njt_str_t cache_del_dyn_location_location_rule_t;

typedef njt_str_t cache_del_dyn_location_location_name_t;

typedef struct cache_del_dyn_location_t_s {
    cache_del_dyn_location_type_t type;
    cache_del_dyn_location_addr_port_t addr_port;
    cache_del_dyn_location_server_name_t server_name;
    cache_del_dyn_location_location_rule_t location_rule;
    cache_del_dyn_location_location_name_t location_name;
    unsigned int is_type_set:1;
    unsigned int is_addr_port_set:1;
    unsigned int is_server_name_set:1;
    unsigned int is_location_rule_set:1;
    unsigned int is_location_name_set:1;
} cache_del_dyn_location_t;

cache_del_dyn_location_type_t get_cache_del_dyn_location_type(cache_del_dyn_location_t *out);
cache_del_dyn_location_addr_port_t* get_cache_del_dyn_location_addr_port(cache_del_dyn_location_t *out);
cache_del_dyn_location_server_name_t* get_cache_del_dyn_location_server_name(cache_del_dyn_location_t *out);
cache_del_dyn_location_location_rule_t* get_cache_del_dyn_location_location_rule(cache_del_dyn_location_t *out);
cache_del_dyn_location_location_name_t* get_cache_del_dyn_location_location_name(cache_del_dyn_location_t *out);
void set_cache_del_dyn_location_type(cache_del_dyn_location_t* obj, cache_del_dyn_location_type_t field);
void set_cache_del_dyn_location_addr_port(cache_del_dyn_location_t* obj, cache_del_dyn_location_addr_port_t* field);
void set_cache_del_dyn_location_server_name(cache_del_dyn_location_t* obj, cache_del_dyn_location_server_name_t* field);
void set_cache_del_dyn_location_location_rule(cache_del_dyn_location_t* obj, cache_del_dyn_location_location_rule_t* field);
void set_cache_del_dyn_location_location_name(cache_del_dyn_location_t* obj, cache_del_dyn_location_location_name_t* field);
cache_del_dyn_location_t* create_cache_del_dyn_location(njt_pool_t *pool);
cache_del_dyn_location_t* json_parse_cache_del_dyn_location(njt_pool_t *pool, const njt_str_t *json_string, js2c_parse_error_t *err_ret);
njt_str_t* to_json_cache_del_dyn_location(njt_pool_t *pool, cache_del_dyn_location_t *out, njt_int_t flags);
#endif /* PARSER_CACHE_DEL_LOC_H */
