

/* This file was generated by JSON Schema to C.
 * Any changes made to it will be lost on regeneration. 

 * Copyright (C) 2021-2023  TMLake(Beijing) Technology Co., Ltd.
 */

#include "njt_http_dyn_range_parser.h"
#include "njt_core.h"
#include "js2c_njet_builtins.h"
/* ========================== Generated parsers ========================== */


static bool parse_dyn_range_ranges_item_type(njt_pool_t *pool, parse_state_t *parse_state, dyn_range_ranges_item_type_t *out, js2c_parse_error_t *err_ret) {
    js2c_check_type(JSMN_STRING);
    if (current_string_is(parse_state, "tcp")) {
        *out = DYN_RANGE_RANGES_ITEM_TYPE_TCP;
    } else if (current_string_is(parse_state, "udp")) {
        *out = DYN_RANGE_RANGES_ITEM_TYPE_UDP;
    } else {
        LOG_ERROR_JSON_PARSE(UNKNOWN_ENUM_VALUE_ERR, parse_state->current_key, CURRENT_TOKEN(parse_state).start, "Unknown enum value in '%s': %.*s", parse_state->current_key, CURRENT_STRING_FOR_ERROR(parse_state));
        return true;
    }
    parse_state->current_token += 1;
    return false;
}


static bool parse_dyn_range_ranges_item(njt_pool_t *pool, parse_state_t *parse_state, dyn_range_ranges_item_t *out, js2c_parse_error_t *err_ret) {
    njt_uint_t i;

    js2c_check_type(JSMN_OBJECT);
    const int object_start_token = parse_state->current_token;
    const uint64_t n = parse_state->tokens[parse_state->current_token].size;
    parse_state->current_token += 1;
    for (i = 0; i < n; ++i) {
        js2c_key_children_check_for_obj();
        if (current_string_is(parse_state, "type")) {
            js2c_check_field_set(out->is_type_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "type";
            if (parse_dyn_range_ranges_item_type(pool, parse_state, (&out->type), err_ret)) {
                return true;
            }
            out->is_type_set = 1;
            parse_state->current_key = saved_key;
        } else if (current_string_is(parse_state, "src_ports")) {
            js2c_check_field_set(out->is_src_ports_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "src_ports";
            int token_size =  CURRENT_STRING_LENGTH(parse_state) ;
            ((&out->src_ports))->data = (u_char*)njt_pcalloc(pool, (size_t)(token_size + 1));
            js2c_malloc_check(((&out->src_ports))->data);
            ((&out->src_ports))->len = token_size;
            if (builtin_parse_string(pool, parse_state, (&out->src_ports), 0, ((&out->src_ports))->len, err_ret)) {
                return true;
            }
            out->is_src_ports_set = 1;
            parse_state->current_key = saved_key;
        } else if (current_string_is(parse_state, "dst_port")) {
            js2c_check_field_set(out->is_dst_port_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "dst_port";
            int64_t int_parse_tmp;
            if (builtin_parse_signed(pool, parse_state, true, false, 10, &int_parse_tmp, err_ret)) {
                return true;
            }
            js2c_int_range_check_min(1LL);
            *(&out->dst_port) = int_parse_tmp;
            out->is_dst_port_set = 1;
            parse_state->current_key = saved_key;
        } else if (current_string_is(parse_state, "try_del_times")) {
            js2c_check_field_set(out->is_try_del_times_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "try_del_times";
            js2c_null_check();
            int64_t int_parse_tmp;
            if (builtin_parse_signed(pool, parse_state, true, false, 10, &int_parse_tmp, err_ret)) {
                return true;
            }
            js2c_int_range_check_min(0LL);
            *(&out->try_del_times) = int_parse_tmp;
            out->is_try_del_times_set = 1;
            parse_state->current_key = saved_key;
        } else if (current_string_is(parse_state, "iptables_path")) {
            js2c_check_field_set(out->is_iptables_path_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "iptables_path";
            js2c_null_check();
            int token_size =  CURRENT_STRING_LENGTH(parse_state) ;
            ((&out->iptables_path))->data = (u_char*)njt_pcalloc(pool, (size_t)(token_size + 1));
            js2c_malloc_check(((&out->iptables_path))->data);
            ((&out->iptables_path))->len = token_size;
            if (builtin_parse_string(pool, parse_state, (&out->iptables_path), 0, ((&out->iptables_path))->len, err_ret)) {
                return true;
            }
            out->is_iptables_path_set = 1;
            parse_state->current_key = saved_key;
        } else {
            LOG_ERROR_JSON_PARSE(UNKNOWN_FIELD_ERR, parse_state->current_key, CURRENT_TOKEN(parse_state).start, "Unknown field in '%s': %.*s", parse_state->current_key, CURRENT_STRING_FOR_ERROR(parse_state));
            return true;
        }
    }
    const int saved_current_token = parse_state->current_token;
    parse_state->current_token = object_start_token;
    if (!out->is_src_ports_set) {
        LOG_ERROR_JSON_PARSE(MISSING_REQUIRED_FIELD_ERR, parse_state->current_key, CURRENT_TOKEN(parse_state).start, "Missing required field in '%s': src_ports", parse_state->current_key);
        return true;
    }
    // set default
    if (!out->is_try_del_times_set) {
        out->try_del_times = 0LL;
    }
    // set default
    if (!out->is_iptables_path_set) {
        size_t token_size = strlen("None");
        (out->iptables_path).data = (u_char*)njt_pcalloc(pool, token_size + 1);
        js2c_malloc_check((out->iptables_path).data);
        (out->iptables_path).len = token_size;
        if (out->iptables_path.len == 0) {
            (out->iptables_path).data[0] = 0;
        }
        if (token_size > 0) {
            njt_memcpy(out->iptables_path.data, "None", token_size);
        }
    }
    parse_state->current_token = saved_current_token;
    return false;
}


static bool parse_dyn_range_ranges(njt_pool_t *pool, parse_state_t *parse_state, dyn_range_ranges_t *out, js2c_parse_error_t *err_ret) {
    int i;
    js2c_check_type(JSMN_ARRAY);
    const int n = parse_state->tokens[parse_state->current_token].size;
    parse_state->current_token += 1;
    for (i = 0; i < n; ++i) {
        ((dyn_range_ranges_item_t**)out->elts)[i] = njt_pcalloc(pool, sizeof(dyn_range_ranges_item_t));
        memset(((dyn_range_ranges_item_t**)out->elts)[i], 0, sizeof(dyn_range_ranges_item_t));
        if (parse_dyn_range_ranges_item(pool, parse_state, ((dyn_range_ranges_item_t**)out->elts)[i], err_ret)) {
            return true;
        }
        out->nelts ++;
    }
    return false;
}


static bool parse_dyn_range(njt_pool_t *pool, parse_state_t *parse_state, dyn_range_t *out, js2c_parse_error_t *err_ret) {
    njt_uint_t i;

    js2c_check_type(JSMN_OBJECT);
    const int object_start_token = parse_state->current_token;
    const uint64_t n = parse_state->tokens[parse_state->current_token].size;
    parse_state->current_token += 1;
    for (i = 0; i < n; ++i) {
        js2c_key_children_check_for_obj();
        if (current_string_is(parse_state, "ranges")) {
            js2c_check_field_set(out->is_ranges_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "ranges";
            out->ranges = njt_array_create(pool, parse_state->tokens[parse_state->current_token].size ,sizeof(dyn_range_ranges_item_t*));
            js2c_malloc_check(out->ranges);

            if (parse_dyn_range_ranges(pool, parse_state, (out->ranges), err_ret)) {
                return true;
            }
            out->is_ranges_set = 1;
            parse_state->current_key = saved_key;
        } else {
            LOG_ERROR_JSON_PARSE(UNKNOWN_FIELD_ERR, parse_state->current_key, CURRENT_TOKEN(parse_state).start, "Unknown field in '%s': %.*s", parse_state->current_key, CURRENT_STRING_FOR_ERROR(parse_state));
            return true;
        }
    }
    const int saved_current_token = parse_state->current_token;
    parse_state->current_token = object_start_token;
    if (!out->is_ranges_set) {
        LOG_ERROR_JSON_PARSE(MISSING_REQUIRED_FIELD_ERR, parse_state->current_key, CURRENT_TOKEN(parse_state).start, "Missing required field in '%s': ranges", parse_state->current_key);
        return true;
    }
    parse_state->current_token = saved_current_token;
    return false;
}

// BEGIN GET_JSON_LENGTH ENUM

static void get_json_length_dyn_range_ranges_item_type(njt_pool_t *pool, dyn_range_ranges_item_type_t *out, size_t *length, njt_int_t flags) {
    if (*out == DYN_RANGE_RANGES_ITEM_TYPE_TCP) {
        // "tcp"
        *length += 3 + 2;
        return;
    }
    if (*out == DYN_RANGE_RANGES_ITEM_TYPE_UDP) {
        // "udp"
        *length += 3 + 2;
        return;
    }
}

static void get_json_length_dyn_range_ranges_item_src_ports(njt_pool_t *pool, dyn_range_ranges_item_src_ports_t *out, size_t *length, njt_int_t flags) {
    njt_str_t *dst = handle_escape_on_write(pool, out);
    *length += dst->len + 2; //  "str" 
}

static void get_json_length_dyn_range_ranges_item_dst_port(njt_pool_t *pool, dyn_range_ranges_item_dst_port_t *out, size_t *length, njt_int_t flags) {
    u_char str[24];
    u_char *cur;
    cur = njt_sprintf(str, "%L", *out);
    *length += cur - str;
}

static void get_json_length_dyn_range_ranges_item_try_del_times(njt_pool_t *pool, dyn_range_ranges_item_try_del_times_t *out, size_t *length, njt_int_t flags) {
    u_char str[24];
    u_char *cur;
    cur = njt_sprintf(str, "%L", *out);
    *length += cur - str;
}

static void get_json_length_dyn_range_ranges_item_iptables_path(njt_pool_t *pool, dyn_range_ranges_item_iptables_path_t *out, size_t *length, njt_int_t flags) {
    njt_str_t *dst = handle_escape_on_write(pool, out);
    *length += dst->len + 2; //  "str" 
}

static void get_json_length_dyn_range_ranges_item(njt_pool_t *pool, dyn_range_ranges_item_t *out, size_t *length, njt_int_t flags) {
    if (out == NULL) {
        *length += 4; // null
        return;
    }
    *length += 1;
    njt_int_t omit;
    njt_int_t count = 0;
    omit = 0;
    omit = out->is_type_set ? 0 : 1;
    if (omit == 0) {
        *length += (4 + 3); // "type": 
        get_json_length_dyn_range_ranges_item_type(pool, (&out->type), length, flags);
        *length += 1; // ","
        count++;
    }
    omit = 0;
    omit = out->is_src_ports_set ? 0 : 1;
    omit = (flags & OMIT_NULL_STR) && (out->src_ports.data) == NULL ? 1 : omit;
    if (omit == 0) {
        *length += (9 + 3); // "src_ports": 
        get_json_length_dyn_range_ranges_item_src_ports(pool, (&out->src_ports), length, flags);
        *length += 1; // ","
        count++;
    }
    omit = 0;
    omit = out->is_dst_port_set ? 0 : 1;
    if (omit == 0) {
        *length += (8 + 3); // "dst_port": 
        get_json_length_dyn_range_ranges_item_dst_port(pool, (&out->dst_port), length, flags);
        *length += 1; // ","
        count++;
    }
    omit = 0;
    omit = out->is_try_del_times_set ? 0 : 1;
    if (omit == 0) {
        *length += (13 + 3); // "try_del_times": 
        get_json_length_dyn_range_ranges_item_try_del_times(pool, (&out->try_del_times), length, flags);
        *length += 1; // ","
        count++;
    }
    omit = 0;
    omit = out->is_iptables_path_set ? 0 : 1;
    omit = (flags & OMIT_NULL_STR) && (out->iptables_path.data) == NULL ? 1 : omit;
    if (omit == 0) {
        *length += (13 + 3); // "iptables_path": 
        get_json_length_dyn_range_ranges_item_iptables_path(pool, (&out->iptables_path), length, flags);
        *length += 1; // ","
        count++;
    }
    if (count != 0) {
        *length -= 1; // "\b"
    }
    *length += 1;
}

static void get_json_length_dyn_range_ranges(njt_pool_t *pool, dyn_range_ranges_t *out, size_t *length, njt_int_t flags) {
    njt_uint_t i;
    njt_uint_t omit;
    njt_int_t count = 0;
    if (out == NULL) {
        *length += 2; // "[]"
        return;
    }
    *length += 2; // "[]"
    for (i = 0; i < out->nelts; ++i) {
        omit = 0;
        omit = ((flags & OMIT_NULL_OBJ) && ((dyn_range_ranges_item_t**)out->elts)[i] == NULL) ? 1 : 0;
        if (omit == 0) {
            get_json_length_dyn_range_ranges_item(pool, ((dyn_range_ranges_item_t**)out->elts)[i], length, flags);
            *length += 1; // ","
            count++; // ","
        }
    }
    if (count != 0) {
        *length -= 1; // "\b"
    }
}

static void get_json_length_dyn_range(njt_pool_t *pool, dyn_range_t *out, size_t *length, njt_int_t flags) {
    if (out == NULL) {
        *length += 4; // null
        return;
    }
    *length += 1;
    njt_int_t omit;
    njt_int_t count = 0;
    omit = 0;
    omit = out->is_ranges_set ? 0 : 1;
    omit = (flags & OMIT_NULL_ARRAY) && (out->ranges) == NULL ? 1 : omit;
    if (omit == 0) {
        *length += (6 + 3); // "ranges": 
        get_json_length_dyn_range_ranges(pool, (out->ranges), length, flags);
        *length += 1; // ","
        count++;
    }
    if (count != 0) {
        *length -= 1; // "\b"
    }
    *length += 1;
}

dyn_range_ranges_item_type_t get_dyn_range_ranges_item_type(dyn_range_ranges_item_t *out) {
    return out->type;
}

dyn_range_ranges_item_src_ports_t* get_dyn_range_ranges_item_src_ports(dyn_range_ranges_item_t *out) {
    return &out->src_ports;
}

dyn_range_ranges_item_dst_port_t get_dyn_range_ranges_item_dst_port(dyn_range_ranges_item_t *out) {
    return out->dst_port;
}

dyn_range_ranges_item_try_del_times_t get_dyn_range_ranges_item_try_del_times(dyn_range_ranges_item_t *out) {
    return out->try_del_times;
}

dyn_range_ranges_item_iptables_path_t* get_dyn_range_ranges_item_iptables_path(dyn_range_ranges_item_t *out) {
    return &out->iptables_path;
}
dyn_range_ranges_item_t* get_dyn_range_ranges_item(dyn_range_ranges_t *out, size_t idx) {
    return ((dyn_range_ranges_item_t**)out->elts)[idx];

}

dyn_range_ranges_t* get_dyn_range_ranges(dyn_range_t *out) {
    return out->ranges;
}
void set_dyn_range_ranges_item_type(dyn_range_ranges_item_t* obj, dyn_range_ranges_item_type_t field) {
    obj->type = field;
    obj->is_type_set = 1;
}
void set_dyn_range_ranges_item_src_ports(dyn_range_ranges_item_t* obj, dyn_range_ranges_item_src_ports_t* field) {
    njt_memcpy(&obj->src_ports, field, sizeof(njt_str_t));
    obj->is_src_ports_set = 1;
}
void set_dyn_range_ranges_item_dst_port(dyn_range_ranges_item_t* obj, dyn_range_ranges_item_dst_port_t field) {
    obj->dst_port = field;
    obj->is_dst_port_set = 1;
}
void set_dyn_range_ranges_item_try_del_times(dyn_range_ranges_item_t* obj, dyn_range_ranges_item_try_del_times_t field) {
    obj->try_del_times = field;
    obj->is_try_del_times_set = 1;
}
void set_dyn_range_ranges_item_iptables_path(dyn_range_ranges_item_t* obj, dyn_range_ranges_item_iptables_path_t* field) {
    njt_memcpy(&obj->iptables_path, field, sizeof(njt_str_t));
    obj->is_iptables_path_set = 1;
}
dyn_range_ranges_item_t* create_dyn_range_ranges_item(njt_pool_t *pool) {
    dyn_range_ranges_item_t* out = njt_pcalloc(pool, sizeof(dyn_range_ranges_item_t));
    return out;
}
int add_item_dyn_range_ranges(dyn_range_ranges_t *src, dyn_range_ranges_item_t* item) {
    void *new = njt_array_push(src);
    if (new == NULL) {
        return NJT_ERROR;
    }
    njt_memcpy(new, &item, src->size);
    return NJT_OK;
}

dyn_range_ranges_t* create_dyn_range_ranges(njt_pool_t *pool, size_t nelts) {
    return njt_array_create(pool, nelts, sizeof(dyn_range_ranges_item_t*));
}
void set_dyn_range_ranges(dyn_range_t* obj, dyn_range_ranges_t* field) {
    obj->ranges = field;
    obj->is_ranges_set = 1;
}
dyn_range_t* create_dyn_range(njt_pool_t *pool) {
    dyn_range_t* out = njt_pcalloc(pool, sizeof(dyn_range_t));
    return out;
}

static void to_oneline_json_dyn_range_ranges_item_type(njt_pool_t *pool, dyn_range_ranges_item_type_t *out, njt_str_t* buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    if (*out == DYN_RANGE_RANGES_ITEM_TYPE_TCP) {
        cur = njt_sprintf(cur, "\"tcp\"");
        buf->len += 3 + 2;
        return;
    }
    if (*out == DYN_RANGE_RANGES_ITEM_TYPE_UDP) {
        cur = njt_sprintf(cur, "\"udp\"");
        buf->len += 3 + 2;
        return;
    }
}

static void to_oneline_json_dyn_range_ranges_item_src_ports(njt_pool_t *pool, dyn_range_ranges_item_src_ports_t *out, njt_str_t *buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    njt_str_t *dst = handle_escape_on_write(pool, out);
    cur = njt_sprintf(cur, "\"%V\"", dst);
    buf->len = cur - buf->data;
}

static void to_oneline_json_dyn_range_ranges_item_dst_port(njt_pool_t *pool, dyn_range_ranges_item_dst_port_t *out, njt_str_t* buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    cur = njt_sprintf(cur, "%L", *out);
    buf->len = cur - buf->data;
}

static void to_oneline_json_dyn_range_ranges_item_try_del_times(njt_pool_t *pool, dyn_range_ranges_item_try_del_times_t *out, njt_str_t* buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    cur = njt_sprintf(cur, "%L", *out);
    buf->len = cur - buf->data;
}

static void to_oneline_json_dyn_range_ranges_item_iptables_path(njt_pool_t *pool, dyn_range_ranges_item_iptables_path_t *out, njt_str_t *buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    njt_str_t *dst = handle_escape_on_write(pool, out);
    cur = njt_sprintf(cur, "\"%V\"", dst);
    buf->len = cur - buf->data;
}

static void to_oneline_json_dyn_range_ranges_item(njt_pool_t *pool, dyn_range_ranges_item_t *out, njt_str_t* buf, njt_int_t flags) {
    njt_int_t omit;
    u_char* cur = buf->data + buf->len;
    if (out == NULL) {
        cur = njt_sprintf(cur, "null");
        buf->len += 4;
        return;
    }
    cur = njt_sprintf(cur, "{");
    buf->len ++;
    omit = 0;
    omit = out->is_type_set ? 0 : 1;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"type\":");
        buf->len = cur - buf->data;
        to_oneline_json_dyn_range_ranges_item_type(pool, (&out->type), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    omit = 0;
    omit = out->is_src_ports_set ? 0 : 1;
    omit = (flags & OMIT_NULL_STR) && (out->src_ports.data) == NULL ? 1 : omit;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"src_ports\":");
        buf->len = cur - buf->data;
        to_oneline_json_dyn_range_ranges_item_src_ports(pool, (&out->src_ports), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    omit = 0;
    omit = out->is_dst_port_set ? 0 : 1;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"dst_port\":");
        buf->len = cur - buf->data;
        to_oneline_json_dyn_range_ranges_item_dst_port(pool, (&out->dst_port), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    omit = 0;
    omit = out->is_try_del_times_set ? 0 : 1;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"try_del_times\":");
        buf->len = cur - buf->data;
        to_oneline_json_dyn_range_ranges_item_try_del_times(pool, (&out->try_del_times), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    omit = 0;
    omit = out->is_iptables_path_set ? 0 : 1;
    omit = (flags & OMIT_NULL_STR) && (out->iptables_path.data) == NULL ? 1 : omit;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"iptables_path\":");
        buf->len = cur - buf->data;
        to_oneline_json_dyn_range_ranges_item_iptables_path(pool, (&out->iptables_path), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    cur--;
    if (cur[0] == ',') {
        buf->len --;
    } else {
        cur ++;
    }
    cur = njt_sprintf(cur, "}");
    buf->len ++;
}

static void to_oneline_json_dyn_range_ranges(njt_pool_t *pool, dyn_range_ranges_t *out, njt_str_t* buf, njt_int_t flags) {
    njt_int_t omit;
    u_char *cur = buf->data + buf->len;
    njt_uint_t i;
    if (out == NULL || out->nelts == 0) {
        cur = njt_sprintf(cur, "[]");
        buf->len += 2;
        return;
    }
    cur = njt_sprintf(cur,  "[");
    buf->len ++;
    for (i = 0; i < out->nelts; ++i) {
        omit = 0;
        omit = ((flags & OMIT_NULL_OBJ) && ((dyn_range_ranges_item_t**)out->elts)[i] == NULL) ? 1 : 0;
        if (omit == 0) {
            to_oneline_json_dyn_range_ranges_item(pool, ((dyn_range_ranges_item_t**)out->elts)[i], buf, flags);
            cur = buf->data + buf->len;
            cur = njt_sprintf(cur, ",");
            buf->len ++;
        }
    }
    cur--;
    if (cur[0] == ',') {
        buf->len --;
    } else {
        cur ++;
    }
    cur = njt_sprintf(cur,  "]");
    buf->len ++;
}

static void to_oneline_json_dyn_range(njt_pool_t *pool, dyn_range_t *out, njt_str_t* buf, njt_int_t flags) {
    njt_int_t omit;
    u_char* cur = buf->data + buf->len;
    if (out == NULL) {
        cur = njt_sprintf(cur, "null");
        buf->len += 4;
        return;
    }
    cur = njt_sprintf(cur, "{");
    buf->len ++;
    omit = 0;
    omit = out->is_ranges_set ? 0 : 1;
    omit = (flags & OMIT_NULL_ARRAY) && (out->ranges) == NULL ? 1 : omit;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"ranges\":");
        buf->len = cur - buf->data;
        to_oneline_json_dyn_range_ranges(pool, (out->ranges), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    cur--;
    if (cur[0] == ',') {
        buf->len --;
    } else {
        cur ++;
    }
    cur = njt_sprintf(cur, "}");
    buf->len ++;
}
dyn_range_t* json_parse_dyn_range(njt_pool_t *pool, const njt_str_t *json_string, js2c_parse_error_t *err_ret) {
    dyn_range_t* out;
    parse_state_t parse_state_var;
    parse_state_t *parse_state = &parse_state_var;
    uint64_t max_token_number = 1024;
    jsmntok_t *token_buffer;
    int parse_result;
    for ( ; /* parse unsuccessful */; ) {
        token_buffer = njt_pcalloc(pool, sizeof(jsmntok_t)*max_token_number);
        parse_result = builtin_parse_json_string(pool, parse_state, token_buffer, max_token_number, (char *)json_string->data, json_string->len, err_ret);
        if (parse_result == JSMN_ERROR_INVAL) {
            LOG_ERROR_JSON_PARSE(INVALID_JSON_CHAR_ERR, "", -1, "%s", "Invalid character inside JSON string");
            return NULL;
        }
        if (parse_result == JSMN_ERROR_PART) {
            LOG_ERROR_JSON_PARSE(PARTIAL_JSON_ERR, "", -1, "%s", "The string is not a full JSON packet, more bytes expected");
            return NULL;
        }
        if (parse_result == JSMN_ERROR_NOMEM) {
            max_token_number += max_token_number;
            continue;
        }
        if (parse_result == 0) {
            LOG_ERROR_JSON_PARSE(NULL_JSON_ERR, "", 0, "String did not contain %s JSON tokens", "any");
            return NULL;
        }
        break; // parse success
    }
    out = njt_pcalloc(pool, sizeof(dyn_range_t));;
    if (parse_dyn_range(pool, parse_state, out, err_ret)) {
        return NULL;
    }
    return out;
}

njt_str_t* to_json_dyn_range(njt_pool_t *pool, dyn_range_t* out, njt_int_t flags) {
    njt_str_t *json_str;
    json_str = njt_pcalloc(pool, sizeof(njt_str_t));
    size_t str_len = 0;
    get_json_length_dyn_range(pool, out, &str_len, flags);
    json_str->data = (u_char*)njt_pcalloc(pool, str_len + 1);
    json_str->len = 0;
    to_oneline_json_dyn_range(pool, out, json_str, flags);
    return json_str;
}
