

/* This file was generated by JSON Schema to C.
 * Any changes made to it will be lost on regeneration. 

 * Copyright (C) 2021-2023  TMLake(Beijing) Technology Co., Ltd.
 */

#include "njt_http_dyn_bwlist_parser.h"
#include "njt_core.h"
#include "js2c_njet_builtins.h"
/* ========================== Generated parsers ========================== */

static bool parse_dynbwlist_locationDef(njt_pool_t *pool, parse_state_t *parse_state, dynbwlist_locationDef_t *out, js2c_parse_error_t *err_ret); //forward decl for public definition
static void get_json_length_dynbwlist_locationDef(njt_pool_t *pool, dynbwlist_locationDef_t *out, size_t *length, njt_int_t flags); //forward decl for public definition
static void to_oneline_json_dynbwlist_locationDef(njt_pool_t *pool, dynbwlist_locationDef_t *out, njt_str_t *buf, njt_int_t flags); //forward decl for public definition

static bool parse_dynbwlist_locationDef_accessIpv4_item_rule(njt_pool_t *pool, parse_state_t *parse_state, dynbwlist_locationDef_accessIpv4_item_rule_t *out, js2c_parse_error_t *err_ret) {
    js2c_check_type(JSMN_STRING);
    if (current_string_is(parse_state, "allow")) {
        *out = DYNBWLIST_LOCATIONDEF_ACCESSIPV4_ITEM_RULE_ALLOW;
    } else if (current_string_is(parse_state, "deny")) {
        *out = DYNBWLIST_LOCATIONDEF_ACCESSIPV4_ITEM_RULE_DENY;
    } else {
        LOG_ERROR_JSON_PARSE(UNKNOWN_ENUM_VALUE_ERR, parse_state->current_key, CURRENT_TOKEN(parse_state).start, "Unknown enum value in '%s': %.*s", parse_state->current_key, CURRENT_STRING_FOR_ERROR(parse_state));
        return true;
    }
    parse_state->current_token += 1;
    return false;
}


static bool parse_dynbwlist_locationDef_accessIpv4_item(njt_pool_t *pool, parse_state_t *parse_state, dynbwlist_locationDef_accessIpv4_item_t *out, js2c_parse_error_t *err_ret) {
    njt_uint_t i;

    js2c_check_type(JSMN_OBJECT);
    const int object_start_token = parse_state->current_token;
    const uint64_t n = parse_state->tokens[parse_state->current_token].size;
    parse_state->current_token += 1;
    for (i = 0; i < n; ++i) {
        js2c_key_children_check_for_obj();
        if (current_string_is(parse_state, "rule")) {
            js2c_check_field_set(out->is_rule_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "rule";
            if (parse_dynbwlist_locationDef_accessIpv4_item_rule(pool, parse_state, (&out->rule), err_ret)) {
                return true;
            }
            out->is_rule_set = 1;
            parse_state->current_key = saved_key;
        } else if (current_string_is(parse_state, "addr")) {
            js2c_check_field_set(out->is_addr_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "addr";
            int token_size =  CURRENT_STRING_LENGTH(parse_state) ;
            ((&out->addr))->data = (u_char*)njt_pcalloc(pool, (size_t)(token_size + 1));
            js2c_malloc_check(((&out->addr))->data);
            ((&out->addr))->len = token_size;
            if (builtin_parse_string(pool, parse_state, (&out->addr), 0, ((&out->addr))->len, err_ret)) {
                return true;
            }
            out->is_addr_set = 1;
            parse_state->current_key = saved_key;
        } else if (current_string_is(parse_state, "mask")) {
            js2c_check_field_set(out->is_mask_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "mask";
            int token_size =  CURRENT_STRING_LENGTH(parse_state) ;
            ((&out->mask))->data = (u_char*)njt_pcalloc(pool, (size_t)(token_size + 1));
            js2c_malloc_check(((&out->mask))->data);
            ((&out->mask))->len = token_size;
            if (builtin_parse_string(pool, parse_state, (&out->mask), 0, ((&out->mask))->len, err_ret)) {
                return true;
            }
            out->is_mask_set = 1;
            parse_state->current_key = saved_key;
        } else {
            LOG_ERROR_JSON_PARSE(UNKNOWN_FIELD_ERR, parse_state->current_key, CURRENT_TOKEN(parse_state).start, "Unknown field in '%s': %.*s", parse_state->current_key, CURRENT_STRING_FOR_ERROR(parse_state));
            return true;
        }
    }
    const int saved_current_token = parse_state->current_token;
    parse_state->current_token = object_start_token;
    if (!out->is_rule_set) {
        LOG_ERROR_JSON_PARSE(MISSING_REQUIRED_FIELD_ERR, parse_state->current_key, CURRENT_TOKEN(parse_state).start, "Missing required field in '%s': rule", parse_state->current_key);
        return true;
    }
    if (!out->is_addr_set) {
        LOG_ERROR_JSON_PARSE(MISSING_REQUIRED_FIELD_ERR, parse_state->current_key, CURRENT_TOKEN(parse_state).start, "Missing required field in '%s': addr", parse_state->current_key);
        return true;
    }
    if (!out->is_mask_set) {
        LOG_ERROR_JSON_PARSE(MISSING_REQUIRED_FIELD_ERR, parse_state->current_key, CURRENT_TOKEN(parse_state).start, "Missing required field in '%s': mask", parse_state->current_key);
        return true;
    }
    parse_state->current_token = saved_current_token;
    return false;
}


static bool parse_dynbwlist_locationDef_accessIpv4(njt_pool_t *pool, parse_state_t *parse_state, dynbwlist_locationDef_accessIpv4_t *out, js2c_parse_error_t *err_ret) {
    int i;
    js2c_check_type(JSMN_ARRAY);
    const int n = parse_state->tokens[parse_state->current_token].size;
    parse_state->current_token += 1;
    for (i = 0; i < n; ++i) {
        ((dynbwlist_locationDef_accessIpv4_item_t**)out->elts)[i] = njt_pcalloc(pool, sizeof(dynbwlist_locationDef_accessIpv4_item_t));
        memset(((dynbwlist_locationDef_accessIpv4_item_t**)out->elts)[i], 0, sizeof(dynbwlist_locationDef_accessIpv4_item_t));
        if (parse_dynbwlist_locationDef_accessIpv4_item(pool, parse_state, ((dynbwlist_locationDef_accessIpv4_item_t**)out->elts)[i], err_ret)) {
            return true;
        }
        out->nelts ++;
    }
    return false;
}


static bool parse_dynbwlist_locationDef_accessIpv6_item_rule(njt_pool_t *pool, parse_state_t *parse_state, dynbwlist_locationDef_accessIpv6_item_rule_t *out, js2c_parse_error_t *err_ret) {
    js2c_check_type(JSMN_STRING);
    if (current_string_is(parse_state, "allow")) {
        *out = DYNBWLIST_LOCATIONDEF_ACCESSIPV6_ITEM_RULE_ALLOW;
    } else if (current_string_is(parse_state, "deny")) {
        *out = DYNBWLIST_LOCATIONDEF_ACCESSIPV6_ITEM_RULE_DENY;
    } else {
        LOG_ERROR_JSON_PARSE(UNKNOWN_ENUM_VALUE_ERR, parse_state->current_key, CURRENT_TOKEN(parse_state).start, "Unknown enum value in '%s': %.*s", parse_state->current_key, CURRENT_STRING_FOR_ERROR(parse_state));
        return true;
    }
    parse_state->current_token += 1;
    return false;
}


static bool parse_dynbwlist_locationDef_accessIpv6_item(njt_pool_t *pool, parse_state_t *parse_state, dynbwlist_locationDef_accessIpv6_item_t *out, js2c_parse_error_t *err_ret) {
    njt_uint_t i;

    js2c_check_type(JSMN_OBJECT);
    const int object_start_token = parse_state->current_token;
    const uint64_t n = parse_state->tokens[parse_state->current_token].size;
    parse_state->current_token += 1;
    for (i = 0; i < n; ++i) {
        js2c_key_children_check_for_obj();
        if (current_string_is(parse_state, "rule")) {
            js2c_check_field_set(out->is_rule_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "rule";
            if (parse_dynbwlist_locationDef_accessIpv6_item_rule(pool, parse_state, (&out->rule), err_ret)) {
                return true;
            }
            out->is_rule_set = 1;
            parse_state->current_key = saved_key;
        } else if (current_string_is(parse_state, "addr")) {
            js2c_check_field_set(out->is_addr_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "addr";
            int token_size =  CURRENT_STRING_LENGTH(parse_state) ;
            ((&out->addr))->data = (u_char*)njt_pcalloc(pool, (size_t)(token_size + 1));
            js2c_malloc_check(((&out->addr))->data);
            ((&out->addr))->len = token_size;
            if (builtin_parse_string(pool, parse_state, (&out->addr), 0, ((&out->addr))->len, err_ret)) {
                return true;
            }
            out->is_addr_set = 1;
            parse_state->current_key = saved_key;
        } else if (current_string_is(parse_state, "mask")) {
            js2c_check_field_set(out->is_mask_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "mask";
            int token_size =  CURRENT_STRING_LENGTH(parse_state) ;
            ((&out->mask))->data = (u_char*)njt_pcalloc(pool, (size_t)(token_size + 1));
            js2c_malloc_check(((&out->mask))->data);
            ((&out->mask))->len = token_size;
            if (builtin_parse_string(pool, parse_state, (&out->mask), 0, ((&out->mask))->len, err_ret)) {
                return true;
            }
            out->is_mask_set = 1;
            parse_state->current_key = saved_key;
        } else {
            LOG_ERROR_JSON_PARSE(UNKNOWN_FIELD_ERR, parse_state->current_key, CURRENT_TOKEN(parse_state).start, "Unknown field in '%s': %.*s", parse_state->current_key, CURRENT_STRING_FOR_ERROR(parse_state));
            return true;
        }
    }
    const int saved_current_token = parse_state->current_token;
    parse_state->current_token = object_start_token;
    if (!out->is_rule_set) {
        LOG_ERROR_JSON_PARSE(MISSING_REQUIRED_FIELD_ERR, parse_state->current_key, CURRENT_TOKEN(parse_state).start, "Missing required field in '%s': rule", parse_state->current_key);
        return true;
    }
    if (!out->is_addr_set) {
        LOG_ERROR_JSON_PARSE(MISSING_REQUIRED_FIELD_ERR, parse_state->current_key, CURRENT_TOKEN(parse_state).start, "Missing required field in '%s': addr", parse_state->current_key);
        return true;
    }
    if (!out->is_mask_set) {
        LOG_ERROR_JSON_PARSE(MISSING_REQUIRED_FIELD_ERR, parse_state->current_key, CURRENT_TOKEN(parse_state).start, "Missing required field in '%s': mask", parse_state->current_key);
        return true;
    }
    parse_state->current_token = saved_current_token;
    return false;
}


static bool parse_dynbwlist_locationDef_accessIpv6(njt_pool_t *pool, parse_state_t *parse_state, dynbwlist_locationDef_accessIpv6_t *out, js2c_parse_error_t *err_ret) {
    int i;
    js2c_check_type(JSMN_ARRAY);
    const int n = parse_state->tokens[parse_state->current_token].size;
    parse_state->current_token += 1;
    for (i = 0; i < n; ++i) {
        ((dynbwlist_locationDef_accessIpv6_item_t**)out->elts)[i] = njt_pcalloc(pool, sizeof(dynbwlist_locationDef_accessIpv6_item_t));
        memset(((dynbwlist_locationDef_accessIpv6_item_t**)out->elts)[i], 0, sizeof(dynbwlist_locationDef_accessIpv6_item_t));
        if (parse_dynbwlist_locationDef_accessIpv6_item(pool, parse_state, ((dynbwlist_locationDef_accessIpv6_item_t**)out->elts)[i], err_ret)) {
            return true;
        }
        out->nelts ++;
    }
    return false;
}


static bool parse_dynbwlist_locationDef_locations(njt_pool_t *pool, parse_state_t *parse_state, dynbwlist_locationDef_locations_t *out, js2c_parse_error_t *err_ret) {
    int i;
    js2c_check_type(JSMN_ARRAY);
    const int n = parse_state->tokens[parse_state->current_token].size;
    parse_state->current_token += 1;
    for (i = 0; i < n; ++i) {
        ((dynbwlist_locationDef_locations_item_t**)out->elts)[i] = njt_pcalloc(pool, sizeof(dynbwlist_locationDef_t));
        memset(((dynbwlist_locationDef_locations_item_t**)out->elts)[i], 0, sizeof(dynbwlist_locationDef_locations_item_t));
        if (parse_dynbwlist_locationDef(pool, parse_state, ((dynbwlist_locationDef_locations_item_t**)out->elts)[i], err_ret)) {
            return true;
        }
        out->nelts ++;
    }
    return false;
}


static bool parse_dynbwlist_locationDef(njt_pool_t *pool, parse_state_t *parse_state, dynbwlist_locationDef_t *out, js2c_parse_error_t *err_ret) {
    njt_uint_t i;

    js2c_check_type(JSMN_OBJECT);
    const int object_start_token = parse_state->current_token;
    const uint64_t n = parse_state->tokens[parse_state->current_token].size;
    parse_state->current_token += 1;
    for (i = 0; i < n; ++i) {
        js2c_key_children_check_for_obj();
        if (current_string_is(parse_state, "location")) {
            js2c_check_field_set(out->is_location_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "location";
            int token_size =  CURRENT_STRING_LENGTH(parse_state) ;
            ((&out->location))->data = (u_char*)njt_pcalloc(pool, (size_t)(token_size + 1));
            js2c_malloc_check(((&out->location))->data);
            ((&out->location))->len = token_size;
            if (builtin_parse_string(pool, parse_state, (&out->location), 0, ((&out->location))->len, err_ret)) {
                return true;
            }
            out->is_location_set = 1;
            parse_state->current_key = saved_key;
        } else if (current_string_is(parse_state, "accessIpv4")) {
            js2c_check_field_set(out->is_accessIpv4_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "accessIpv4";
            js2c_null_check();
            out->accessIpv4 = njt_array_create(pool, parse_state->tokens[parse_state->current_token].size ,sizeof(dynbwlist_locationDef_accessIpv4_item_t*));
            js2c_malloc_check(out->accessIpv4);

            if (parse_dynbwlist_locationDef_accessIpv4(pool, parse_state, (out->accessIpv4), err_ret)) {
                return true;
            }
            out->is_accessIpv4_set = 1;
            parse_state->current_key = saved_key;
        } else if (current_string_is(parse_state, "accessIpv6")) {
            js2c_check_field_set(out->is_accessIpv6_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "accessIpv6";
            js2c_null_check();
            out->accessIpv6 = njt_array_create(pool, parse_state->tokens[parse_state->current_token].size ,sizeof(dynbwlist_locationDef_accessIpv6_item_t*));
            js2c_malloc_check(out->accessIpv6);

            if (parse_dynbwlist_locationDef_accessIpv6(pool, parse_state, (out->accessIpv6), err_ret)) {
                return true;
            }
            out->is_accessIpv6_set = 1;
            parse_state->current_key = saved_key;
        } else if (current_string_is(parse_state, "locations")) {
            js2c_check_field_set(out->is_locations_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "locations";
            js2c_null_check();
            out->locations = njt_array_create(pool, parse_state->tokens[parse_state->current_token].size ,sizeof(dynbwlist_locationDef_locations_item_t*));
            js2c_malloc_check(out->locations);

            if (parse_dynbwlist_locationDef_locations(pool, parse_state, (out->locations), err_ret)) {
                return true;
            }
            out->is_locations_set = 1;
            parse_state->current_key = saved_key;
        } else {
            LOG_ERROR_JSON_PARSE(UNKNOWN_FIELD_ERR, parse_state->current_key, CURRENT_TOKEN(parse_state).start, "Unknown field in '%s': %.*s", parse_state->current_key, CURRENT_STRING_FOR_ERROR(parse_state));
            return true;
        }
    }
    const int saved_current_token = parse_state->current_token;
    parse_state->current_token = object_start_token;
    if (!out->is_location_set) {
        LOG_ERROR_JSON_PARSE(MISSING_REQUIRED_FIELD_ERR, parse_state->current_key, CURRENT_TOKEN(parse_state).start, "Missing required field in '%s': location", parse_state->current_key);
        return true;
    }
    // set default
    if (!out->is_accessIpv4_set) {
        out->accessIpv4 = njt_pcalloc(pool, sizeof(njt_array_t));
    }
    // set default
    if (!out->is_accessIpv6_set) {
        out->accessIpv6 = njt_pcalloc(pool, sizeof(njt_array_t));
    }
    // set default
    if (!out->is_locations_set) {
        out->locations = njt_pcalloc(pool, sizeof(njt_array_t));
    }
    parse_state->current_token = saved_current_token;
    return false;
}


static void get_json_length_dynbwlist_locationDef_location(njt_pool_t *pool, dynbwlist_locationDef_location_t *out, size_t *length, njt_int_t flags) {
    njt_str_t *dst = handle_escape_on_write(pool, out);
    *length += dst->len + 2; //  "str" 
}
// BEGIN GET_JSON_LENGTH ENUM

static void get_json_length_dynbwlist_locationDef_accessIpv4_item_rule(njt_pool_t *pool, dynbwlist_locationDef_accessIpv4_item_rule_t *out, size_t *length, njt_int_t flags) {
    if (*out == DYNBWLIST_LOCATIONDEF_ACCESSIPV4_ITEM_RULE_ALLOW) {
        // "allow"
        *length += 5 + 2;
        return;
    }
    if (*out == DYNBWLIST_LOCATIONDEF_ACCESSIPV4_ITEM_RULE_DENY) {
        // "deny"
        *length += 4 + 2;
        return;
    }
}

static void get_json_length_dynbwlist_locationDef_accessIpv4_item_addr(njt_pool_t *pool, dynbwlist_locationDef_accessIpv4_item_addr_t *out, size_t *length, njt_int_t flags) {
    njt_str_t *dst = handle_escape_on_write(pool, out);
    *length += dst->len + 2; //  "str" 
}

static void get_json_length_dynbwlist_locationDef_accessIpv4_item_mask(njt_pool_t *pool, dynbwlist_locationDef_accessIpv4_item_mask_t *out, size_t *length, njt_int_t flags) {
    njt_str_t *dst = handle_escape_on_write(pool, out);
    *length += dst->len + 2; //  "str" 
}

static void get_json_length_dynbwlist_locationDef_accessIpv4_item(njt_pool_t *pool, dynbwlist_locationDef_accessIpv4_item_t *out, size_t *length, njt_int_t flags) {
    if (out == NULL) {
        *length += 4; // null
        return;
    }
    *length += 1;
    njt_int_t omit;
    njt_int_t count = 0;
    omit = 0;
    omit = out->is_rule_set ? 0 : 1;
    if (omit == 0) {
        *length += (4 + 3); // "rule": 
        get_json_length_dynbwlist_locationDef_accessIpv4_item_rule(pool, (&out->rule), length, flags);
        *length += 1; // ","
        count++;
    }
    omit = 0;
    omit = out->is_addr_set ? 0 : 1;
    omit = (flags & OMIT_NULL_STR) && (out->addr.data) == NULL ? 1 : omit;
    if (omit == 0) {
        *length += (4 + 3); // "addr": 
        get_json_length_dynbwlist_locationDef_accessIpv4_item_addr(pool, (&out->addr), length, flags);
        *length += 1; // ","
        count++;
    }
    omit = 0;
    omit = out->is_mask_set ? 0 : 1;
    omit = (flags & OMIT_NULL_STR) && (out->mask.data) == NULL ? 1 : omit;
    if (omit == 0) {
        *length += (4 + 3); // "mask": 
        get_json_length_dynbwlist_locationDef_accessIpv4_item_mask(pool, (&out->mask), length, flags);
        *length += 1; // ","
        count++;
    }
    if (count != 0) {
        *length -= 1; // "\b"
    }
    *length += 1;
}

static void get_json_length_dynbwlist_locationDef_accessIpv4(njt_pool_t *pool, dynbwlist_locationDef_accessIpv4_t *out, size_t *length, njt_int_t flags) {
    njt_uint_t i;
    njt_uint_t omit;
    njt_int_t count = 0;
    if (out == NULL) {
        *length += 2; // "[]"
        return;
    }
    *length += 2; // "[]"
    for (i = 0; i < out->nelts; ++i) {
        omit = 0;
        omit = ((flags & OMIT_NULL_OBJ) && ((dynbwlist_locationDef_accessIpv4_item_t**)out->elts)[i] == NULL) ? 1 : 0;
        if (omit == 0) {
            get_json_length_dynbwlist_locationDef_accessIpv4_item(pool, ((dynbwlist_locationDef_accessIpv4_item_t**)out->elts)[i], length, flags);
            *length += 1; // ","
            count++; // ","
        }
    }
    if (count != 0) {
        *length -= 1; // "\b"
    }
}
// BEGIN GET_JSON_LENGTH ENUM

static void get_json_length_dynbwlist_locationDef_accessIpv6_item_rule(njt_pool_t *pool, dynbwlist_locationDef_accessIpv6_item_rule_t *out, size_t *length, njt_int_t flags) {
    if (*out == DYNBWLIST_LOCATIONDEF_ACCESSIPV6_ITEM_RULE_ALLOW) {
        // "allow"
        *length += 5 + 2;
        return;
    }
    if (*out == DYNBWLIST_LOCATIONDEF_ACCESSIPV6_ITEM_RULE_DENY) {
        // "deny"
        *length += 4 + 2;
        return;
    }
}

static void get_json_length_dynbwlist_locationDef_accessIpv6_item_addr(njt_pool_t *pool, dynbwlist_locationDef_accessIpv6_item_addr_t *out, size_t *length, njt_int_t flags) {
    njt_str_t *dst = handle_escape_on_write(pool, out);
    *length += dst->len + 2; //  "str" 
}

static void get_json_length_dynbwlist_locationDef_accessIpv6_item_mask(njt_pool_t *pool, dynbwlist_locationDef_accessIpv6_item_mask_t *out, size_t *length, njt_int_t flags) {
    njt_str_t *dst = handle_escape_on_write(pool, out);
    *length += dst->len + 2; //  "str" 
}

static void get_json_length_dynbwlist_locationDef_accessIpv6_item(njt_pool_t *pool, dynbwlist_locationDef_accessIpv6_item_t *out, size_t *length, njt_int_t flags) {
    if (out == NULL) {
        *length += 4; // null
        return;
    }
    *length += 1;
    njt_int_t omit;
    njt_int_t count = 0;
    omit = 0;
    omit = out->is_rule_set ? 0 : 1;
    if (omit == 0) {
        *length += (4 + 3); // "rule": 
        get_json_length_dynbwlist_locationDef_accessIpv6_item_rule(pool, (&out->rule), length, flags);
        *length += 1; // ","
        count++;
    }
    omit = 0;
    omit = out->is_addr_set ? 0 : 1;
    omit = (flags & OMIT_NULL_STR) && (out->addr.data) == NULL ? 1 : omit;
    if (omit == 0) {
        *length += (4 + 3); // "addr": 
        get_json_length_dynbwlist_locationDef_accessIpv6_item_addr(pool, (&out->addr), length, flags);
        *length += 1; // ","
        count++;
    }
    omit = 0;
    omit = out->is_mask_set ? 0 : 1;
    omit = (flags & OMIT_NULL_STR) && (out->mask.data) == NULL ? 1 : omit;
    if (omit == 0) {
        *length += (4 + 3); // "mask": 
        get_json_length_dynbwlist_locationDef_accessIpv6_item_mask(pool, (&out->mask), length, flags);
        *length += 1; // ","
        count++;
    }
    if (count != 0) {
        *length -= 1; // "\b"
    }
    *length += 1;
}

static void get_json_length_dynbwlist_locationDef_accessIpv6(njt_pool_t *pool, dynbwlist_locationDef_accessIpv6_t *out, size_t *length, njt_int_t flags) {
    njt_uint_t i;
    njt_uint_t omit;
    njt_int_t count = 0;
    if (out == NULL) {
        *length += 2; // "[]"
        return;
    }
    *length += 2; // "[]"
    for (i = 0; i < out->nelts; ++i) {
        omit = 0;
        omit = ((flags & OMIT_NULL_OBJ) && ((dynbwlist_locationDef_accessIpv6_item_t**)out->elts)[i] == NULL) ? 1 : 0;
        if (omit == 0) {
            get_json_length_dynbwlist_locationDef_accessIpv6_item(pool, ((dynbwlist_locationDef_accessIpv6_item_t**)out->elts)[i], length, flags);
            *length += 1; // ","
            count++; // ","
        }
    }
    if (count != 0) {
        *length -= 1; // "\b"
    }
}

static void get_json_length_dynbwlist_locationDef_locations_item(njt_pool_t *pool, dynbwlist_locationDef_locations_item_t *out, size_t *length, njt_int_t flags) {
    get_json_length_dynbwlist_locationDef(pool, out, length, flags);
}

static void get_json_length_dynbwlist_locationDef_locations(njt_pool_t *pool, dynbwlist_locationDef_locations_t *out, size_t *length, njt_int_t flags) {
    njt_uint_t i;
    njt_uint_t omit;
    njt_int_t count = 0;
    if (out == NULL) {
        *length += 2; // "[]"
        return;
    }
    *length += 2; // "[]"
    for (i = 0; i < out->nelts; ++i) {
        omit = 0;
        omit = ((flags & OMIT_NULL_OBJ) && ((dynbwlist_locationDef_locations_item_t**)out->elts)[i] == NULL) ? 1 : 0;
        if (omit == 0) {
            get_json_length_dynbwlist_locationDef_locations_item(pool, ((dynbwlist_locationDef_locations_item_t**)out->elts)[i], length, flags);
            *length += 1; // ","
            count++; // ","
        }
    }
    if (count != 0) {
        *length -= 1; // "\b"
    }
}

static void get_json_length_dynbwlist_locationDef(njt_pool_t *pool, dynbwlist_locationDef_t *out, size_t *length, njt_int_t flags) {
    if (out == NULL) {
        *length += 4; // null
        return;
    }
    *length += 1;
    njt_int_t omit;
    njt_int_t count = 0;
    omit = 0;
    omit = out->is_location_set ? 0 : 1;
    omit = (flags & OMIT_NULL_STR) && (out->location.data) == NULL ? 1 : omit;
    if (omit == 0) {
        *length += (8 + 3); // "location": 
        get_json_length_dynbwlist_locationDef_location(pool, (&out->location), length, flags);
        *length += 1; // ","
        count++;
    }
    omit = 0;
    omit = out->is_accessIpv4_set ? 0 : 1;
    omit = (flags & OMIT_NULL_ARRAY) && (out->accessIpv4) == NULL ? 1 : omit;
    if (omit == 0) {
        *length += (10 + 3); // "accessIpv4": 
        get_json_length_dynbwlist_locationDef_accessIpv4(pool, (out->accessIpv4), length, flags);
        *length += 1; // ","
        count++;
    }
    omit = 0;
    omit = out->is_accessIpv6_set ? 0 : 1;
    omit = (flags & OMIT_NULL_ARRAY) && (out->accessIpv6) == NULL ? 1 : omit;
    if (omit == 0) {
        *length += (10 + 3); // "accessIpv6": 
        get_json_length_dynbwlist_locationDef_accessIpv6(pool, (out->accessIpv6), length, flags);
        *length += 1; // ","
        count++;
    }
    omit = 0;
    omit = out->is_locations_set ? 0 : 1;
    omit = (flags & OMIT_NULL_ARRAY) && (out->locations) == NULL ? 1 : omit;
    if (omit == 0) {
        *length += (9 + 3); // "locations": 
        get_json_length_dynbwlist_locationDef_locations(pool, (out->locations), length, flags);
        *length += 1; // ","
        count++;
    }
    if (count != 0) {
        *length -= 1; // "\b"
    }
    *length += 1;
}

dynbwlist_locationDef_accessIpv4_item_rule_t get_dynbwlist_locationDef_accessIpv4_item_rule(dynbwlist_locationDef_accessIpv4_item_t *out) {
    return out->rule;
}

dynbwlist_locationDef_accessIpv4_item_addr_t* get_dynbwlist_locationDef_accessIpv4_item_addr(dynbwlist_locationDef_accessIpv4_item_t *out) {
    return &out->addr;
}

dynbwlist_locationDef_accessIpv4_item_mask_t* get_dynbwlist_locationDef_accessIpv4_item_mask(dynbwlist_locationDef_accessIpv4_item_t *out) {
    return &out->mask;
}
dynbwlist_locationDef_accessIpv4_item_t* get_dynbwlist_locationDef_accessIpv4_item(dynbwlist_locationDef_accessIpv4_t *out, size_t idx) {
    return ((dynbwlist_locationDef_accessIpv4_item_t**)out->elts)[idx];

}

dynbwlist_locationDef_accessIpv6_item_rule_t get_dynbwlist_locationDef_accessIpv6_item_rule(dynbwlist_locationDef_accessIpv6_item_t *out) {
    return out->rule;
}

dynbwlist_locationDef_accessIpv6_item_addr_t* get_dynbwlist_locationDef_accessIpv6_item_addr(dynbwlist_locationDef_accessIpv6_item_t *out) {
    return &out->addr;
}

dynbwlist_locationDef_accessIpv6_item_mask_t* get_dynbwlist_locationDef_accessIpv6_item_mask(dynbwlist_locationDef_accessIpv6_item_t *out) {
    return &out->mask;
}
dynbwlist_locationDef_accessIpv6_item_t* get_dynbwlist_locationDef_accessIpv6_item(dynbwlist_locationDef_accessIpv6_t *out, size_t idx) {
    return ((dynbwlist_locationDef_accessIpv6_item_t**)out->elts)[idx];

}
dynbwlist_locationDef_locations_item_t* get_dynbwlist_locationDef_locations_item(dynbwlist_locationDef_locations_t *out, size_t idx) {
    return ((dynbwlist_locationDef_locations_item_t**)out->elts)[idx];

}

dynbwlist_locationDef_location_t* get_dynbwlist_locationDef_location(dynbwlist_locationDef_t *out) {
    return &out->location;
}

dynbwlist_locationDef_accessIpv4_t* get_dynbwlist_locationDef_accessIpv4(dynbwlist_locationDef_t *out) {
    return out->accessIpv4;
}

dynbwlist_locationDef_accessIpv6_t* get_dynbwlist_locationDef_accessIpv6(dynbwlist_locationDef_t *out) {
    return out->accessIpv6;
}

dynbwlist_locationDef_locations_t* get_dynbwlist_locationDef_locations(dynbwlist_locationDef_t *out) {
    return out->locations;
}
void set_dynbwlist_locationDef_location(dynbwlist_locationDef_t* obj, dynbwlist_locationDef_location_t* field) {
    njt_memcpy(&obj->location, field, sizeof(njt_str_t));
    obj->is_location_set = 1;
}
void set_dynbwlist_locationDef_accessIpv4_item_rule(dynbwlist_locationDef_accessIpv4_item_t* obj, dynbwlist_locationDef_accessIpv4_item_rule_t field) {
    obj->rule = field;
    obj->is_rule_set = 1;
}
void set_dynbwlist_locationDef_accessIpv4_item_addr(dynbwlist_locationDef_accessIpv4_item_t* obj, dynbwlist_locationDef_accessIpv4_item_addr_t* field) {
    njt_memcpy(&obj->addr, field, sizeof(njt_str_t));
    obj->is_addr_set = 1;
}
void set_dynbwlist_locationDef_accessIpv4_item_mask(dynbwlist_locationDef_accessIpv4_item_t* obj, dynbwlist_locationDef_accessIpv4_item_mask_t* field) {
    njt_memcpy(&obj->mask, field, sizeof(njt_str_t));
    obj->is_mask_set = 1;
}
dynbwlist_locationDef_accessIpv4_item_t* create_dynbwlist_locationDef_accessIpv4_item(njt_pool_t *pool) {
    dynbwlist_locationDef_accessIpv4_item_t* out = njt_pcalloc(pool, sizeof(dynbwlist_locationDef_accessIpv4_item_t));
    return out;
}
int add_item_dynbwlist_locationDef_accessIpv4(dynbwlist_locationDef_accessIpv4_t *src, dynbwlist_locationDef_accessIpv4_item_t* item) {
    void *new = njt_array_push(src);
    if (new == NULL) {
        return NJT_ERROR;
    }
    njt_memcpy(new, &item, src->size);
    return NJT_OK;
}

dynbwlist_locationDef_accessIpv4_t* create_dynbwlist_locationDef_accessIpv4(njt_pool_t *pool, size_t nelts) {
    return njt_array_create(pool, nelts, sizeof(dynbwlist_locationDef_accessIpv4_item_t*));
}
void set_dynbwlist_locationDef_accessIpv4(dynbwlist_locationDef_t* obj, dynbwlist_locationDef_accessIpv4_t* field) {
    obj->accessIpv4 = field;
    obj->is_accessIpv4_set = 1;
}
void set_dynbwlist_locationDef_accessIpv6_item_rule(dynbwlist_locationDef_accessIpv6_item_t* obj, dynbwlist_locationDef_accessIpv6_item_rule_t field) {
    obj->rule = field;
    obj->is_rule_set = 1;
}
void set_dynbwlist_locationDef_accessIpv6_item_addr(dynbwlist_locationDef_accessIpv6_item_t* obj, dynbwlist_locationDef_accessIpv6_item_addr_t* field) {
    njt_memcpy(&obj->addr, field, sizeof(njt_str_t));
    obj->is_addr_set = 1;
}
void set_dynbwlist_locationDef_accessIpv6_item_mask(dynbwlist_locationDef_accessIpv6_item_t* obj, dynbwlist_locationDef_accessIpv6_item_mask_t* field) {
    njt_memcpy(&obj->mask, field, sizeof(njt_str_t));
    obj->is_mask_set = 1;
}
dynbwlist_locationDef_accessIpv6_item_t* create_dynbwlist_locationDef_accessIpv6_item(njt_pool_t *pool) {
    dynbwlist_locationDef_accessIpv6_item_t* out = njt_pcalloc(pool, sizeof(dynbwlist_locationDef_accessIpv6_item_t));
    return out;
}
int add_item_dynbwlist_locationDef_accessIpv6(dynbwlist_locationDef_accessIpv6_t *src, dynbwlist_locationDef_accessIpv6_item_t* item) {
    void *new = njt_array_push(src);
    if (new == NULL) {
        return NJT_ERROR;
    }
    njt_memcpy(new, &item, src->size);
    return NJT_OK;
}

dynbwlist_locationDef_accessIpv6_t* create_dynbwlist_locationDef_accessIpv6(njt_pool_t *pool, size_t nelts) {
    return njt_array_create(pool, nelts, sizeof(dynbwlist_locationDef_accessIpv6_item_t*));
}
void set_dynbwlist_locationDef_accessIpv6(dynbwlist_locationDef_t* obj, dynbwlist_locationDef_accessIpv6_t* field) {
    obj->accessIpv6 = field;
    obj->is_accessIpv6_set = 1;
}
int add_item_dynbwlist_locationDef_locations(dynbwlist_locationDef_locations_t *src, dynbwlist_locationDef_locations_item_t* item) {
    void *new = njt_array_push(src);
    if (new == NULL) {
        return NJT_ERROR;
    }
    njt_memcpy(new, &item, src->size);
    return NJT_OK;
}

dynbwlist_locationDef_locations_t* create_dynbwlist_locationDef_locations(njt_pool_t *pool, size_t nelts) {
    return njt_array_create(pool, nelts, sizeof(dynbwlist_locationDef_locations_item_t*));
}
void set_dynbwlist_locationDef_locations(dynbwlist_locationDef_t* obj, dynbwlist_locationDef_locations_t* field) {
    obj->locations = field;
    obj->is_locations_set = 1;
}
dynbwlist_locationDef_t* create_dynbwlist_locationDef(njt_pool_t *pool) {
    dynbwlist_locationDef_t* out = njt_pcalloc(pool, sizeof(dynbwlist_locationDef_t));
    return out;
}

static void to_oneline_json_dynbwlist_locationDef_location(njt_pool_t *pool, dynbwlist_locationDef_location_t *out, njt_str_t *buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    njt_str_t *dst = handle_escape_on_write(pool, out);
    cur = njt_sprintf(cur, "\"%V\"", dst);
    buf->len = cur - buf->data;
}

static void to_oneline_json_dynbwlist_locationDef_accessIpv4_item_rule(njt_pool_t *pool, dynbwlist_locationDef_accessIpv4_item_rule_t *out, njt_str_t* buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    if (*out == DYNBWLIST_LOCATIONDEF_ACCESSIPV4_ITEM_RULE_ALLOW) {
        cur = njt_sprintf(cur, "\"allow\"");
        buf->len += 5 + 2;
        return;
    }
    if (*out == DYNBWLIST_LOCATIONDEF_ACCESSIPV4_ITEM_RULE_DENY) {
        cur = njt_sprintf(cur, "\"deny\"");
        buf->len += 4 + 2;
        return;
    }
}

static void to_oneline_json_dynbwlist_locationDef_accessIpv4_item_addr(njt_pool_t *pool, dynbwlist_locationDef_accessIpv4_item_addr_t *out, njt_str_t *buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    njt_str_t *dst = handle_escape_on_write(pool, out);
    cur = njt_sprintf(cur, "\"%V\"", dst);
    buf->len = cur - buf->data;
}

static void to_oneline_json_dynbwlist_locationDef_accessIpv4_item_mask(njt_pool_t *pool, dynbwlist_locationDef_accessIpv4_item_mask_t *out, njt_str_t *buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    njt_str_t *dst = handle_escape_on_write(pool, out);
    cur = njt_sprintf(cur, "\"%V\"", dst);
    buf->len = cur - buf->data;
}

static void to_oneline_json_dynbwlist_locationDef_accessIpv4_item(njt_pool_t *pool, dynbwlist_locationDef_accessIpv4_item_t *out, njt_str_t* buf, njt_int_t flags) {
    njt_int_t omit;
    u_char* cur = buf->data + buf->len;
    if (out == NULL) {
        cur = njt_sprintf(cur, "null");
        buf->len += 4;
        return;
    }
    cur = njt_sprintf(cur, "{");
    buf->len ++;
    omit = 0;
    omit = out->is_rule_set ? 0 : 1;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"rule\":");
        buf->len = cur - buf->data;
        to_oneline_json_dynbwlist_locationDef_accessIpv4_item_rule(pool, (&out->rule), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    omit = 0;
    omit = out->is_addr_set ? 0 : 1;
    omit = (flags & OMIT_NULL_STR) && (out->addr.data) == NULL ? 1 : omit;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"addr\":");
        buf->len = cur - buf->data;
        to_oneline_json_dynbwlist_locationDef_accessIpv4_item_addr(pool, (&out->addr), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    omit = 0;
    omit = out->is_mask_set ? 0 : 1;
    omit = (flags & OMIT_NULL_STR) && (out->mask.data) == NULL ? 1 : omit;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"mask\":");
        buf->len = cur - buf->data;
        to_oneline_json_dynbwlist_locationDef_accessIpv4_item_mask(pool, (&out->mask), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    cur--;
    if (cur[0] == ',') {
        buf->len --;
    } else {
        cur ++;
    }
    cur = njt_sprintf(cur, "}");
    buf->len ++;
}

static void to_oneline_json_dynbwlist_locationDef_accessIpv4(njt_pool_t *pool, dynbwlist_locationDef_accessIpv4_t *out, njt_str_t* buf, njt_int_t flags) {
    njt_int_t omit;
    u_char *cur = buf->data + buf->len;
    njt_uint_t i;
    if (out == NULL || out->nelts == 0) {
        cur = njt_sprintf(cur, "[]");
        buf->len += 2;
        return;
    }
    cur = njt_sprintf(cur,  "[");
    buf->len ++;
    for (i = 0; i < out->nelts; ++i) {
        omit = 0;
        omit = ((flags & OMIT_NULL_OBJ) && ((dynbwlist_locationDef_accessIpv4_item_t**)out->elts)[i] == NULL) ? 1 : 0;
        if (omit == 0) {
            to_oneline_json_dynbwlist_locationDef_accessIpv4_item(pool, ((dynbwlist_locationDef_accessIpv4_item_t**)out->elts)[i], buf, flags);
            cur = buf->data + buf->len;
            cur = njt_sprintf(cur, ",");
            buf->len ++;
        }
    }
    cur--;
    if (cur[0] == ',') {
        buf->len --;
    } else {
        cur ++;
    }
    cur = njt_sprintf(cur,  "]");
    buf->len ++;
}

static void to_oneline_json_dynbwlist_locationDef_accessIpv6_item_rule(njt_pool_t *pool, dynbwlist_locationDef_accessIpv6_item_rule_t *out, njt_str_t* buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    if (*out == DYNBWLIST_LOCATIONDEF_ACCESSIPV6_ITEM_RULE_ALLOW) {
        cur = njt_sprintf(cur, "\"allow\"");
        buf->len += 5 + 2;
        return;
    }
    if (*out == DYNBWLIST_LOCATIONDEF_ACCESSIPV6_ITEM_RULE_DENY) {
        cur = njt_sprintf(cur, "\"deny\"");
        buf->len += 4 + 2;
        return;
    }
}

static void to_oneline_json_dynbwlist_locationDef_accessIpv6_item_addr(njt_pool_t *pool, dynbwlist_locationDef_accessIpv6_item_addr_t *out, njt_str_t *buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    njt_str_t *dst = handle_escape_on_write(pool, out);
    cur = njt_sprintf(cur, "\"%V\"", dst);
    buf->len = cur - buf->data;
}

static void to_oneline_json_dynbwlist_locationDef_accessIpv6_item_mask(njt_pool_t *pool, dynbwlist_locationDef_accessIpv6_item_mask_t *out, njt_str_t *buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    njt_str_t *dst = handle_escape_on_write(pool, out);
    cur = njt_sprintf(cur, "\"%V\"", dst);
    buf->len = cur - buf->data;
}

static void to_oneline_json_dynbwlist_locationDef_accessIpv6_item(njt_pool_t *pool, dynbwlist_locationDef_accessIpv6_item_t *out, njt_str_t* buf, njt_int_t flags) {
    njt_int_t omit;
    u_char* cur = buf->data + buf->len;
    if (out == NULL) {
        cur = njt_sprintf(cur, "null");
        buf->len += 4;
        return;
    }
    cur = njt_sprintf(cur, "{");
    buf->len ++;
    omit = 0;
    omit = out->is_rule_set ? 0 : 1;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"rule\":");
        buf->len = cur - buf->data;
        to_oneline_json_dynbwlist_locationDef_accessIpv6_item_rule(pool, (&out->rule), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    omit = 0;
    omit = out->is_addr_set ? 0 : 1;
    omit = (flags & OMIT_NULL_STR) && (out->addr.data) == NULL ? 1 : omit;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"addr\":");
        buf->len = cur - buf->data;
        to_oneline_json_dynbwlist_locationDef_accessIpv6_item_addr(pool, (&out->addr), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    omit = 0;
    omit = out->is_mask_set ? 0 : 1;
    omit = (flags & OMIT_NULL_STR) && (out->mask.data) == NULL ? 1 : omit;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"mask\":");
        buf->len = cur - buf->data;
        to_oneline_json_dynbwlist_locationDef_accessIpv6_item_mask(pool, (&out->mask), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    cur--;
    if (cur[0] == ',') {
        buf->len --;
    } else {
        cur ++;
    }
    cur = njt_sprintf(cur, "}");
    buf->len ++;
}

static void to_oneline_json_dynbwlist_locationDef_accessIpv6(njt_pool_t *pool, dynbwlist_locationDef_accessIpv6_t *out, njt_str_t* buf, njt_int_t flags) {
    njt_int_t omit;
    u_char *cur = buf->data + buf->len;
    njt_uint_t i;
    if (out == NULL || out->nelts == 0) {
        cur = njt_sprintf(cur, "[]");
        buf->len += 2;
        return;
    }
    cur = njt_sprintf(cur,  "[");
    buf->len ++;
    for (i = 0; i < out->nelts; ++i) {
        omit = 0;
        omit = ((flags & OMIT_NULL_OBJ) && ((dynbwlist_locationDef_accessIpv6_item_t**)out->elts)[i] == NULL) ? 1 : 0;
        if (omit == 0) {
            to_oneline_json_dynbwlist_locationDef_accessIpv6_item(pool, ((dynbwlist_locationDef_accessIpv6_item_t**)out->elts)[i], buf, flags);
            cur = buf->data + buf->len;
            cur = njt_sprintf(cur, ",");
            buf->len ++;
        }
    }
    cur--;
    if (cur[0] == ',') {
        buf->len --;
    } else {
        cur ++;
    }
    cur = njt_sprintf(cur,  "]");
    buf->len ++;
}
// to_oneline_json_REF

static void to_oneline_json_dynbwlist_locationDef_locations_item(njt_pool_t *pool, dynbwlist_locationDef_locations_item_t *out, njt_str_t* buf, njt_int_t flags) {
    to_oneline_json_dynbwlist_locationDef(pool, out, buf, flags);
}

static void to_oneline_json_dynbwlist_locationDef_locations(njt_pool_t *pool, dynbwlist_locationDef_locations_t *out, njt_str_t* buf, njt_int_t flags) {
    njt_int_t omit;
    u_char *cur = buf->data + buf->len;
    njt_uint_t i;
    if (out == NULL || out->nelts == 0) {
        cur = njt_sprintf(cur, "[]");
        buf->len += 2;
        return;
    }
    cur = njt_sprintf(cur,  "[");
    buf->len ++;
    for (i = 0; i < out->nelts; ++i) {
        omit = 0;
        omit = ((flags & OMIT_NULL_OBJ) && ((dynbwlist_locationDef_locations_item_t**)out->elts)[i] == NULL) ? 1 : 0;
        if (omit == 0) {
            to_oneline_json_dynbwlist_locationDef_locations_item(pool, ((dynbwlist_locationDef_locations_item_t**)out->elts)[i], buf, flags);
            cur = buf->data + buf->len;
            cur = njt_sprintf(cur, ",");
            buf->len ++;
        }
    }
    cur--;
    if (cur[0] == ',') {
        buf->len --;
    } else {
        cur ++;
    }
    cur = njt_sprintf(cur,  "]");
    buf->len ++;
}

static void to_oneline_json_dynbwlist_locationDef(njt_pool_t *pool, dynbwlist_locationDef_t *out, njt_str_t* buf, njt_int_t flags) {
    njt_int_t omit;
    u_char* cur = buf->data + buf->len;
    if (out == NULL) {
        cur = njt_sprintf(cur, "null");
        buf->len += 4;
        return;
    }
    cur = njt_sprintf(cur, "{");
    buf->len ++;
    omit = 0;
    omit = out->is_location_set ? 0 : 1;
    omit = (flags & OMIT_NULL_STR) && (out->location.data) == NULL ? 1 : omit;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"location\":");
        buf->len = cur - buf->data;
        to_oneline_json_dynbwlist_locationDef_location(pool, (&out->location), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    omit = 0;
    omit = out->is_accessIpv4_set ? 0 : 1;
    omit = (flags & OMIT_NULL_ARRAY) && (out->accessIpv4) == NULL ? 1 : omit;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"accessIpv4\":");
        buf->len = cur - buf->data;
        to_oneline_json_dynbwlist_locationDef_accessIpv4(pool, (out->accessIpv4), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    omit = 0;
    omit = out->is_accessIpv6_set ? 0 : 1;
    omit = (flags & OMIT_NULL_ARRAY) && (out->accessIpv6) == NULL ? 1 : omit;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"accessIpv6\":");
        buf->len = cur - buf->data;
        to_oneline_json_dynbwlist_locationDef_accessIpv6(pool, (out->accessIpv6), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    omit = 0;
    omit = out->is_locations_set ? 0 : 1;
    omit = (flags & OMIT_NULL_ARRAY) && (out->locations) == NULL ? 1 : omit;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"locations\":");
        buf->len = cur - buf->data;
        to_oneline_json_dynbwlist_locationDef_locations(pool, (out->locations), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    cur--;
    if (cur[0] == ',') {
        buf->len --;
    } else {
        cur ++;
    }
    cur = njt_sprintf(cur, "}");
    buf->len ++;
}

static bool parse_dynbwlist_servers_item_listens(njt_pool_t *pool, parse_state_t *parse_state, dynbwlist_servers_item_listens_t *out, js2c_parse_error_t *err_ret) {
    int i;
    js2c_check_type(JSMN_ARRAY);
    const int n = parse_state->tokens[parse_state->current_token].size;
    parse_state->current_token += 1;
    for (i = 0; i < n; ++i) {
        int token_size =  CURRENT_STRING_LENGTH(parse_state) ;
        ((&((dynbwlist_servers_item_listens_item_t*)out->elts)[i]))->data = (u_char*)njt_pcalloc(pool, (size_t)(token_size + 1));
        js2c_malloc_check(((&((dynbwlist_servers_item_listens_item_t*)out->elts)[i]))->data);
        ((&((dynbwlist_servers_item_listens_item_t*)out->elts)[i]))->len = token_size;
        if (builtin_parse_string(pool, parse_state, (&((dynbwlist_servers_item_listens_item_t*)out->elts)[i]), 1, ((&((dynbwlist_servers_item_listens_item_t*)out->elts)[i]))->len, err_ret)) {
            return true;
        }
        out->nelts ++;
    }
    return false;
}


static bool parse_dynbwlist_servers_item_serverNames(njt_pool_t *pool, parse_state_t *parse_state, dynbwlist_servers_item_serverNames_t *out, js2c_parse_error_t *err_ret) {
    int i;
    js2c_check_type(JSMN_ARRAY);
    const int n = parse_state->tokens[parse_state->current_token].size;
    parse_state->current_token += 1;
    for (i = 0; i < n; ++i) {
        int token_size =  CURRENT_STRING_LENGTH(parse_state) ;
        ((&((dynbwlist_servers_item_serverNames_item_t*)out->elts)[i]))->data = (u_char*)njt_pcalloc(pool, (size_t)(token_size + 1));
        js2c_malloc_check(((&((dynbwlist_servers_item_serverNames_item_t*)out->elts)[i]))->data);
        ((&((dynbwlist_servers_item_serverNames_item_t*)out->elts)[i]))->len = token_size;
        if (builtin_parse_string(pool, parse_state, (&((dynbwlist_servers_item_serverNames_item_t*)out->elts)[i]), 0, ((&((dynbwlist_servers_item_serverNames_item_t*)out->elts)[i]))->len, err_ret)) {
            return true;
        }
        out->nelts ++;
    }
    return false;
}


static bool parse_dynbwlist_servers_item_locations(njt_pool_t *pool, parse_state_t *parse_state, dynbwlist_servers_item_locations_t *out, js2c_parse_error_t *err_ret) {
    int i;
    js2c_check_type(JSMN_ARRAY);
    const int n = parse_state->tokens[parse_state->current_token].size;
    parse_state->current_token += 1;
    for (i = 0; i < n; ++i) {
        ((dynbwlist_servers_item_locations_item_t**)out->elts)[i] = njt_pcalloc(pool, sizeof(dynbwlist_locationDef_t));
        memset(((dynbwlist_servers_item_locations_item_t**)out->elts)[i], 0, sizeof(dynbwlist_servers_item_locations_item_t));
        if (parse_dynbwlist_locationDef(pool, parse_state, ((dynbwlist_servers_item_locations_item_t**)out->elts)[i], err_ret)) {
            return true;
        }
        out->nelts ++;
    }
    return false;
}


static bool parse_dynbwlist_servers_item(njt_pool_t *pool, parse_state_t *parse_state, dynbwlist_servers_item_t *out, js2c_parse_error_t *err_ret) {
    njt_uint_t i;

    js2c_check_type(JSMN_OBJECT);
    const int object_start_token = parse_state->current_token;
    const uint64_t n = parse_state->tokens[parse_state->current_token].size;
    parse_state->current_token += 1;
    for (i = 0; i < n; ++i) {
        js2c_key_children_check_for_obj();
        if (current_string_is(parse_state, "listens")) {
            js2c_check_field_set(out->is_listens_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "listens";
            out->listens = njt_array_create(pool, parse_state->tokens[parse_state->current_token].size ,sizeof(njt_str_t));
            js2c_malloc_check(out->listens);

            if (parse_dynbwlist_servers_item_listens(pool, parse_state, (out->listens), err_ret)) {
                return true;
            }
            out->is_listens_set = 1;
            parse_state->current_key = saved_key;
        } else if (current_string_is(parse_state, "serverNames")) {
            js2c_check_field_set(out->is_serverNames_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "serverNames";
            out->serverNames = njt_array_create(pool, parse_state->tokens[parse_state->current_token].size ,sizeof(njt_str_t));
            js2c_malloc_check(out->serverNames);

            if (parse_dynbwlist_servers_item_serverNames(pool, parse_state, (out->serverNames), err_ret)) {
                return true;
            }
            out->is_serverNames_set = 1;
            parse_state->current_key = saved_key;
        } else if (current_string_is(parse_state, "locations")) {
            js2c_check_field_set(out->is_locations_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "locations";
            out->locations = njt_array_create(pool, parse_state->tokens[parse_state->current_token].size ,sizeof(dynbwlist_servers_item_locations_item_t*));
            js2c_malloc_check(out->locations);

            if (parse_dynbwlist_servers_item_locations(pool, parse_state, (out->locations), err_ret)) {
                return true;
            }
            out->is_locations_set = 1;
            parse_state->current_key = saved_key;
        } else {
            LOG_ERROR_JSON_PARSE(UNKNOWN_FIELD_ERR, parse_state->current_key, CURRENT_TOKEN(parse_state).start, "Unknown field in '%s': %.*s", parse_state->current_key, CURRENT_STRING_FOR_ERROR(parse_state));
            return true;
        }
    }
    const int saved_current_token = parse_state->current_token;
    parse_state->current_token = object_start_token;
    if (!out->is_listens_set) {
        LOG_ERROR_JSON_PARSE(MISSING_REQUIRED_FIELD_ERR, parse_state->current_key, CURRENT_TOKEN(parse_state).start, "Missing required field in '%s': listens", parse_state->current_key);
        return true;
    }
    if (!out->is_serverNames_set) {
        LOG_ERROR_JSON_PARSE(MISSING_REQUIRED_FIELD_ERR, parse_state->current_key, CURRENT_TOKEN(parse_state).start, "Missing required field in '%s': serverNames", parse_state->current_key);
        return true;
    }
    if (!out->is_locations_set) {
        LOG_ERROR_JSON_PARSE(MISSING_REQUIRED_FIELD_ERR, parse_state->current_key, CURRENT_TOKEN(parse_state).start, "Missing required field in '%s': locations", parse_state->current_key);
        return true;
    }
    parse_state->current_token = saved_current_token;
    return false;
}


static bool parse_dynbwlist_servers(njt_pool_t *pool, parse_state_t *parse_state, dynbwlist_servers_t *out, js2c_parse_error_t *err_ret) {
    int i;
    js2c_check_type(JSMN_ARRAY);
    const int n = parse_state->tokens[parse_state->current_token].size;
    parse_state->current_token += 1;
    for (i = 0; i < n; ++i) {
        ((dynbwlist_servers_item_t**)out->elts)[i] = njt_pcalloc(pool, sizeof(dynbwlist_servers_item_t));
        memset(((dynbwlist_servers_item_t**)out->elts)[i], 0, sizeof(dynbwlist_servers_item_t));
        if (parse_dynbwlist_servers_item(pool, parse_state, ((dynbwlist_servers_item_t**)out->elts)[i], err_ret)) {
            return true;
        }
        out->nelts ++;
    }
    return false;
}


static bool parse_dynbwlist(njt_pool_t *pool, parse_state_t *parse_state, dynbwlist_t *out, js2c_parse_error_t *err_ret) {
    njt_uint_t i;

    js2c_check_type(JSMN_OBJECT);
    const int object_start_token = parse_state->current_token;
    const uint64_t n = parse_state->tokens[parse_state->current_token].size;
    parse_state->current_token += 1;
    for (i = 0; i < n; ++i) {
        js2c_key_children_check_for_obj();
        if (current_string_is(parse_state, "servers")) {
            js2c_check_field_set(out->is_servers_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "servers";
            out->servers = njt_array_create(pool, parse_state->tokens[parse_state->current_token].size ,sizeof(dynbwlist_servers_item_t*));
            js2c_malloc_check(out->servers);

            if (parse_dynbwlist_servers(pool, parse_state, (out->servers), err_ret)) {
                return true;
            }
            out->is_servers_set = 1;
            parse_state->current_key = saved_key;
        } else {
            LOG_ERROR_JSON_PARSE(UNKNOWN_FIELD_ERR, parse_state->current_key, CURRENT_TOKEN(parse_state).start, "Unknown field in '%s': %.*s", parse_state->current_key, CURRENT_STRING_FOR_ERROR(parse_state));
            return true;
        }
    }
    const int saved_current_token = parse_state->current_token;
    parse_state->current_token = object_start_token;
    if (!out->is_servers_set) {
        LOG_ERROR_JSON_PARSE(MISSING_REQUIRED_FIELD_ERR, parse_state->current_key, CURRENT_TOKEN(parse_state).start, "Missing required field in '%s': servers", parse_state->current_key);
        return true;
    }
    parse_state->current_token = saved_current_token;
    return false;
}


static void get_json_length_dynbwlist_servers_item_listens_item(njt_pool_t *pool, dynbwlist_servers_item_listens_item_t *out, size_t *length, njt_int_t flags) {
    njt_str_t *dst = handle_escape_on_write(pool, out);
    *length += dst->len + 2; //  "str" 
}

static void get_json_length_dynbwlist_servers_item_listens(njt_pool_t *pool, dynbwlist_servers_item_listens_t *out, size_t *length, njt_int_t flags) {
    njt_uint_t i;
    njt_uint_t omit;
    njt_int_t count = 0;
    if (out == NULL) {
        *length += 2; // "[]"
        return;
    }
    *length += 2; // "[]"
    for (i = 0; i < out->nelts; ++i) {
        omit = 0;
        omit = ((flags & OMIT_NULL_STR) && (&((dynbwlist_servers_item_listens_item_t*)out->elts)[i])->data == NULL) ? 1 : 0;
        if (omit == 0) {
            get_json_length_dynbwlist_servers_item_listens_item(pool, (&((dynbwlist_servers_item_listens_item_t*)out->elts)[i]), length, flags);
            *length += 1; // ","
            count++; // ","
        }
    }
    if (count != 0) {
        *length -= 1; // "\b"
    }
}

static void get_json_length_dynbwlist_servers_item_serverNames_item(njt_pool_t *pool, dynbwlist_servers_item_serverNames_item_t *out, size_t *length, njt_int_t flags) {
    njt_str_t *dst = handle_escape_on_write(pool, out);
    *length += dst->len + 2; //  "str" 
}

static void get_json_length_dynbwlist_servers_item_serverNames(njt_pool_t *pool, dynbwlist_servers_item_serverNames_t *out, size_t *length, njt_int_t flags) {
    njt_uint_t i;
    njt_uint_t omit;
    njt_int_t count = 0;
    if (out == NULL) {
        *length += 2; // "[]"
        return;
    }
    *length += 2; // "[]"
    for (i = 0; i < out->nelts; ++i) {
        omit = 0;
        omit = ((flags & OMIT_NULL_STR) && (&((dynbwlist_servers_item_serverNames_item_t*)out->elts)[i])->data == NULL) ? 1 : 0;
        if (omit == 0) {
            get_json_length_dynbwlist_servers_item_serverNames_item(pool, (&((dynbwlist_servers_item_serverNames_item_t*)out->elts)[i]), length, flags);
            *length += 1; // ","
            count++; // ","
        }
    }
    if (count != 0) {
        *length -= 1; // "\b"
    }
}

static void get_json_length_dynbwlist_servers_item_locations_item(njt_pool_t *pool, dynbwlist_servers_item_locations_item_t *out, size_t *length, njt_int_t flags) {
    get_json_length_dynbwlist_locationDef(pool, out, length, flags);
}

static void get_json_length_dynbwlist_servers_item_locations(njt_pool_t *pool, dynbwlist_servers_item_locations_t *out, size_t *length, njt_int_t flags) {
    njt_uint_t i;
    njt_uint_t omit;
    njt_int_t count = 0;
    if (out == NULL) {
        *length += 2; // "[]"
        return;
    }
    *length += 2; // "[]"
    for (i = 0; i < out->nelts; ++i) {
        omit = 0;
        omit = ((flags & OMIT_NULL_OBJ) && ((dynbwlist_servers_item_locations_item_t**)out->elts)[i] == NULL) ? 1 : 0;
        if (omit == 0) {
            get_json_length_dynbwlist_servers_item_locations_item(pool, ((dynbwlist_servers_item_locations_item_t**)out->elts)[i], length, flags);
            *length += 1; // ","
            count++; // ","
        }
    }
    if (count != 0) {
        *length -= 1; // "\b"
    }
}

static void get_json_length_dynbwlist_servers_item(njt_pool_t *pool, dynbwlist_servers_item_t *out, size_t *length, njt_int_t flags) {
    if (out == NULL) {
        *length += 4; // null
        return;
    }
    *length += 1;
    njt_int_t omit;
    njt_int_t count = 0;
    omit = 0;
    omit = out->is_listens_set ? 0 : 1;
    omit = (flags & OMIT_NULL_ARRAY) && (out->listens) == NULL ? 1 : omit;
    if (omit == 0) {
        *length += (7 + 3); // "listens": 
        get_json_length_dynbwlist_servers_item_listens(pool, (out->listens), length, flags);
        *length += 1; // ","
        count++;
    }
    omit = 0;
    omit = out->is_serverNames_set ? 0 : 1;
    omit = (flags & OMIT_NULL_ARRAY) && (out->serverNames) == NULL ? 1 : omit;
    if (omit == 0) {
        *length += (11 + 3); // "serverNames": 
        get_json_length_dynbwlist_servers_item_serverNames(pool, (out->serverNames), length, flags);
        *length += 1; // ","
        count++;
    }
    omit = 0;
    omit = out->is_locations_set ? 0 : 1;
    omit = (flags & OMIT_NULL_ARRAY) && (out->locations) == NULL ? 1 : omit;
    if (omit == 0) {
        *length += (9 + 3); // "locations": 
        get_json_length_dynbwlist_servers_item_locations(pool, (out->locations), length, flags);
        *length += 1; // ","
        count++;
    }
    if (count != 0) {
        *length -= 1; // "\b"
    }
    *length += 1;
}

static void get_json_length_dynbwlist_servers(njt_pool_t *pool, dynbwlist_servers_t *out, size_t *length, njt_int_t flags) {
    njt_uint_t i;
    njt_uint_t omit;
    njt_int_t count = 0;
    if (out == NULL) {
        *length += 2; // "[]"
        return;
    }
    *length += 2; // "[]"
    for (i = 0; i < out->nelts; ++i) {
        omit = 0;
        omit = ((flags & OMIT_NULL_OBJ) && ((dynbwlist_servers_item_t**)out->elts)[i] == NULL) ? 1 : 0;
        if (omit == 0) {
            get_json_length_dynbwlist_servers_item(pool, ((dynbwlist_servers_item_t**)out->elts)[i], length, flags);
            *length += 1; // ","
            count++; // ","
        }
    }
    if (count != 0) {
        *length -= 1; // "\b"
    }
}

static void get_json_length_dynbwlist(njt_pool_t *pool, dynbwlist_t *out, size_t *length, njt_int_t flags) {
    if (out == NULL) {
        *length += 4; // null
        return;
    }
    *length += 1;
    njt_int_t omit;
    njt_int_t count = 0;
    omit = 0;
    omit = out->is_servers_set ? 0 : 1;
    omit = (flags & OMIT_NULL_ARRAY) && (out->servers) == NULL ? 1 : omit;
    if (omit == 0) {
        *length += (7 + 3); // "servers": 
        get_json_length_dynbwlist_servers(pool, (out->servers), length, flags);
        *length += 1; // ","
        count++;
    }
    if (count != 0) {
        *length -= 1; // "\b"
    }
    *length += 1;
}
dynbwlist_servers_item_listens_item_t* get_dynbwlist_servers_item_listens_item(dynbwlist_servers_item_listens_t *out, size_t idx) {
    return &((dynbwlist_servers_item_listens_item_t*)out->elts)[idx];

}
dynbwlist_servers_item_serverNames_item_t* get_dynbwlist_servers_item_serverNames_item(dynbwlist_servers_item_serverNames_t *out, size_t idx) {
    return &((dynbwlist_servers_item_serverNames_item_t*)out->elts)[idx];

}
dynbwlist_servers_item_locations_item_t* get_dynbwlist_servers_item_locations_item(dynbwlist_servers_item_locations_t *out, size_t idx) {
    return ((dynbwlist_servers_item_locations_item_t**)out->elts)[idx];

}

dynbwlist_servers_item_listens_t* get_dynbwlist_servers_item_listens(dynbwlist_servers_item_t *out) {
    return out->listens;
}

dynbwlist_servers_item_serverNames_t* get_dynbwlist_servers_item_serverNames(dynbwlist_servers_item_t *out) {
    return out->serverNames;
}

dynbwlist_servers_item_locations_t* get_dynbwlist_servers_item_locations(dynbwlist_servers_item_t *out) {
    return out->locations;
}
dynbwlist_servers_item_t* get_dynbwlist_servers_item(dynbwlist_servers_t *out, size_t idx) {
    return ((dynbwlist_servers_item_t**)out->elts)[idx];

}

dynbwlist_servers_t* get_dynbwlist_servers(dynbwlist_t *out) {
    return out->servers;
}
int add_item_dynbwlist_servers_item_listens(dynbwlist_servers_item_listens_t *src, dynbwlist_servers_item_listens_item_t* item) {
    void *new = njt_array_push(src);
    if (new == NULL) {
        return NJT_ERROR;
    }
    njt_memcpy(new, item, src->size);
    return NJT_OK;
}

dynbwlist_servers_item_listens_t* create_dynbwlist_servers_item_listens(njt_pool_t *pool, size_t nelts) {
    return njt_array_create(pool, nelts, sizeof(dynbwlist_servers_item_listens_item_t));
}
void set_dynbwlist_servers_item_listens(dynbwlist_servers_item_t* obj, dynbwlist_servers_item_listens_t* field) {
    obj->listens = field;
    obj->is_listens_set = 1;
}
int add_item_dynbwlist_servers_item_serverNames(dynbwlist_servers_item_serverNames_t *src, dynbwlist_servers_item_serverNames_item_t* item) {
    void *new = njt_array_push(src);
    if (new == NULL) {
        return NJT_ERROR;
    }
    njt_memcpy(new, item, src->size);
    return NJT_OK;
}

dynbwlist_servers_item_serverNames_t* create_dynbwlist_servers_item_serverNames(njt_pool_t *pool, size_t nelts) {
    return njt_array_create(pool, nelts, sizeof(dynbwlist_servers_item_serverNames_item_t));
}
void set_dynbwlist_servers_item_serverNames(dynbwlist_servers_item_t* obj, dynbwlist_servers_item_serverNames_t* field) {
    obj->serverNames = field;
    obj->is_serverNames_set = 1;
}
int add_item_dynbwlist_servers_item_locations(dynbwlist_servers_item_locations_t *src, dynbwlist_servers_item_locations_item_t* item) {
    void *new = njt_array_push(src);
    if (new == NULL) {
        return NJT_ERROR;
    }
    njt_memcpy(new, &item, src->size);
    return NJT_OK;
}

dynbwlist_servers_item_locations_t* create_dynbwlist_servers_item_locations(njt_pool_t *pool, size_t nelts) {
    return njt_array_create(pool, nelts, sizeof(dynbwlist_servers_item_locations_item_t*));
}
void set_dynbwlist_servers_item_locations(dynbwlist_servers_item_t* obj, dynbwlist_servers_item_locations_t* field) {
    obj->locations = field;
    obj->is_locations_set = 1;
}
dynbwlist_servers_item_t* create_dynbwlist_servers_item(njt_pool_t *pool) {
    dynbwlist_servers_item_t* out = njt_pcalloc(pool, sizeof(dynbwlist_servers_item_t));
    return out;
}
int add_item_dynbwlist_servers(dynbwlist_servers_t *src, dynbwlist_servers_item_t* item) {
    void *new = njt_array_push(src);
    if (new == NULL) {
        return NJT_ERROR;
    }
    njt_memcpy(new, &item, src->size);
    return NJT_OK;
}

dynbwlist_servers_t* create_dynbwlist_servers(njt_pool_t *pool, size_t nelts) {
    return njt_array_create(pool, nelts, sizeof(dynbwlist_servers_item_t*));
}
void set_dynbwlist_servers(dynbwlist_t* obj, dynbwlist_servers_t* field) {
    obj->servers = field;
    obj->is_servers_set = 1;
}
dynbwlist_t* create_dynbwlist(njt_pool_t *pool) {
    dynbwlist_t* out = njt_pcalloc(pool, sizeof(dynbwlist_t));
    return out;
}

static void to_oneline_json_dynbwlist_servers_item_listens_item(njt_pool_t *pool, dynbwlist_servers_item_listens_item_t *out, njt_str_t *buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    njt_str_t *dst = handle_escape_on_write(pool, out);
    cur = njt_sprintf(cur, "\"%V\"", dst);
    buf->len = cur - buf->data;
}

static void to_oneline_json_dynbwlist_servers_item_listens(njt_pool_t *pool, dynbwlist_servers_item_listens_t *out, njt_str_t* buf, njt_int_t flags) {
    njt_int_t omit;
    u_char *cur = buf->data + buf->len;
    njt_uint_t i;
    if (out == NULL || out->nelts == 0) {
        cur = njt_sprintf(cur, "[]");
        buf->len += 2;
        return;
    }
    cur = njt_sprintf(cur,  "[");
    buf->len ++;
    for (i = 0; i < out->nelts; ++i) {
        omit = 0;
        omit = ((flags & OMIT_NULL_STR) && (&((dynbwlist_servers_item_listens_item_t*)out->elts)[i])->data == NULL) ? 1 : 0;
        if (omit == 0) {
            to_oneline_json_dynbwlist_servers_item_listens_item(pool, (&((dynbwlist_servers_item_listens_item_t*)out->elts)[i]), buf, flags);
            cur = buf->data + buf->len;
            cur = njt_sprintf(cur, ",");
            buf->len ++;
        }
    }
    cur--;
    if (cur[0] == ',') {
        buf->len --;
    } else {
        cur ++;
    }
    cur = njt_sprintf(cur,  "]");
    buf->len ++;
}

static void to_oneline_json_dynbwlist_servers_item_serverNames_item(njt_pool_t *pool, dynbwlist_servers_item_serverNames_item_t *out, njt_str_t *buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    njt_str_t *dst = handle_escape_on_write(pool, out);
    cur = njt_sprintf(cur, "\"%V\"", dst);
    buf->len = cur - buf->data;
}

static void to_oneline_json_dynbwlist_servers_item_serverNames(njt_pool_t *pool, dynbwlist_servers_item_serverNames_t *out, njt_str_t* buf, njt_int_t flags) {
    njt_int_t omit;
    u_char *cur = buf->data + buf->len;
    njt_uint_t i;
    if (out == NULL || out->nelts == 0) {
        cur = njt_sprintf(cur, "[]");
        buf->len += 2;
        return;
    }
    cur = njt_sprintf(cur,  "[");
    buf->len ++;
    for (i = 0; i < out->nelts; ++i) {
        omit = 0;
        omit = ((flags & OMIT_NULL_STR) && (&((dynbwlist_servers_item_serverNames_item_t*)out->elts)[i])->data == NULL) ? 1 : 0;
        if (omit == 0) {
            to_oneline_json_dynbwlist_servers_item_serverNames_item(pool, (&((dynbwlist_servers_item_serverNames_item_t*)out->elts)[i]), buf, flags);
            cur = buf->data + buf->len;
            cur = njt_sprintf(cur, ",");
            buf->len ++;
        }
    }
    cur--;
    if (cur[0] == ',') {
        buf->len --;
    } else {
        cur ++;
    }
    cur = njt_sprintf(cur,  "]");
    buf->len ++;
}
// to_oneline_json_REF

static void to_oneline_json_dynbwlist_servers_item_locations_item(njt_pool_t *pool, dynbwlist_servers_item_locations_item_t *out, njt_str_t* buf, njt_int_t flags) {
    to_oneline_json_dynbwlist_locationDef(pool, out, buf, flags);
}

static void to_oneline_json_dynbwlist_servers_item_locations(njt_pool_t *pool, dynbwlist_servers_item_locations_t *out, njt_str_t* buf, njt_int_t flags) {
    njt_int_t omit;
    u_char *cur = buf->data + buf->len;
    njt_uint_t i;
    if (out == NULL || out->nelts == 0) {
        cur = njt_sprintf(cur, "[]");
        buf->len += 2;
        return;
    }
    cur = njt_sprintf(cur,  "[");
    buf->len ++;
    for (i = 0; i < out->nelts; ++i) {
        omit = 0;
        omit = ((flags & OMIT_NULL_OBJ) && ((dynbwlist_servers_item_locations_item_t**)out->elts)[i] == NULL) ? 1 : 0;
        if (omit == 0) {
            to_oneline_json_dynbwlist_servers_item_locations_item(pool, ((dynbwlist_servers_item_locations_item_t**)out->elts)[i], buf, flags);
            cur = buf->data + buf->len;
            cur = njt_sprintf(cur, ",");
            buf->len ++;
        }
    }
    cur--;
    if (cur[0] == ',') {
        buf->len --;
    } else {
        cur ++;
    }
    cur = njt_sprintf(cur,  "]");
    buf->len ++;
}

static void to_oneline_json_dynbwlist_servers_item(njt_pool_t *pool, dynbwlist_servers_item_t *out, njt_str_t* buf, njt_int_t flags) {
    njt_int_t omit;
    u_char* cur = buf->data + buf->len;
    if (out == NULL) {
        cur = njt_sprintf(cur, "null");
        buf->len += 4;
        return;
    }
    cur = njt_sprintf(cur, "{");
    buf->len ++;
    omit = 0;
    omit = out->is_listens_set ? 0 : 1;
    omit = (flags & OMIT_NULL_ARRAY) && (out->listens) == NULL ? 1 : omit;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"listens\":");
        buf->len = cur - buf->data;
        to_oneline_json_dynbwlist_servers_item_listens(pool, (out->listens), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    omit = 0;
    omit = out->is_serverNames_set ? 0 : 1;
    omit = (flags & OMIT_NULL_ARRAY) && (out->serverNames) == NULL ? 1 : omit;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"serverNames\":");
        buf->len = cur - buf->data;
        to_oneline_json_dynbwlist_servers_item_serverNames(pool, (out->serverNames), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    omit = 0;
    omit = out->is_locations_set ? 0 : 1;
    omit = (flags & OMIT_NULL_ARRAY) && (out->locations) == NULL ? 1 : omit;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"locations\":");
        buf->len = cur - buf->data;
        to_oneline_json_dynbwlist_servers_item_locations(pool, (out->locations), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    cur--;
    if (cur[0] == ',') {
        buf->len --;
    } else {
        cur ++;
    }
    cur = njt_sprintf(cur, "}");
    buf->len ++;
}

static void to_oneline_json_dynbwlist_servers(njt_pool_t *pool, dynbwlist_servers_t *out, njt_str_t* buf, njt_int_t flags) {
    njt_int_t omit;
    u_char *cur = buf->data + buf->len;
    njt_uint_t i;
    if (out == NULL || out->nelts == 0) {
        cur = njt_sprintf(cur, "[]");
        buf->len += 2;
        return;
    }
    cur = njt_sprintf(cur,  "[");
    buf->len ++;
    for (i = 0; i < out->nelts; ++i) {
        omit = 0;
        omit = ((flags & OMIT_NULL_OBJ) && ((dynbwlist_servers_item_t**)out->elts)[i] == NULL) ? 1 : 0;
        if (omit == 0) {
            to_oneline_json_dynbwlist_servers_item(pool, ((dynbwlist_servers_item_t**)out->elts)[i], buf, flags);
            cur = buf->data + buf->len;
            cur = njt_sprintf(cur, ",");
            buf->len ++;
        }
    }
    cur--;
    if (cur[0] == ',') {
        buf->len --;
    } else {
        cur ++;
    }
    cur = njt_sprintf(cur,  "]");
    buf->len ++;
}

static void to_oneline_json_dynbwlist(njt_pool_t *pool, dynbwlist_t *out, njt_str_t* buf, njt_int_t flags) {
    njt_int_t omit;
    u_char* cur = buf->data + buf->len;
    if (out == NULL) {
        cur = njt_sprintf(cur, "null");
        buf->len += 4;
        return;
    }
    cur = njt_sprintf(cur, "{");
    buf->len ++;
    omit = 0;
    omit = out->is_servers_set ? 0 : 1;
    omit = (flags & OMIT_NULL_ARRAY) && (out->servers) == NULL ? 1 : omit;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"servers\":");
        buf->len = cur - buf->data;
        to_oneline_json_dynbwlist_servers(pool, (out->servers), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    cur--;
    if (cur[0] == ',') {
        buf->len --;
    } else {
        cur ++;
    }
    cur = njt_sprintf(cur, "}");
    buf->len ++;
}
dynbwlist_t* json_parse_dynbwlist(njt_pool_t *pool, const njt_str_t *json_string, js2c_parse_error_t *err_ret) {
    dynbwlist_t* out;
    parse_state_t parse_state_var;
    parse_state_t *parse_state = &parse_state_var;
    uint64_t max_token_number = 1024;
    jsmntok_t *token_buffer;
    int parse_result;
    for ( ; /* parse unsuccessful */; ) {
        token_buffer = njt_pcalloc(pool, sizeof(jsmntok_t)*max_token_number);
        parse_result = builtin_parse_json_string(pool, parse_state, token_buffer, max_token_number, (char *)json_string->data, json_string->len, err_ret);
        if (parse_result == JSMN_ERROR_INVAL) {
            LOG_ERROR_JSON_PARSE(INVALID_JSON_CHAR_ERR, "", -1, "%s", "Invalid character inside JSON string");
            return NULL;
        }
        if (parse_result == JSMN_ERROR_PART) {
            LOG_ERROR_JSON_PARSE(PARTIAL_JSON_ERR, "", -1, "%s", "The string is not a full JSON packet, more bytes expected");
            return NULL;
        }
        if (parse_result == JSMN_ERROR_NOMEM) {
            max_token_number += max_token_number;
            continue;
        }
        if (parse_result == 0) {
            LOG_ERROR_JSON_PARSE(NULL_JSON_ERR, "", 0, "String did not contain %s JSON tokens", "any");
            return NULL;
        }
        break; // parse success
    }
    out = njt_pcalloc(pool, sizeof(dynbwlist_t));;
    memset(out, 0, sizeof(dynbwlist_t));
    if (parse_dynbwlist(pool, parse_state, out, err_ret)) {
        return NULL;
    }
    return out;
}

njt_str_t* to_json_dynbwlist(njt_pool_t *pool, dynbwlist_t* out, njt_int_t flags) {
    njt_str_t *json_str;
    json_str = njt_pcalloc(pool, sizeof(njt_str_t));
    size_t str_len = 0;
    get_json_length_dynbwlist(pool, out, &str_len, flags);
    json_str->data = (u_char*)njt_pcalloc(pool, str_len + 1);
    json_str->len = 0;
    to_oneline_json_dynbwlist(pool, out, json_str, flags);
    return json_str;
}
