

/* This file was generated by JSON Schema to C.
 * Any changes made to it will be lost on regeneration. 

 * Copyright (C) 2021-2023  TMLake(Beijing) Technology Co., Ltd.
 */

#include "njt_http_dyn_upstream_parser.h"
#include "njt_core.h"
#include "js2c_njet_builtins.h"
/* ========================== Generated parsers ========================== */

static bool parse_dyn_upstream_list_upstream(njt_pool_t *pool, parse_state_t *parse_state, dyn_upstream_list_upstream_t *out, js2c_parse_error_t *err_ret); //forward decl for public definition
static void get_json_length_dyn_upstream_list_upstream(njt_pool_t *pool, dyn_upstream_list_upstream_t *out, size_t *length, njt_int_t flags); //forward decl for public definition
static void to_oneline_json_dyn_upstream_list_upstream(njt_pool_t *pool, dyn_upstream_list_upstream_t *out, njt_str_t *buf, njt_int_t flags); //forward decl for public definition

static bool parse_dyn_upstream_list_upstream_zone(njt_pool_t *pool, parse_state_t *parse_state, dyn_upstream_list_upstream_zone_t *out, js2c_parse_error_t *err_ret) {
    njt_uint_t i;

    js2c_check_type(JSMN_OBJECT);
    const int object_start_token = parse_state->current_token;
    const uint64_t n = parse_state->tokens[parse_state->current_token].size;
    parse_state->current_token += 1;
    for (i = 0; i < n; ++i) {
        js2c_key_children_check_for_obj();
        if (current_string_is(parse_state, "name")) {
            js2c_check_field_set(out->is_name_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "name";
            int token_size =  CURRENT_STRING_LENGTH(parse_state) ;
            ((&out->name))->data = (u_char*)njt_pcalloc(pool, (size_t)(token_size + 1));
            js2c_malloc_check(((&out->name))->data);
            ((&out->name))->len = token_size;
            if (builtin_parse_string(pool, parse_state, (&out->name), 0, ((&out->name))->len, err_ret)) {
                return true;
            }
            out->is_name_set = 1;
            parse_state->current_key = saved_key;
        } else if (current_string_is(parse_state, "size")) {
            js2c_check_field_set(out->is_size_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "size";
            int64_t int_parse_tmp;
            if (builtin_parse_signed(pool, parse_state, true, false, 10, &int_parse_tmp, err_ret)) {
                return true;
            }
            js2c_int_range_check_min(0LL);
            *(&out->size) = int_parse_tmp;
            out->is_size_set = 1;
            parse_state->current_key = saved_key;
        } else {
            LOG_ERROR_JSON_PARSE(UNKNOWN_FIELD_ERR, parse_state->current_key, CURRENT_TOKEN(parse_state).start, "Unknown field in '%s': %.*s", parse_state->current_key, CURRENT_STRING_FOR_ERROR(parse_state));
            return true;
        }
    }
    const int saved_current_token = parse_state->current_token;
    parse_state->current_token = object_start_token;
    parse_state->current_token = saved_current_token;
    return false;
}


static bool parse_dyn_upstream_list_upstream(njt_pool_t *pool, parse_state_t *parse_state, dyn_upstream_list_upstream_t *out, js2c_parse_error_t *err_ret) {
    njt_uint_t i;

    js2c_check_type(JSMN_OBJECT);
    const int object_start_token = parse_state->current_token;
    const uint64_t n = parse_state->tokens[parse_state->current_token].size;
    parse_state->current_token += 1;
    for (i = 0; i < n; ++i) {
        js2c_key_children_check_for_obj();
        if (current_string_is(parse_state, "name")) {
            js2c_check_field_set(out->is_name_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "name";
            int token_size =  CURRENT_STRING_LENGTH(parse_state) ;
            ((&out->name))->data = (u_char*)njt_pcalloc(pool, (size_t)(token_size + 1));
            js2c_malloc_check(((&out->name))->data);
            ((&out->name))->len = token_size;
            if (builtin_parse_string(pool, parse_state, (&out->name), 0, ((&out->name))->len, err_ret)) {
                return true;
            }
            out->is_name_set = 1;
            parse_state->current_key = saved_key;
        } else if (current_string_is(parse_state, "type")) {
            js2c_check_field_set(out->is_type_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "type";
            js2c_null_check();
            int token_size =  CURRENT_STRING_LENGTH(parse_state) ;
            ((&out->type))->data = (u_char*)njt_pcalloc(pool, (size_t)(token_size + 1));
            js2c_malloc_check(((&out->type))->data);
            ((&out->type))->len = token_size;
            if (builtin_parse_string(pool, parse_state, (&out->type), 0, ((&out->type))->len, err_ret)) {
                return true;
            }
            out->is_type_set = 1;
            parse_state->current_key = saved_key;
        } else if (current_string_is(parse_state, "balance")) {
            js2c_check_field_set(out->is_balance_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "balance";
            js2c_null_check();
            int token_size =  CURRENT_STRING_LENGTH(parse_state) ;
            ((&out->balance))->data = (u_char*)njt_pcalloc(pool, (size_t)(token_size + 1));
            js2c_malloc_check(((&out->balance))->data);
            ((&out->balance))->len = token_size;
            if (builtin_parse_string(pool, parse_state, (&out->balance), 0, ((&out->balance))->len, err_ret)) {
                return true;
            }
            out->is_balance_set = 1;
            parse_state->current_key = saved_key;
        } else if (current_string_is(parse_state, "zone")) {
            js2c_check_field_set(out->is_zone_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "zone";
            js2c_null_check();
            out->zone = njt_pcalloc(pool, sizeof(dyn_upstream_list_upstream_zone_t));
            js2c_malloc_check(out->zone);
            memset(out->zone, 0, sizeof(dyn_upstream_list_upstream_zone_t));

            if (parse_dyn_upstream_list_upstream_zone(pool, parse_state, (out->zone), err_ret)) {
                return true;
            }
            out->is_zone_set = 1;
            parse_state->current_key = saved_key;
        } else if (current_string_is(parse_state, "state")) {
            js2c_check_field_set(out->is_state_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "state";
            js2c_null_check();
            int token_size =  CURRENT_STRING_LENGTH(parse_state) ;
            ((&out->state))->data = (u_char*)njt_pcalloc(pool, (size_t)(token_size + 1));
            js2c_malloc_check(((&out->state))->data);
            ((&out->state))->len = token_size;
            if (builtin_parse_string(pool, parse_state, (&out->state), 0, ((&out->state))->len, err_ret)) {
                return true;
            }
            out->is_state_set = 1;
            parse_state->current_key = saved_key;
        } else if (current_string_is(parse_state, "keepalive")) {
            js2c_check_field_set(out->is_keepalive_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "keepalive";
            js2c_null_check();
            int64_t int_parse_tmp;
            if (builtin_parse_signed(pool, parse_state, true, false, 10, &int_parse_tmp, err_ret)) {
                return true;
            }
            js2c_int_range_check_min(0LL);
            *(&out->keepalive) = int_parse_tmp;
            out->is_keepalive_set = 1;
            parse_state->current_key = saved_key;
        } else if (current_string_is(parse_state, "keepalive_requests")) {
            js2c_check_field_set(out->is_keepalive_requests_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "keepalive_requests";
            js2c_null_check();
            int64_t int_parse_tmp;
            if (builtin_parse_signed(pool, parse_state, true, false, 10, &int_parse_tmp, err_ret)) {
                return true;
            }
            js2c_int_range_check_min(0LL);
            *(&out->keepalive_requests) = int_parse_tmp;
            out->is_keepalive_requests_set = 1;
            parse_state->current_key = saved_key;
        } else if (current_string_is(parse_state, "keepalive_timeout")) {
            js2c_check_field_set(out->is_keepalive_timeout_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "keepalive_timeout";
            js2c_null_check();
            int64_t int_parse_tmp;
            if (builtin_parse_signed(pool, parse_state, true, false, 10, &int_parse_tmp, err_ret)) {
                return true;
            }
            js2c_int_range_check_min(0LL);
            *(&out->keepalive_timeout) = int_parse_tmp;
            out->is_keepalive_timeout_set = 1;
            parse_state->current_key = saved_key;
        } else if (current_string_is(parse_state, "keepalive_time")) {
            js2c_check_field_set(out->is_keepalive_time_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "keepalive_time";
            js2c_null_check();
            int64_t int_parse_tmp;
            if (builtin_parse_signed(pool, parse_state, true, false, 10, &int_parse_tmp, err_ret)) {
                return true;
            }
            js2c_int_range_check_min(0LL);
            *(&out->keepalive_time) = int_parse_tmp;
            out->is_keepalive_time_set = 1;
            parse_state->current_key = saved_key;
        } else if (current_string_is(parse_state, "resolver_timeout")) {
            js2c_check_field_set(out->is_resolver_timeout_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "resolver_timeout";
            js2c_null_check();
            int64_t int_parse_tmp;
            if (builtin_parse_signed(pool, parse_state, true, false, 10, &int_parse_tmp, err_ret)) {
                return true;
            }
            js2c_int_range_check_min(0LL);
            *(&out->resolver_timeout) = int_parse_tmp;
            out->is_resolver_timeout_set = 1;
            parse_state->current_key = saved_key;
        } else if (current_string_is(parse_state, "resolver")) {
            js2c_check_field_set(out->is_resolver_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "resolver";
            js2c_null_check();
            int token_size =  CURRENT_STRING_LENGTH(parse_state) ;
            ((&out->resolver))->data = (u_char*)njt_pcalloc(pool, (size_t)(token_size + 1));
            js2c_malloc_check(((&out->resolver))->data);
            ((&out->resolver))->len = token_size;
            if (builtin_parse_string(pool, parse_state, (&out->resolver), 0, ((&out->resolver))->len, err_ret)) {
                return true;
            }
            out->is_resolver_set = 1;
            parse_state->current_key = saved_key;
        } else if (current_string_is(parse_state, "is_static")) {
            js2c_check_field_set(out->is_is_static_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "is_static";
            js2c_null_check();
            if (builtin_parse_bool(pool, parse_state, (&out->is_static), err_ret)) {
                return true;
            }
            out->is_is_static_set = 1;
            parse_state->current_key = saved_key;
        } else {
            LOG_ERROR_JSON_PARSE(UNKNOWN_FIELD_ERR, parse_state->current_key, CURRENT_TOKEN(parse_state).start, "Unknown field in '%s': %.*s", parse_state->current_key, CURRENT_STRING_FOR_ERROR(parse_state));
            return true;
        }
    }
    const int saved_current_token = parse_state->current_token;
    parse_state->current_token = object_start_token;
    // set default
    if (!out->is_type_set) {
        size_t token_size = strlen("");
        (out->type).data = (u_char*)njt_pcalloc(pool, token_size + 1);
        js2c_malloc_check((out->type).data);
        (out->type).len = token_size;
        if (out->type.len == 0) {
            (out->type).data[0] = 0;
        }
        if (token_size > 0) {
            njt_memcpy(out->type.data, "", token_size);
        }
    }
    // set default
    if (!out->is_balance_set) {
        size_t token_size = strlen("");
        (out->balance).data = (u_char*)njt_pcalloc(pool, token_size + 1);
        js2c_malloc_check((out->balance).data);
        (out->balance).len = token_size;
        if (out->balance.len == 0) {
            (out->balance).data[0] = 0;
        }
        if (token_size > 0) {
            njt_memcpy(out->balance.data, "", token_size);
        }
    }
    // set default
    if (!out->is_zone_set) {
        out->zone = NULL;
    }
    // set default
    if (!out->is_state_set) {
        size_t token_size = strlen("");
        (out->state).data = (u_char*)njt_pcalloc(pool, token_size + 1);
        js2c_malloc_check((out->state).data);
        (out->state).len = token_size;
        if (out->state.len == 0) {
            (out->state).data[0] = 0;
        }
        if (token_size > 0) {
            njt_memcpy(out->state.data, "", token_size);
        }
    }
    // set default
    if (!out->is_keepalive_set) {
        out->keepalive = 0LL;
    }
    // set default
    if (!out->is_keepalive_requests_set) {
        out->keepalive_requests = 0LL;
    }
    // set default
    if (!out->is_keepalive_timeout_set) {
        out->keepalive_timeout = 0LL;
    }
    // set default
    if (!out->is_keepalive_time_set) {
        out->keepalive_time = 0LL;
    }
    // set default
    if (!out->is_resolver_timeout_set) {
        out->resolver_timeout = 0LL;
    }
    // set default
    if (!out->is_resolver_set) {
        size_t token_size = strlen("");
        (out->resolver).data = (u_char*)njt_pcalloc(pool, token_size + 1);
        js2c_malloc_check((out->resolver).data);
        (out->resolver).len = token_size;
        if (out->resolver.len == 0) {
            (out->resolver).data[0] = 0;
        }
        if (token_size > 0) {
            njt_memcpy(out->resolver.data, "", token_size);
        }
    }
    // set default
    if (!out->is_is_static_set) {
        out->is_static = true;
    }
    parse_state->current_token = saved_current_token;
    return false;
}


static void get_json_length_dyn_upstream_list_upstream_name(njt_pool_t *pool, dyn_upstream_list_upstream_name_t *out, size_t *length, njt_int_t flags) {
    njt_str_t *dst = handle_escape_on_write(pool, out);
    *length += dst->len + 2; //  "str" 
}

static void get_json_length_dyn_upstream_list_upstream_type(njt_pool_t *pool, dyn_upstream_list_upstream_type_t *out, size_t *length, njt_int_t flags) {
    njt_str_t *dst = handle_escape_on_write(pool, out);
    *length += dst->len + 2; //  "str" 
}

static void get_json_length_dyn_upstream_list_upstream_balance(njt_pool_t *pool, dyn_upstream_list_upstream_balance_t *out, size_t *length, njt_int_t flags) {
    njt_str_t *dst = handle_escape_on_write(pool, out);
    *length += dst->len + 2; //  "str" 
}

static void get_json_length_dyn_upstream_list_upstream_zone_name(njt_pool_t *pool, dyn_upstream_list_upstream_zone_name_t *out, size_t *length, njt_int_t flags) {
    njt_str_t *dst = handle_escape_on_write(pool, out);
    *length += dst->len + 2; //  "str" 
}

static void get_json_length_dyn_upstream_list_upstream_zone_size(njt_pool_t *pool, dyn_upstream_list_upstream_zone_size_t *out, size_t *length, njt_int_t flags) {
    u_char str[24];
    u_char *cur;
    cur = njt_sprintf(str, "%L", *out);
    *length += cur - str;
}

static void get_json_length_dyn_upstream_list_upstream_zone(njt_pool_t *pool, dyn_upstream_list_upstream_zone_t *out, size_t *length, njt_int_t flags) {
    if (out == NULL) {
        *length += 4; // null
        return;
    }
    *length += 1;
    njt_int_t omit;
    njt_int_t count = 0;
    omit = 0;
    omit = out->is_name_set ? 0 : 1;
    omit = (flags & OMIT_NULL_STR) && (out->name.data) == NULL ? 1 : omit;
    if (omit == 0) {
        *length += (4 + 3); // "name": 
        get_json_length_dyn_upstream_list_upstream_zone_name(pool, (&out->name), length, flags);
        *length += 1; // ","
        count++;
    }
    omit = 0;
    omit = out->is_size_set ? 0 : 1;
    if (omit == 0) {
        *length += (4 + 3); // "size": 
        get_json_length_dyn_upstream_list_upstream_zone_size(pool, (&out->size), length, flags);
        *length += 1; // ","
        count++;
    }
    if (count != 0) {
        *length -= 1; // "\b"
    }
    *length += 1;
}

static void get_json_length_dyn_upstream_list_upstream_state(njt_pool_t *pool, dyn_upstream_list_upstream_state_t *out, size_t *length, njt_int_t flags) {
    njt_str_t *dst = handle_escape_on_write(pool, out);
    *length += dst->len + 2; //  "str" 
}

static void get_json_length_dyn_upstream_list_upstream_keepalive(njt_pool_t *pool, dyn_upstream_list_upstream_keepalive_t *out, size_t *length, njt_int_t flags) {
    u_char str[24];
    u_char *cur;
    cur = njt_sprintf(str, "%L", *out);
    *length += cur - str;
}

static void get_json_length_dyn_upstream_list_upstream_keepalive_requests(njt_pool_t *pool, dyn_upstream_list_upstream_keepalive_requests_t *out, size_t *length, njt_int_t flags) {
    u_char str[24];
    u_char *cur;
    cur = njt_sprintf(str, "%L", *out);
    *length += cur - str;
}

static void get_json_length_dyn_upstream_list_upstream_keepalive_timeout(njt_pool_t *pool, dyn_upstream_list_upstream_keepalive_timeout_t *out, size_t *length, njt_int_t flags) {
    u_char str[24];
    u_char *cur;
    cur = njt_sprintf(str, "%L", *out);
    *length += cur - str;
}

static void get_json_length_dyn_upstream_list_upstream_keepalive_time(njt_pool_t *pool, dyn_upstream_list_upstream_keepalive_time_t *out, size_t *length, njt_int_t flags) {
    u_char str[24];
    u_char *cur;
    cur = njt_sprintf(str, "%L", *out);
    *length += cur - str;
}

static void get_json_length_dyn_upstream_list_upstream_resolver_timeout(njt_pool_t *pool, dyn_upstream_list_upstream_resolver_timeout_t *out, size_t *length, njt_int_t flags) {
    u_char str[24];
    u_char *cur;
    cur = njt_sprintf(str, "%L", *out);
    *length += cur - str;
}

static void get_json_length_dyn_upstream_list_upstream_resolver(njt_pool_t *pool, dyn_upstream_list_upstream_resolver_t *out, size_t *length, njt_int_t flags) {
    njt_str_t *dst = handle_escape_on_write(pool, out);
    *length += dst->len + 2; //  "str" 
}

static void get_json_length_dyn_upstream_list_upstream_is_static(njt_pool_t *pool, dyn_upstream_list_upstream_is_static_t *out, size_t *length, njt_int_t flags) {
    if (*out) {
        *length += 4; // "true"
    } else {
        *length += 5; // "false"
    }
}

static void get_json_length_dyn_upstream_list_upstream(njt_pool_t *pool, dyn_upstream_list_upstream_t *out, size_t *length, njt_int_t flags) {
    if (out == NULL) {
        *length += 4; // null
        return;
    }
    *length += 1;
    njt_int_t omit;
    njt_int_t count = 0;
    omit = 0;
    omit = out->is_name_set ? 0 : 1;
    omit = (flags & OMIT_NULL_STR) && (out->name.data) == NULL ? 1 : omit;
    if (omit == 0) {
        *length += (4 + 3); // "name": 
        get_json_length_dyn_upstream_list_upstream_name(pool, (&out->name), length, flags);
        *length += 1; // ","
        count++;
    }
    omit = 0;
    omit = out->is_type_set ? 0 : 1;
    omit = (flags & OMIT_NULL_STR) && (out->type.data) == NULL ? 1 : omit;
    if (omit == 0) {
        *length += (4 + 3); // "type": 
        get_json_length_dyn_upstream_list_upstream_type(pool, (&out->type), length, flags);
        *length += 1; // ","
        count++;
    }
    omit = 0;
    omit = out->is_balance_set ? 0 : 1;
    omit = (flags & OMIT_NULL_STR) && (out->balance.data) == NULL ? 1 : omit;
    if (omit == 0) {
        *length += (7 + 3); // "balance": 
        get_json_length_dyn_upstream_list_upstream_balance(pool, (&out->balance), length, flags);
        *length += 1; // ","
        count++;
    }
    omit = 0;
    omit = out->is_zone_set ? 0 : 1;
    omit = (flags & OMIT_NULL_OBJ) && (out->zone) == NULL ? 1 : omit;
    if (omit == 0) {
        *length += (4 + 3); // "zone": 
        get_json_length_dyn_upstream_list_upstream_zone(pool, (out->zone), length, flags);
        *length += 1; // ","
        count++;
    }
    omit = 0;
    omit = out->is_state_set ? 0 : 1;
    omit = (flags & OMIT_NULL_STR) && (out->state.data) == NULL ? 1 : omit;
    if (omit == 0) {
        *length += (5 + 3); // "state": 
        get_json_length_dyn_upstream_list_upstream_state(pool, (&out->state), length, flags);
        *length += 1; // ","
        count++;
    }
    omit = 0;
    omit = out->is_keepalive_set ? 0 : 1;
    if (omit == 0) {
        *length += (9 + 3); // "keepalive": 
        get_json_length_dyn_upstream_list_upstream_keepalive(pool, (&out->keepalive), length, flags);
        *length += 1; // ","
        count++;
    }
    omit = 0;
    omit = out->is_keepalive_requests_set ? 0 : 1;
    if (omit == 0) {
        *length += (18 + 3); // "keepalive_requests": 
        get_json_length_dyn_upstream_list_upstream_keepalive_requests(pool, (&out->keepalive_requests), length, flags);
        *length += 1; // ","
        count++;
    }
    omit = 0;
    omit = out->is_keepalive_timeout_set ? 0 : 1;
    if (omit == 0) {
        *length += (17 + 3); // "keepalive_timeout": 
        get_json_length_dyn_upstream_list_upstream_keepalive_timeout(pool, (&out->keepalive_timeout), length, flags);
        *length += 1; // ","
        count++;
    }
    omit = 0;
    omit = out->is_keepalive_time_set ? 0 : 1;
    if (omit == 0) {
        *length += (14 + 3); // "keepalive_time": 
        get_json_length_dyn_upstream_list_upstream_keepalive_time(pool, (&out->keepalive_time), length, flags);
        *length += 1; // ","
        count++;
    }
    omit = 0;
    omit = out->is_resolver_timeout_set ? 0 : 1;
    if (omit == 0) {
        *length += (16 + 3); // "resolver_timeout": 
        get_json_length_dyn_upstream_list_upstream_resolver_timeout(pool, (&out->resolver_timeout), length, flags);
        *length += 1; // ","
        count++;
    }
    omit = 0;
    omit = out->is_resolver_set ? 0 : 1;
    omit = (flags & OMIT_NULL_STR) && (out->resolver.data) == NULL ? 1 : omit;
    if (omit == 0) {
        *length += (8 + 3); // "resolver": 
        get_json_length_dyn_upstream_list_upstream_resolver(pool, (&out->resolver), length, flags);
        *length += 1; // ","
        count++;
    }
    omit = 0;
    omit = out->is_is_static_set ? 0 : 1;
    if (omit == 0) {
        *length += (9 + 3); // "is_static": 
        get_json_length_dyn_upstream_list_upstream_is_static(pool, (&out->is_static), length, flags);
        *length += 1; // ","
        count++;
    }
    if (count != 0) {
        *length -= 1; // "\b"
    }
    *length += 1;
}

dyn_upstream_list_upstream_zone_name_t* get_dyn_upstream_list_upstream_zone_name(dyn_upstream_list_upstream_zone_t *out) {
    return &out->name;
}

dyn_upstream_list_upstream_zone_size_t get_dyn_upstream_list_upstream_zone_size(dyn_upstream_list_upstream_zone_t *out) {
    return out->size;
}

dyn_upstream_list_upstream_name_t* get_dyn_upstream_list_upstream_name(dyn_upstream_list_upstream_t *out) {
    return &out->name;
}

dyn_upstream_list_upstream_type_t* get_dyn_upstream_list_upstream_type(dyn_upstream_list_upstream_t *out) {
    return &out->type;
}

dyn_upstream_list_upstream_balance_t* get_dyn_upstream_list_upstream_balance(dyn_upstream_list_upstream_t *out) {
    return &out->balance;
}

dyn_upstream_list_upstream_zone_t* get_dyn_upstream_list_upstream_zone(dyn_upstream_list_upstream_t *out) {
    return out->zone;
}

dyn_upstream_list_upstream_state_t* get_dyn_upstream_list_upstream_state(dyn_upstream_list_upstream_t *out) {
    return &out->state;
}

dyn_upstream_list_upstream_keepalive_t get_dyn_upstream_list_upstream_keepalive(dyn_upstream_list_upstream_t *out) {
    return out->keepalive;
}

dyn_upstream_list_upstream_keepalive_requests_t get_dyn_upstream_list_upstream_keepalive_requests(dyn_upstream_list_upstream_t *out) {
    return out->keepalive_requests;
}

dyn_upstream_list_upstream_keepalive_timeout_t get_dyn_upstream_list_upstream_keepalive_timeout(dyn_upstream_list_upstream_t *out) {
    return out->keepalive_timeout;
}

dyn_upstream_list_upstream_keepalive_time_t get_dyn_upstream_list_upstream_keepalive_time(dyn_upstream_list_upstream_t *out) {
    return out->keepalive_time;
}

dyn_upstream_list_upstream_resolver_timeout_t get_dyn_upstream_list_upstream_resolver_timeout(dyn_upstream_list_upstream_t *out) {
    return out->resolver_timeout;
}

dyn_upstream_list_upstream_resolver_t* get_dyn_upstream_list_upstream_resolver(dyn_upstream_list_upstream_t *out) {
    return &out->resolver;
}

dyn_upstream_list_upstream_is_static_t get_dyn_upstream_list_upstream_is_static(dyn_upstream_list_upstream_t *out) {
    return out->is_static;
}
void set_dyn_upstream_list_upstream_name(dyn_upstream_list_upstream_t* obj, dyn_upstream_list_upstream_name_t* field) {
    njt_memcpy(&obj->name, field, sizeof(njt_str_t));
    obj->is_name_set = 1;
}
void set_dyn_upstream_list_upstream_type(dyn_upstream_list_upstream_t* obj, dyn_upstream_list_upstream_type_t* field) {
    njt_memcpy(&obj->type, field, sizeof(njt_str_t));
    obj->is_type_set = 1;
}
void set_dyn_upstream_list_upstream_balance(dyn_upstream_list_upstream_t* obj, dyn_upstream_list_upstream_balance_t* field) {
    njt_memcpy(&obj->balance, field, sizeof(njt_str_t));
    obj->is_balance_set = 1;
}
void set_dyn_upstream_list_upstream_zone_name(dyn_upstream_list_upstream_zone_t* obj, dyn_upstream_list_upstream_zone_name_t* field) {
    njt_memcpy(&obj->name, field, sizeof(njt_str_t));
    obj->is_name_set = 1;
}
void set_dyn_upstream_list_upstream_zone_size(dyn_upstream_list_upstream_zone_t* obj, dyn_upstream_list_upstream_zone_size_t field) {
    obj->size = field;
    obj->is_size_set = 1;
}
dyn_upstream_list_upstream_zone_t* create_dyn_upstream_list_upstream_zone(njt_pool_t *pool) {
    dyn_upstream_list_upstream_zone_t* out = njt_pcalloc(pool, sizeof(dyn_upstream_list_upstream_zone_t));
    return out;
}
void set_dyn_upstream_list_upstream_zone(dyn_upstream_list_upstream_t* obj, dyn_upstream_list_upstream_zone_t* field) {
    obj->zone = field;
    obj->is_zone_set = 1;
}
void set_dyn_upstream_list_upstream_state(dyn_upstream_list_upstream_t* obj, dyn_upstream_list_upstream_state_t* field) {
    njt_memcpy(&obj->state, field, sizeof(njt_str_t));
    obj->is_state_set = 1;
}
void set_dyn_upstream_list_upstream_keepalive(dyn_upstream_list_upstream_t* obj, dyn_upstream_list_upstream_keepalive_t field) {
    obj->keepalive = field;
    obj->is_keepalive_set = 1;
}
void set_dyn_upstream_list_upstream_keepalive_requests(dyn_upstream_list_upstream_t* obj, dyn_upstream_list_upstream_keepalive_requests_t field) {
    obj->keepalive_requests = field;
    obj->is_keepalive_requests_set = 1;
}
void set_dyn_upstream_list_upstream_keepalive_timeout(dyn_upstream_list_upstream_t* obj, dyn_upstream_list_upstream_keepalive_timeout_t field) {
    obj->keepalive_timeout = field;
    obj->is_keepalive_timeout_set = 1;
}
void set_dyn_upstream_list_upstream_keepalive_time(dyn_upstream_list_upstream_t* obj, dyn_upstream_list_upstream_keepalive_time_t field) {
    obj->keepalive_time = field;
    obj->is_keepalive_time_set = 1;
}
void set_dyn_upstream_list_upstream_resolver_timeout(dyn_upstream_list_upstream_t* obj, dyn_upstream_list_upstream_resolver_timeout_t field) {
    obj->resolver_timeout = field;
    obj->is_resolver_timeout_set = 1;
}
void set_dyn_upstream_list_upstream_resolver(dyn_upstream_list_upstream_t* obj, dyn_upstream_list_upstream_resolver_t* field) {
    njt_memcpy(&obj->resolver, field, sizeof(njt_str_t));
    obj->is_resolver_set = 1;
}
void set_dyn_upstream_list_upstream_is_static(dyn_upstream_list_upstream_t* obj, dyn_upstream_list_upstream_is_static_t field) {
    obj->is_static = field;
    obj->is_is_static_set = 1;
}
dyn_upstream_list_upstream_t* create_dyn_upstream_list_upstream(njt_pool_t *pool) {
    dyn_upstream_list_upstream_t* out = njt_pcalloc(pool, sizeof(dyn_upstream_list_upstream_t));
    return out;
}

static void to_oneline_json_dyn_upstream_list_upstream_name(njt_pool_t *pool, dyn_upstream_list_upstream_name_t *out, njt_str_t *buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    njt_str_t *dst = handle_escape_on_write(pool, out);
    cur = njt_sprintf(cur, "\"%V\"", dst);
    buf->len = cur - buf->data;
}

static void to_oneline_json_dyn_upstream_list_upstream_type(njt_pool_t *pool, dyn_upstream_list_upstream_type_t *out, njt_str_t *buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    njt_str_t *dst = handle_escape_on_write(pool, out);
    cur = njt_sprintf(cur, "\"%V\"", dst);
    buf->len = cur - buf->data;
}

static void to_oneline_json_dyn_upstream_list_upstream_balance(njt_pool_t *pool, dyn_upstream_list_upstream_balance_t *out, njt_str_t *buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    njt_str_t *dst = handle_escape_on_write(pool, out);
    cur = njt_sprintf(cur, "\"%V\"", dst);
    buf->len = cur - buf->data;
}

static void to_oneline_json_dyn_upstream_list_upstream_zone_name(njt_pool_t *pool, dyn_upstream_list_upstream_zone_name_t *out, njt_str_t *buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    njt_str_t *dst = handle_escape_on_write(pool, out);
    cur = njt_sprintf(cur, "\"%V\"", dst);
    buf->len = cur - buf->data;
}

static void to_oneline_json_dyn_upstream_list_upstream_zone_size(njt_pool_t *pool, dyn_upstream_list_upstream_zone_size_t *out, njt_str_t* buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    cur = njt_sprintf(cur, "%L", *out);
    buf->len = cur - buf->data;
}

static void to_oneline_json_dyn_upstream_list_upstream_zone(njt_pool_t *pool, dyn_upstream_list_upstream_zone_t *out, njt_str_t* buf, njt_int_t flags) {
    njt_int_t omit;
    u_char* cur = buf->data + buf->len;
    if (out == NULL) {
        cur = njt_sprintf(cur, "null");
        buf->len += 4;
        return;
    }
    cur = njt_sprintf(cur, "{");
    buf->len ++;
    omit = 0;
    omit = out->is_name_set ? 0 : 1;
    omit = (flags & OMIT_NULL_STR) && (out->name.data) == NULL ? 1 : omit;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"name\":");
        buf->len = cur - buf->data;
        to_oneline_json_dyn_upstream_list_upstream_zone_name(pool, (&out->name), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    omit = 0;
    omit = out->is_size_set ? 0 : 1;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"size\":");
        buf->len = cur - buf->data;
        to_oneline_json_dyn_upstream_list_upstream_zone_size(pool, (&out->size), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    cur--;
    if (cur[0] == ',') {
        buf->len --;
    } else {
        cur ++;
    }
    cur = njt_sprintf(cur, "}");
    buf->len ++;
}

static void to_oneline_json_dyn_upstream_list_upstream_state(njt_pool_t *pool, dyn_upstream_list_upstream_state_t *out, njt_str_t *buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    njt_str_t *dst = handle_escape_on_write(pool, out);
    cur = njt_sprintf(cur, "\"%V\"", dst);
    buf->len = cur - buf->data;
}

static void to_oneline_json_dyn_upstream_list_upstream_keepalive(njt_pool_t *pool, dyn_upstream_list_upstream_keepalive_t *out, njt_str_t* buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    cur = njt_sprintf(cur, "%L", *out);
    buf->len = cur - buf->data;
}

static void to_oneline_json_dyn_upstream_list_upstream_keepalive_requests(njt_pool_t *pool, dyn_upstream_list_upstream_keepalive_requests_t *out, njt_str_t* buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    cur = njt_sprintf(cur, "%L", *out);
    buf->len = cur - buf->data;
}

static void to_oneline_json_dyn_upstream_list_upstream_keepalive_timeout(njt_pool_t *pool, dyn_upstream_list_upstream_keepalive_timeout_t *out, njt_str_t* buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    cur = njt_sprintf(cur, "%L", *out);
    buf->len = cur - buf->data;
}

static void to_oneline_json_dyn_upstream_list_upstream_keepalive_time(njt_pool_t *pool, dyn_upstream_list_upstream_keepalive_time_t *out, njt_str_t* buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    cur = njt_sprintf(cur, "%L", *out);
    buf->len = cur - buf->data;
}

static void to_oneline_json_dyn_upstream_list_upstream_resolver_timeout(njt_pool_t *pool, dyn_upstream_list_upstream_resolver_timeout_t *out, njt_str_t* buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    cur = njt_sprintf(cur, "%L", *out);
    buf->len = cur - buf->data;
}

static void to_oneline_json_dyn_upstream_list_upstream_resolver(njt_pool_t *pool, dyn_upstream_list_upstream_resolver_t *out, njt_str_t *buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    njt_str_t *dst = handle_escape_on_write(pool, out);
    cur = njt_sprintf(cur, "\"%V\"", dst);
    buf->len = cur - buf->data;
}

static void to_oneline_json_dyn_upstream_list_upstream_is_static(njt_pool_t *pool, dyn_upstream_list_upstream_is_static_t *out, njt_str_t *buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    if (*out) {
        njt_sprintf(cur, "true");
        buf->len += 4;
    } else {
        njt_sprintf(cur, "false");
        buf->len += 5;
    }
}

static void to_oneline_json_dyn_upstream_list_upstream(njt_pool_t *pool, dyn_upstream_list_upstream_t *out, njt_str_t* buf, njt_int_t flags) {
    njt_int_t omit;
    u_char* cur = buf->data + buf->len;
    if (out == NULL) {
        cur = njt_sprintf(cur, "null");
        buf->len += 4;
        return;
    }
    cur = njt_sprintf(cur, "{");
    buf->len ++;
    omit = 0;
    omit = out->is_name_set ? 0 : 1;
    omit = (flags & OMIT_NULL_STR) && (out->name.data) == NULL ? 1 : omit;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"name\":");
        buf->len = cur - buf->data;
        to_oneline_json_dyn_upstream_list_upstream_name(pool, (&out->name), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    omit = 0;
    omit = out->is_type_set ? 0 : 1;
    omit = (flags & OMIT_NULL_STR) && (out->type.data) == NULL ? 1 : omit;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"type\":");
        buf->len = cur - buf->data;
        to_oneline_json_dyn_upstream_list_upstream_type(pool, (&out->type), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    omit = 0;
    omit = out->is_balance_set ? 0 : 1;
    omit = (flags & OMIT_NULL_STR) && (out->balance.data) == NULL ? 1 : omit;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"balance\":");
        buf->len = cur - buf->data;
        to_oneline_json_dyn_upstream_list_upstream_balance(pool, (&out->balance), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    omit = 0;
    omit = out->is_zone_set ? 0 : 1;
    omit = (flags & OMIT_NULL_OBJ) && (out->zone) == NULL ? 1 : omit;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"zone\":");
        buf->len = cur - buf->data;
        to_oneline_json_dyn_upstream_list_upstream_zone(pool, (out->zone), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    omit = 0;
    omit = out->is_state_set ? 0 : 1;
    omit = (flags & OMIT_NULL_STR) && (out->state.data) == NULL ? 1 : omit;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"state\":");
        buf->len = cur - buf->data;
        to_oneline_json_dyn_upstream_list_upstream_state(pool, (&out->state), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    omit = 0;
    omit = out->is_keepalive_set ? 0 : 1;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"keepalive\":");
        buf->len = cur - buf->data;
        to_oneline_json_dyn_upstream_list_upstream_keepalive(pool, (&out->keepalive), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    omit = 0;
    omit = out->is_keepalive_requests_set ? 0 : 1;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"keepalive_requests\":");
        buf->len = cur - buf->data;
        to_oneline_json_dyn_upstream_list_upstream_keepalive_requests(pool, (&out->keepalive_requests), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    omit = 0;
    omit = out->is_keepalive_timeout_set ? 0 : 1;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"keepalive_timeout\":");
        buf->len = cur - buf->data;
        to_oneline_json_dyn_upstream_list_upstream_keepalive_timeout(pool, (&out->keepalive_timeout), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    omit = 0;
    omit = out->is_keepalive_time_set ? 0 : 1;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"keepalive_time\":");
        buf->len = cur - buf->data;
        to_oneline_json_dyn_upstream_list_upstream_keepalive_time(pool, (&out->keepalive_time), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    omit = 0;
    omit = out->is_resolver_timeout_set ? 0 : 1;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"resolver_timeout\":");
        buf->len = cur - buf->data;
        to_oneline_json_dyn_upstream_list_upstream_resolver_timeout(pool, (&out->resolver_timeout), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    omit = 0;
    omit = out->is_resolver_set ? 0 : 1;
    omit = (flags & OMIT_NULL_STR) && (out->resolver.data) == NULL ? 1 : omit;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"resolver\":");
        buf->len = cur - buf->data;
        to_oneline_json_dyn_upstream_list_upstream_resolver(pool, (&out->resolver), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    omit = 0;
    omit = out->is_is_static_set ? 0 : 1;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"is_static\":");
        buf->len = cur - buf->data;
        to_oneline_json_dyn_upstream_list_upstream_is_static(pool, (&out->is_static), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    cur--;
    if (cur[0] == ',') {
        buf->len --;
    } else {
        cur ++;
    }
    cur = njt_sprintf(cur, "}");
    buf->len ++;
}

static bool parse_dyn_upstream_list(njt_pool_t *pool, parse_state_t *parse_state, dyn_upstream_list_t *out, js2c_parse_error_t *err_ret) {
    int i;
    js2c_check_type(JSMN_ARRAY);
    const int n = parse_state->tokens[parse_state->current_token].size;
    parse_state->current_token += 1;
    for (i = 0; i < n; ++i) {
        ((dyn_upstream_list_item_t**)out->elts)[i] = njt_pcalloc(pool, sizeof(dyn_upstream_list_upstream_t));
        memset(((dyn_upstream_list_item_t**)out->elts)[i], 0, sizeof(dyn_upstream_list_item_t));
        if (parse_dyn_upstream_list_upstream(pool, parse_state, ((dyn_upstream_list_item_t**)out->elts)[i], err_ret)) {
            return true;
        }
        out->nelts ++;
    }
    return false;
}


static void get_json_length_dyn_upstream_list_item(njt_pool_t *pool, dyn_upstream_list_item_t *out, size_t *length, njt_int_t flags) {
    get_json_length_dyn_upstream_list_upstream(pool, out, length, flags);
}

static void get_json_length_dyn_upstream_list(njt_pool_t *pool, dyn_upstream_list_t *out, size_t *length, njt_int_t flags) {
    njt_uint_t i;
    njt_uint_t omit;
    njt_int_t count = 0;
    if (out == NULL) {
        *length += 2; // "[]"
        return;
    }
    *length += 2; // "[]"
    for (i = 0; i < out->nelts; ++i) {
        omit = 0;
        omit = ((flags & OMIT_NULL_OBJ) && ((dyn_upstream_list_item_t**)out->elts)[i] == NULL) ? 1 : 0;
        if (omit == 0) {
            get_json_length_dyn_upstream_list_item(pool, ((dyn_upstream_list_item_t**)out->elts)[i], length, flags);
            *length += 1; // ","
            count++; // ","
        }
    }
    if (count != 0) {
        *length -= 1; // "\b"
    }
}
dyn_upstream_list_item_t* get_dyn_upstream_list_item(dyn_upstream_list_t *out, size_t idx) {
    return ((dyn_upstream_list_item_t**)out->elts)[idx];

}
int add_item_dyn_upstream_list(dyn_upstream_list_t *src, dyn_upstream_list_item_t* item) {
    void *new = njt_array_push(src);
    if (new == NULL) {
        return NJT_ERROR;
    }
    njt_memcpy(new, &item, src->size);
    return NJT_OK;
}

dyn_upstream_list_t* create_dyn_upstream_list(njt_pool_t *pool, size_t nelts) {
    return njt_array_create(pool, nelts, sizeof(dyn_upstream_list_item_t*));
}
// to_oneline_json_REF

static void to_oneline_json_dyn_upstream_list_item(njt_pool_t *pool, dyn_upstream_list_item_t *out, njt_str_t* buf, njt_int_t flags) {
    to_oneline_json_dyn_upstream_list_upstream(pool, out, buf, flags);
}

static void to_oneline_json_dyn_upstream_list(njt_pool_t *pool, dyn_upstream_list_t *out, njt_str_t* buf, njt_int_t flags) {
    njt_int_t omit;
    u_char *cur = buf->data + buf->len;
    njt_uint_t i;
    if (out == NULL || out->nelts == 0) {
        cur = njt_sprintf(cur, "[]");
        buf->len += 2;
        return;
    }
    cur = njt_sprintf(cur,  "[");
    buf->len ++;
    for (i = 0; i < out->nelts; ++i) {
        omit = 0;
        omit = ((flags & OMIT_NULL_OBJ) && ((dyn_upstream_list_item_t**)out->elts)[i] == NULL) ? 1 : 0;
        if (omit == 0) {
            to_oneline_json_dyn_upstream_list_item(pool, ((dyn_upstream_list_item_t**)out->elts)[i], buf, flags);
            cur = buf->data + buf->len;
            cur = njt_sprintf(cur, ",");
            buf->len ++;
        }
    }
    cur--;
    if (cur[0] == ',') {
        buf->len --;
    } else {
        cur ++;
    }
    cur = njt_sprintf(cur,  "]");
    buf->len ++;
}
dyn_upstream_list_t* json_parse_dyn_upstream_list(njt_pool_t *pool, const njt_str_t *json_string, js2c_parse_error_t *err_ret) {
    dyn_upstream_list_t* out;
    parse_state_t parse_state_var;
    parse_state_t *parse_state = &parse_state_var;
    uint64_t max_token_number = 1024;
    jsmntok_t *token_buffer;
    int parse_result;
    for ( ; /* parse unsuccessful */; ) {
        token_buffer = njt_pcalloc(pool, sizeof(jsmntok_t)*max_token_number);
        parse_result = builtin_parse_json_string(pool, parse_state, token_buffer, max_token_number, (char *)json_string->data, json_string->len, err_ret);
        if (parse_result == JSMN_ERROR_INVAL) {
            LOG_ERROR_JSON_PARSE(INVALID_JSON_CHAR_ERR, "", -1, "%s", "Invalid character inside JSON string");
            return NULL;
        }
        if (parse_result == JSMN_ERROR_PART) {
            LOG_ERROR_JSON_PARSE(PARTIAL_JSON_ERR, "", -1, "%s", "The string is not a full JSON packet, more bytes expected");
            return NULL;
        }
        if (parse_result == JSMN_ERROR_NOMEM) {
            max_token_number += max_token_number;
            continue;
        }
        if (parse_result == 0) {
            LOG_ERROR_JSON_PARSE(NULL_JSON_ERR, "", 0, "String did not contain %s JSON tokens", "any");
            return NULL;
        }
        break; // parse success
    }
    out = njt_array_create(pool, parse_state->tokens[parse_state->current_token].size ,sizeof(dyn_upstream_list_item_t*));;
    if (parse_dyn_upstream_list(pool, parse_state, out, err_ret)) {
        return NULL;
    }
    return out;
}

njt_str_t* to_json_dyn_upstream_list(njt_pool_t *pool, dyn_upstream_list_t* out, njt_int_t flags) {
    njt_str_t *json_str;
    json_str = njt_pcalloc(pool, sizeof(njt_str_t));
    size_t str_len = 0;
    get_json_length_dyn_upstream_list(pool, out, &str_len, flags);
    json_str->data = (u_char*)njt_pcalloc(pool, str_len + 1);
    json_str->len = 0;
    to_oneline_json_dyn_upstream_list(pool, out, json_str, flags);
    return json_str;
}
