

/* This file was generated by JSON Schema to C.
 * Any changes made to it will be lost on regeneration. 

 * Copyright (C) 2021-2023  TMLake(Beijing) Technology Co., Ltd.
 */

#include "njt_http_upstream_api_parser.h"
#include "njt_core.h"
#include "js2c_njet_builtins.h"
/* ========================== Generated parsers ========================== */


static bool parse_upstream_api(njt_pool_t *pool, parse_state_t *parse_state, upstream_api_t *out, js2c_parse_error_t *err_ret) {
    njt_uint_t i;

    js2c_check_type(JSMN_OBJECT);
    const int object_start_token = parse_state->current_token;
    const uint64_t n = parse_state->tokens[parse_state->current_token].size;
    parse_state->current_token += 1;
    for (i = 0; i < n; ++i) {
        js2c_key_children_check_for_obj();
        if (current_string_is(parse_state, "server")) {
            js2c_check_field_set(out->is_server_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "server";
            js2c_null_check();
            int token_size =  CURRENT_STRING_LENGTH(parse_state) ;
            ((&out->server))->data = (u_char*)njt_pcalloc(pool, (size_t)(token_size + 1));
            js2c_malloc_check(((&out->server))->data);
            ((&out->server))->len = token_size;
            if (builtin_parse_string(pool, parse_state, (&out->server), 0, ((&out->server))->len, err_ret)) {
                return true;
            }
            out->is_server_set = 1;
            parse_state->current_key = saved_key;
        } else if (current_string_is(parse_state, "weight")) {
            js2c_check_field_set(out->is_weight_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "weight";
            js2c_null_check();
            int64_t int_parse_tmp;
            if (builtin_parse_signed(pool, parse_state, true, false, 10, &int_parse_tmp, err_ret)) {
                return true;
            }
            js2c_int_range_check_min(1LL);
            *(&out->weight) = int_parse_tmp;
            out->is_weight_set = 1;
            parse_state->current_key = saved_key;
        } else if (current_string_is(parse_state, "max_conns")) {
            js2c_check_field_set(out->is_max_conns_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "max_conns";
            js2c_null_check();
            int64_t int_parse_tmp;
            if (builtin_parse_signed(pool, parse_state, true, false, 10, &int_parse_tmp, err_ret)) {
                return true;
            }
            js2c_int_range_check_min(0LL);
            *(&out->max_conns) = int_parse_tmp;
            out->is_max_conns_set = 1;
            parse_state->current_key = saved_key;
        } else if (current_string_is(parse_state, "max_fails")) {
            js2c_check_field_set(out->is_max_fails_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "max_fails";
            js2c_null_check();
            int64_t int_parse_tmp;
            if (builtin_parse_signed(pool, parse_state, true, false, 10, &int_parse_tmp, err_ret)) {
                return true;
            }
            js2c_int_range_check_min(0LL);
            *(&out->max_fails) = int_parse_tmp;
            out->is_max_fails_set = 1;
            parse_state->current_key = saved_key;
        } else if (current_string_is(parse_state, "down")) {
            js2c_check_field_set(out->is_down_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "down";
            js2c_null_check();
            if (builtin_parse_bool(pool, parse_state, (&out->down), err_ret)) {
                return true;
            }
            out->is_down_set = 1;
            parse_state->current_key = saved_key;
        } else if (current_string_is(parse_state, "backup")) {
            js2c_check_field_set(out->is_backup_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "backup";
            js2c_null_check();
            if (builtin_parse_bool(pool, parse_state, (&out->backup), err_ret)) {
                return true;
            }
            out->is_backup_set = 1;
            parse_state->current_key = saved_key;
        } else if (current_string_is(parse_state, "drain")) {
            js2c_check_field_set(out->is_drain_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "drain";
            js2c_null_check();
            if (builtin_parse_bool(pool, parse_state, (&out->drain), err_ret)) {
                return true;
            }
            out->is_drain_set = 1;
            parse_state->current_key = saved_key;
        } else if (current_string_is(parse_state, "fail_timeout")) {
            js2c_check_field_set(out->is_fail_timeout_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "fail_timeout";
            js2c_null_check();
            int token_size =  CURRENT_STRING_LENGTH(parse_state) ;
            ((&out->fail_timeout))->data = (u_char*)njt_pcalloc(pool, (size_t)(token_size + 1));
            js2c_malloc_check(((&out->fail_timeout))->data);
            ((&out->fail_timeout))->len = token_size;
            if (builtin_parse_string(pool, parse_state, (&out->fail_timeout), 0, ((&out->fail_timeout))->len, err_ret)) {
                return true;
            }
            out->is_fail_timeout_set = 1;
            parse_state->current_key = saved_key;
        } else if (current_string_is(parse_state, "slow_start")) {
            js2c_check_field_set(out->is_slow_start_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "slow_start";
            js2c_null_check();
            int token_size =  CURRENT_STRING_LENGTH(parse_state) ;
            ((&out->slow_start))->data = (u_char*)njt_pcalloc(pool, (size_t)(token_size + 1));
            js2c_malloc_check(((&out->slow_start))->data);
            ((&out->slow_start))->len = token_size;
            if (builtin_parse_string(pool, parse_state, (&out->slow_start), 0, ((&out->slow_start))->len, err_ret)) {
                return true;
            }
            out->is_slow_start_set = 1;
            parse_state->current_key = saved_key;
        } else if (current_string_is(parse_state, "route")) {
            js2c_check_field_set(out->is_route_set);
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "route";
            js2c_null_check();
            int token_size =  CURRENT_STRING_LENGTH(parse_state) ;
            ((&out->route))->data = (u_char*)njt_pcalloc(pool, (size_t)(token_size + 1));
            js2c_malloc_check(((&out->route))->data);
            ((&out->route))->len = token_size;
            if (builtin_parse_string(pool, parse_state, (&out->route), 0, 32, err_ret)) {
                return true;
            }
            out->is_route_set = 1;
            parse_state->current_key = saved_key;
        } else {
            LOG_ERROR_JSON_PARSE(UNKNOWN_FIELD_ERR, parse_state->current_key, CURRENT_TOKEN(parse_state).start, "Unknown field in '%s': %.*s", parse_state->current_key, CURRENT_STRING_FOR_ERROR(parse_state));
            return true;
        }
    }
    const int saved_current_token = parse_state->current_token;
    parse_state->current_token = object_start_token;
    // set default
    if (!out->is_server_set) {
        size_t token_size = strlen("");
        (out->server).data = (u_char*)njt_pcalloc(pool, token_size + 1);
        js2c_malloc_check((out->server).data);
        (out->server).len = token_size;
        if (out->server.len == 0) {
            (out->server).data[0] = 0;
        }
        if (token_size > 0) {
            njt_memcpy(out->server.data, "", token_size);
        }
    }
    // set default
    if (!out->is_weight_set) {
        out->weight = -1LL;
    }
    // set default
    if (!out->is_max_conns_set) {
        out->max_conns = -1LL;
    }
    // set default
    if (!out->is_max_fails_set) {
        out->max_fails = -1LL;
    }
    // set default
    if (!out->is_down_set) {
        out->down = true;
    }
    // set default
    if (!out->is_backup_set) {
        out->backup = true;
    }
    // set default
    if (!out->is_drain_set) {
        out->drain = true;
    }
    // set default
    if (!out->is_fail_timeout_set) {
        size_t token_size = strlen("");
        (out->fail_timeout).data = (u_char*)njt_pcalloc(pool, token_size + 1);
        js2c_malloc_check((out->fail_timeout).data);
        (out->fail_timeout).len = token_size;
        if (out->fail_timeout.len == 0) {
            (out->fail_timeout).data[0] = 0;
        }
        if (token_size > 0) {
            njt_memcpy(out->fail_timeout.data, "", token_size);
        }
    }
    // set default
    if (!out->is_slow_start_set) {
        size_t token_size = strlen("");
        (out->slow_start).data = (u_char*)njt_pcalloc(pool, token_size + 1);
        js2c_malloc_check((out->slow_start).data);
        (out->slow_start).len = token_size;
        if (out->slow_start.len == 0) {
            (out->slow_start).data[0] = 0;
        }
        if (token_size > 0) {
            njt_memcpy(out->slow_start.data, "", token_size);
        }
    }
    // set default
    if (!out->is_route_set) {
        size_t token_size = strlen("");
        (out->route).data = (u_char*)njt_pcalloc(pool, token_size + 1);
        js2c_malloc_check((out->route).data);
        (out->route).len = token_size;
        if (out->route.len == 0) {
            (out->route).data[0] = 0;
        }
        if (token_size > 0) {
            njt_memcpy(out->route.data, "", token_size);
        }
    }
    parse_state->current_token = saved_current_token;
    return false;
}


static void get_json_length_upstream_api_server(njt_pool_t *pool, upstream_api_server_t *out, size_t *length, njt_int_t flags) {
    njt_str_t *dst = handle_escape_on_write(pool, out);
    *length += dst->len + 2; //  "str" 
}

static void get_json_length_upstream_api_weight(njt_pool_t *pool, upstream_api_weight_t *out, size_t *length, njt_int_t flags) {
    u_char str[24];
    u_char *cur;
    cur = njt_sprintf(str, "%L", *out);
    *length += cur - str;
}

static void get_json_length_upstream_api_max_conns(njt_pool_t *pool, upstream_api_max_conns_t *out, size_t *length, njt_int_t flags) {
    u_char str[24];
    u_char *cur;
    cur = njt_sprintf(str, "%L", *out);
    *length += cur - str;
}

static void get_json_length_upstream_api_max_fails(njt_pool_t *pool, upstream_api_max_fails_t *out, size_t *length, njt_int_t flags) {
    u_char str[24];
    u_char *cur;
    cur = njt_sprintf(str, "%L", *out);
    *length += cur - str;
}

static void get_json_length_upstream_api_down(njt_pool_t *pool, upstream_api_down_t *out, size_t *length, njt_int_t flags) {
    if (*out) {
        *length += 4; // "true"
    } else {
        *length += 5; // "false"
    }
}

static void get_json_length_upstream_api_backup(njt_pool_t *pool, upstream_api_backup_t *out, size_t *length, njt_int_t flags) {
    if (*out) {
        *length += 4; // "true"
    } else {
        *length += 5; // "false"
    }
}

static void get_json_length_upstream_api_drain(njt_pool_t *pool, upstream_api_drain_t *out, size_t *length, njt_int_t flags) {
    if (*out) {
        *length += 4; // "true"
    } else {
        *length += 5; // "false"
    }
}

static void get_json_length_upstream_api_fail_timeout(njt_pool_t *pool, upstream_api_fail_timeout_t *out, size_t *length, njt_int_t flags) {
    njt_str_t *dst = handle_escape_on_write(pool, out);
    *length += dst->len + 2; //  "str" 
}

static void get_json_length_upstream_api_slow_start(njt_pool_t *pool, upstream_api_slow_start_t *out, size_t *length, njt_int_t flags) {
    njt_str_t *dst = handle_escape_on_write(pool, out);
    *length += dst->len + 2; //  "str" 
}

static void get_json_length_upstream_api_route(njt_pool_t *pool, upstream_api_route_t *out, size_t *length, njt_int_t flags) {
    njt_str_t *dst = handle_escape_on_write(pool, out);
    *length += dst->len + 2; //  "str" 
}

static void get_json_length_upstream_api(njt_pool_t *pool, upstream_api_t *out, size_t *length, njt_int_t flags) {
    if (out == NULL) {
        *length += 4; // null
        return;
    }
    *length += 1;
    njt_int_t omit;
    njt_int_t count = 0;
    omit = 0;
    omit = out->is_server_set ? 0 : 1;
    omit = (flags & OMIT_NULL_STR) && (out->server.data) == NULL ? 1 : omit;
    if (omit == 0) {
        *length += (6 + 3); // "server": 
        get_json_length_upstream_api_server(pool, (&out->server), length, flags);
        *length += 1; // ","
        count++;
    }
    omit = 0;
    omit = out->is_weight_set ? 0 : 1;
    if (omit == 0) {
        *length += (6 + 3); // "weight": 
        get_json_length_upstream_api_weight(pool, (&out->weight), length, flags);
        *length += 1; // ","
        count++;
    }
    omit = 0;
    omit = out->is_max_conns_set ? 0 : 1;
    if (omit == 0) {
        *length += (9 + 3); // "max_conns": 
        get_json_length_upstream_api_max_conns(pool, (&out->max_conns), length, flags);
        *length += 1; // ","
        count++;
    }
    omit = 0;
    omit = out->is_max_fails_set ? 0 : 1;
    if (omit == 0) {
        *length += (9 + 3); // "max_fails": 
        get_json_length_upstream_api_max_fails(pool, (&out->max_fails), length, flags);
        *length += 1; // ","
        count++;
    }
    omit = 0;
    omit = out->is_down_set ? 0 : 1;
    if (omit == 0) {
        *length += (4 + 3); // "down": 
        get_json_length_upstream_api_down(pool, (&out->down), length, flags);
        *length += 1; // ","
        count++;
    }
    omit = 0;
    omit = out->is_backup_set ? 0 : 1;
    if (omit == 0) {
        *length += (6 + 3); // "backup": 
        get_json_length_upstream_api_backup(pool, (&out->backup), length, flags);
        *length += 1; // ","
        count++;
    }
    omit = 0;
    omit = out->is_drain_set ? 0 : 1;
    if (omit == 0) {
        *length += (5 + 3); // "drain": 
        get_json_length_upstream_api_drain(pool, (&out->drain), length, flags);
        *length += 1; // ","
        count++;
    }
    omit = 0;
    omit = out->is_fail_timeout_set ? 0 : 1;
    omit = (flags & OMIT_NULL_STR) && (out->fail_timeout.data) == NULL ? 1 : omit;
    if (omit == 0) {
        *length += (12 + 3); // "fail_timeout": 
        get_json_length_upstream_api_fail_timeout(pool, (&out->fail_timeout), length, flags);
        *length += 1; // ","
        count++;
    }
    omit = 0;
    omit = out->is_slow_start_set ? 0 : 1;
    omit = (flags & OMIT_NULL_STR) && (out->slow_start.data) == NULL ? 1 : omit;
    if (omit == 0) {
        *length += (10 + 3); // "slow_start": 
        get_json_length_upstream_api_slow_start(pool, (&out->slow_start), length, flags);
        *length += 1; // ","
        count++;
    }
    omit = 0;
    omit = out->is_route_set ? 0 : 1;
    omit = (flags & OMIT_NULL_STR) && (out->route.data) == NULL ? 1 : omit;
    if (omit == 0) {
        *length += (5 + 3); // "route": 
        get_json_length_upstream_api_route(pool, (&out->route), length, flags);
        *length += 1; // ","
        count++;
    }
    if (count != 0) {
        *length -= 1; // "\b"
    }
    *length += 1;
}

upstream_api_server_t* get_upstream_api_server(upstream_api_t *out) {
    return &out->server;
}

upstream_api_weight_t get_upstream_api_weight(upstream_api_t *out) {
    return out->weight;
}

upstream_api_max_conns_t get_upstream_api_max_conns(upstream_api_t *out) {
    return out->max_conns;
}

upstream_api_max_fails_t get_upstream_api_max_fails(upstream_api_t *out) {
    return out->max_fails;
}

upstream_api_down_t get_upstream_api_down(upstream_api_t *out) {
    return out->down;
}

upstream_api_backup_t get_upstream_api_backup(upstream_api_t *out) {
    return out->backup;
}

upstream_api_drain_t get_upstream_api_drain(upstream_api_t *out) {
    return out->drain;
}

upstream_api_fail_timeout_t* get_upstream_api_fail_timeout(upstream_api_t *out) {
    return &out->fail_timeout;
}

upstream_api_slow_start_t* get_upstream_api_slow_start(upstream_api_t *out) {
    return &out->slow_start;
}

upstream_api_route_t* get_upstream_api_route(upstream_api_t *out) {
    return &out->route;
}
void set_upstream_api_server(upstream_api_t* obj, upstream_api_server_t* field) {
    njt_memcpy(&obj->server, field, sizeof(njt_str_t));
    obj->is_server_set = 1;
}
void set_upstream_api_weight(upstream_api_t* obj, upstream_api_weight_t field) {
    obj->weight = field;
    obj->is_weight_set = 1;
}
void set_upstream_api_max_conns(upstream_api_t* obj, upstream_api_max_conns_t field) {
    obj->max_conns = field;
    obj->is_max_conns_set = 1;
}
void set_upstream_api_max_fails(upstream_api_t* obj, upstream_api_max_fails_t field) {
    obj->max_fails = field;
    obj->is_max_fails_set = 1;
}
void set_upstream_api_down(upstream_api_t* obj, upstream_api_down_t field) {
    obj->down = field;
    obj->is_down_set = 1;
}
void set_upstream_api_backup(upstream_api_t* obj, upstream_api_backup_t field) {
    obj->backup = field;
    obj->is_backup_set = 1;
}
void set_upstream_api_drain(upstream_api_t* obj, upstream_api_drain_t field) {
    obj->drain = field;
    obj->is_drain_set = 1;
}
void set_upstream_api_fail_timeout(upstream_api_t* obj, upstream_api_fail_timeout_t* field) {
    njt_memcpy(&obj->fail_timeout, field, sizeof(njt_str_t));
    obj->is_fail_timeout_set = 1;
}
void set_upstream_api_slow_start(upstream_api_t* obj, upstream_api_slow_start_t* field) {
    njt_memcpy(&obj->slow_start, field, sizeof(njt_str_t));
    obj->is_slow_start_set = 1;
}
void set_upstream_api_route(upstream_api_t* obj, upstream_api_route_t* field) {
    njt_memcpy(&obj->route, field, sizeof(njt_str_t));
    obj->is_route_set = 1;
}
upstream_api_t* create_upstream_api(njt_pool_t *pool) {
    upstream_api_t* out = njt_pcalloc(pool, sizeof(upstream_api_t));
    return out;
}

static void to_oneline_json_upstream_api_server(njt_pool_t *pool, upstream_api_server_t *out, njt_str_t *buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    njt_str_t *dst = handle_escape_on_write(pool, out);
    cur = njt_sprintf(cur, "\"%V\"", dst);
    buf->len = cur - buf->data;
}

static void to_oneline_json_upstream_api_weight(njt_pool_t *pool, upstream_api_weight_t *out, njt_str_t* buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    cur = njt_sprintf(cur, "%L", *out);
    buf->len = cur - buf->data;
}

static void to_oneline_json_upstream_api_max_conns(njt_pool_t *pool, upstream_api_max_conns_t *out, njt_str_t* buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    cur = njt_sprintf(cur, "%L", *out);
    buf->len = cur - buf->data;
}

static void to_oneline_json_upstream_api_max_fails(njt_pool_t *pool, upstream_api_max_fails_t *out, njt_str_t* buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    cur = njt_sprintf(cur, "%L", *out);
    buf->len = cur - buf->data;
}

static void to_oneline_json_upstream_api_down(njt_pool_t *pool, upstream_api_down_t *out, njt_str_t *buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    if (*out) {
        njt_sprintf(cur, "true");
        buf->len += 4;
    } else {
        njt_sprintf(cur, "false");
        buf->len += 5;
    }
}

static void to_oneline_json_upstream_api_backup(njt_pool_t *pool, upstream_api_backup_t *out, njt_str_t *buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    if (*out) {
        njt_sprintf(cur, "true");
        buf->len += 4;
    } else {
        njt_sprintf(cur, "false");
        buf->len += 5;
    }
}

static void to_oneline_json_upstream_api_drain(njt_pool_t *pool, upstream_api_drain_t *out, njt_str_t *buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    if (*out) {
        njt_sprintf(cur, "true");
        buf->len += 4;
    } else {
        njt_sprintf(cur, "false");
        buf->len += 5;
    }
}

static void to_oneline_json_upstream_api_fail_timeout(njt_pool_t *pool, upstream_api_fail_timeout_t *out, njt_str_t *buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    njt_str_t *dst = handle_escape_on_write(pool, out);
    cur = njt_sprintf(cur, "\"%V\"", dst);
    buf->len = cur - buf->data;
}

static void to_oneline_json_upstream_api_slow_start(njt_pool_t *pool, upstream_api_slow_start_t *out, njt_str_t *buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    njt_str_t *dst = handle_escape_on_write(pool, out);
    cur = njt_sprintf(cur, "\"%V\"", dst);
    buf->len = cur - buf->data;
}

static void to_oneline_json_upstream_api_route(njt_pool_t *pool, upstream_api_route_t *out, njt_str_t *buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    njt_str_t *dst = handle_escape_on_write(pool, out);
    cur = njt_sprintf(cur, "\"%V\"", dst);
    buf->len = cur - buf->data;
}

static void to_oneline_json_upstream_api(njt_pool_t *pool, upstream_api_t *out, njt_str_t* buf, njt_int_t flags) {
    njt_int_t omit;
    u_char* cur = buf->data + buf->len;
    if (out == NULL) {
        cur = njt_sprintf(cur, "null");
        buf->len += 4;
        return;
    }
    cur = njt_sprintf(cur, "{");
    buf->len ++;
    omit = 0;
    omit = out->is_server_set ? 0 : 1;
    omit = (flags & OMIT_NULL_STR) && (out->server.data) == NULL ? 1 : omit;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"server\":");
        buf->len = cur - buf->data;
        to_oneline_json_upstream_api_server(pool, (&out->server), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    omit = 0;
    omit = out->is_weight_set ? 0 : 1;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"weight\":");
        buf->len = cur - buf->data;
        to_oneline_json_upstream_api_weight(pool, (&out->weight), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    omit = 0;
    omit = out->is_max_conns_set ? 0 : 1;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"max_conns\":");
        buf->len = cur - buf->data;
        to_oneline_json_upstream_api_max_conns(pool, (&out->max_conns), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    omit = 0;
    omit = out->is_max_fails_set ? 0 : 1;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"max_fails\":");
        buf->len = cur - buf->data;
        to_oneline_json_upstream_api_max_fails(pool, (&out->max_fails), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    omit = 0;
    omit = out->is_down_set ? 0 : 1;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"down\":");
        buf->len = cur - buf->data;
        to_oneline_json_upstream_api_down(pool, (&out->down), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    omit = 0;
    omit = out->is_backup_set ? 0 : 1;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"backup\":");
        buf->len = cur - buf->data;
        to_oneline_json_upstream_api_backup(pool, (&out->backup), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    omit = 0;
    omit = out->is_drain_set ? 0 : 1;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"drain\":");
        buf->len = cur - buf->data;
        to_oneline_json_upstream_api_drain(pool, (&out->drain), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    omit = 0;
    omit = out->is_fail_timeout_set ? 0 : 1;
    omit = (flags & OMIT_NULL_STR) && (out->fail_timeout.data) == NULL ? 1 : omit;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"fail_timeout\":");
        buf->len = cur - buf->data;
        to_oneline_json_upstream_api_fail_timeout(pool, (&out->fail_timeout), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    omit = 0;
    omit = out->is_slow_start_set ? 0 : 1;
    omit = (flags & OMIT_NULL_STR) && (out->slow_start.data) == NULL ? 1 : omit;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"slow_start\":");
        buf->len = cur - buf->data;
        to_oneline_json_upstream_api_slow_start(pool, (&out->slow_start), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    omit = 0;
    omit = out->is_route_set ? 0 : 1;
    omit = (flags & OMIT_NULL_STR) && (out->route.data) == NULL ? 1 : omit;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"route\":");
        buf->len = cur - buf->data;
        to_oneline_json_upstream_api_route(pool, (&out->route), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    cur--;
    if (cur[0] == ',') {
        buf->len --;
    } else {
        cur ++;
    }
    cur = njt_sprintf(cur, "}");
    buf->len ++;
}
upstream_api_t* json_parse_upstream_api(njt_pool_t *pool, const njt_str_t *json_string, js2c_parse_error_t *err_ret) {
    upstream_api_t* out;
    parse_state_t parse_state_var;
    parse_state_t *parse_state = &parse_state_var;
    uint64_t max_token_number = 1024;
    jsmntok_t *token_buffer;
    int parse_result;
    for ( ; /* parse unsuccessful */; ) {
        token_buffer = njt_pcalloc(pool, sizeof(jsmntok_t)*max_token_number);
        parse_result = builtin_parse_json_string(pool, parse_state, token_buffer, max_token_number, (char *)json_string->data, json_string->len, err_ret);
        if (parse_result == JSMN_ERROR_INVAL) {
            LOG_ERROR_JSON_PARSE(INVALID_JSON_CHAR_ERR, "", -1, "%s", "Invalid character inside JSON string");
            return NULL;
        }
        if (parse_result == JSMN_ERROR_PART) {
            LOG_ERROR_JSON_PARSE(PARTIAL_JSON_ERR, "", -1, "%s", "The string is not a full JSON packet, more bytes expected");
            return NULL;
        }
        if (parse_result == JSMN_ERROR_NOMEM) {
            max_token_number += max_token_number;
            continue;
        }
        if (parse_result == 0) {
            LOG_ERROR_JSON_PARSE(NULL_JSON_ERR, "", 0, "String did not contain %s JSON tokens", "any");
            return NULL;
        }
        break; // parse success
    }
    out = njt_pcalloc(pool, sizeof(upstream_api_t));;
    memset(out, 0, sizeof(upstream_api_t));
    if (parse_upstream_api(pool, parse_state, out, err_ret)) {
        return NULL;
    }
    return out;
}

njt_str_t* to_json_upstream_api(njt_pool_t *pool, upstream_api_t* out, njt_int_t flags) {
    njt_str_t *json_str;
    json_str = njt_pcalloc(pool, sizeof(njt_str_t));
    size_t str_len = 0;
    get_json_length_upstream_api(pool, out, &str_len, flags);
    json_str->data = (u_char*)njt_pcalloc(pool, str_len + 1);
    json_str->len = 0;
    to_oneline_json_upstream_api(pool, out, json_str, flags);
    return json_str;
}
