

/* This file was generated by JSON Schema to C.
 * Any changes made to it will be lost on regeneration. 

 * Copyright (C) Roman Arutyunyan
 * Copyright (C) Nginx, Inc.
 * Copyright (C) 2021-2023  TMLake(Beijing) Technology Co., Ltd.
 */

#include "njt_http_dyn_fault_inject_parser.h"
#include "njt_core.h"
#include "js2c_njet_builtins.h"
/* ========================== Generated parsers ========================== */

static bool parse_locationDef(njt_pool_t *pool, parse_state_t *parse_state, locationDef_t *out, njt_str_t* err_str); //forward decl for public definition
static void get_json_length_locationDef(locationDef_t *out, size_t *length, njt_int_t flags); //forward decl for public definition
static void to_oneline_json_locationDef(locationDef_t *out, njt_str_t *buf, njt_int_t flags); //forward decl for public definition

static bool parse_locationDef_fault_inject_type(njt_pool_t *pool, parse_state_t *parse_state, locationDef_fault_inject_type_t *out, njt_str_t *err_str) {
    if (check_type(pool, parse_state, JSMN_STRING, err_str)) {
        return true;
    }
    if (current_string_is(parse_state, "none")) {
        *out = LOCATIONDEF_FAULT_INJECT_TYPE_NONE;
    } else if (current_string_is(parse_state, "delay")) {
        *out = LOCATIONDEF_FAULT_INJECT_TYPE_DELAY;
    } else if (current_string_is(parse_state, "abort")) {
        *out = LOCATIONDEF_FAULT_INJECT_TYPE_ABORT;
    } else if (current_string_is(parse_state, "delay_abort")) {
        *out = LOCATIONDEF_FAULT_INJECT_TYPE_DELAY_ABORT;
    } else {
        LOG_ERROR_JSON_PARSE(CURRENT_TOKEN(parse_state).start, "Unknown enum value in '%s': %.*s", parse_state->current_key, CURRENT_STRING_FOR_ERROR(parse_state))
        return true;
    }
    parse_state->current_token += 1;
    return false;
}


static bool parse_locationDef_locations(njt_pool_t *pool, parse_state_t *parse_state, locationDef_locations_t *out, njt_str_t *err_str) {
    int i;
    if (check_type(pool, parse_state, JSMN_ARRAY, err_str)) {
        return true;
    }
    const int n = parse_state->tokens[parse_state->current_token].size;
    // memory has been allocate in njt_array_create.
    parse_state->current_token += 1;
    for (i = 0; i < n; ++i) {
        // TODO CHECK write later
        ((locationDef_locations_item_t**)out->elts)[i] = njt_palloc(pool, sizeof(locationDef_t));
        if (parse_locationDef(pool, parse_state, ((locationDef_locations_item_t**)out->elts)[i], err_str)) {
            return true;
        }
        out->nelts ++;
    }
    return false;
}


static bool parse_locationDef(njt_pool_t *pool, parse_state_t *parse_state, locationDef_t *out, njt_str_t *err_str) {
    njt_uint_t i;
    // malloc pool for object first

    if (check_type(pool, parse_state, JSMN_OBJECT, err_str)) {
        return true;
    }
    bool seen_location = false;
    bool seen_fault_inject_type = false;
    bool seen_delay_percentage = false;
    bool seen_abort_percentage = false;
    bool seen_status_code = false;
    bool seen_delay_duration = false;
    bool seen_locations = false;
    const int object_start_token = parse_state->current_token;
    const uint64_t n = parse_state->tokens[parse_state->current_token].size;
    parse_state->current_token += 1;
    for (i = 0; i < n; ++i) {
        if (CURRENT_TOKEN(parse_state).size > 1) {
            LOG_ERROR_JSON_PARSE(CURRENT_TOKEN(parse_state).start, "Missing separator between values in '%s', after key: %.*s", parse_state->current_key, CURRENT_STRING_FOR_ERROR(parse_state))
            return true;
        }
        if (CURRENT_TOKEN(parse_state).size < 1) {
            LOG_ERROR_JSON_PARSE(CURRENT_TOKEN(parse_state).start, "Missing value in '%s', after key: %.*s", parse_state->current_key, CURRENT_STRING_FOR_ERROR(parse_state))
            return true;
        }
        if (current_string_is(parse_state, "location")) {
            if (seen_location) {
                LOG_ERROR_JSON_PARSE(CURRENT_TOKEN(parse_state).start, "Duplicate field definition in '%s': location", parse_state->current_key)
                return true;
            }
            seen_location = true;
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "location";
            out->location = njt_palloc(pool, sizeof(njt_str_t));
            if (out->location == NULL) {
                LOG_ERROR_JSON_PARSE(0, "Failed to allocate memory from %s.", "pool")
            }
            // first get str len from TOKEN_STRING
            int token_size =  CURRENT_STRING_LENGTH(parse_state) ;
            (out->location) = njt_palloc(pool, sizeof(njt_str_t));
            if ((out->location) == NULL) {
                // TODO LOG_ERROR
                return true;
            }
            ((out->location))->data = njt_palloc(pool, (size_t)(token_size));
            ((out->location))->len = token_size;
            if ((out->location)->data == NULL) {
                // TODO LOG_ERROR
                return true;
            }
            if (builtin_parse_string(pool, parse_state, (char *)((out->location))->data, 0, ((out->location))->len, err_str)) {
                return true;
            }
            parse_state->current_key = saved_key;
        } else if (current_string_is(parse_state, "fault_inject_type")) {
            if (seen_fault_inject_type) {
                LOG_ERROR_JSON_PARSE(CURRENT_TOKEN(parse_state).start, "Duplicate field definition in '%s': fault_inject_type", parse_state->current_key)
                return true;
            }
            seen_fault_inject_type = true;
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "fault_inject_type";
            if (parse_locationDef_fault_inject_type(pool, parse_state, (&out->fault_inject_type), err_str)) {
                return true;
            }
            parse_state->current_key = saved_key;
        } else if (current_string_is(parse_state, "delay_percentage")) {
            if (seen_delay_percentage) {
                LOG_ERROR_JSON_PARSE(CURRENT_TOKEN(parse_state).start, "Duplicate field definition in '%s': delay_percentage", parse_state->current_key)
                return true;
            }
            seen_delay_percentage = true;
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "delay_percentage";
            int64_t int_parse_tmp;
            if (builtin_parse_signed(pool, parse_state, true, false, 10, &int_parse_tmp, err_str)) {
                return true;
            }
            if (!(int_parse_tmp >= 1)) {
                parse_state->current_token -= 1;
                LOG_ERROR_JSON_PARSE(CURRENT_TOKEN(parse_state).start, "Integer %" PRIi64 " in '%s' out of range. It must be >= 1.", int_parse_tmp, parse_state->current_key)
                return true;
            }
            if (!(int_parse_tmp <= 100)) {
                parse_state->current_token -= 1;
                LOG_ERROR_JSON_PARSE(CURRENT_TOKEN(parse_state).start, "Integer %" PRIi64 " in '%s' out of range. It must be <= 100.", int_parse_tmp, parse_state->current_key)
                return true;
            }
            *(&out->delay_percentage) = int_parse_tmp;
            parse_state->current_key = saved_key;
        } else if (current_string_is(parse_state, "abort_percentage")) {
            if (seen_abort_percentage) {
                LOG_ERROR_JSON_PARSE(CURRENT_TOKEN(parse_state).start, "Duplicate field definition in '%s': abort_percentage", parse_state->current_key)
                return true;
            }
            seen_abort_percentage = true;
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "abort_percentage";
            int64_t int_parse_tmp;
            if (builtin_parse_signed(pool, parse_state, true, false, 10, &int_parse_tmp, err_str)) {
                return true;
            }
            if (!(int_parse_tmp >= 1)) {
                parse_state->current_token -= 1;
                LOG_ERROR_JSON_PARSE(CURRENT_TOKEN(parse_state).start, "Integer %" PRIi64 " in '%s' out of range. It must be >= 1.", int_parse_tmp, parse_state->current_key)
                return true;
            }
            if (!(int_parse_tmp <= 100)) {
                parse_state->current_token -= 1;
                LOG_ERROR_JSON_PARSE(CURRENT_TOKEN(parse_state).start, "Integer %" PRIi64 " in '%s' out of range. It must be <= 100.", int_parse_tmp, parse_state->current_key)
                return true;
            }
            *(&out->abort_percentage) = int_parse_tmp;
            parse_state->current_key = saved_key;
        } else if (current_string_is(parse_state, "status_code")) {
            if (seen_status_code) {
                LOG_ERROR_JSON_PARSE(CURRENT_TOKEN(parse_state).start, "Duplicate field definition in '%s': status_code", parse_state->current_key)
                return true;
            }
            seen_status_code = true;
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "status_code";
            int64_t int_parse_tmp;
            if (builtin_parse_signed(pool, parse_state, true, false, 10, &int_parse_tmp, err_str)) {
                return true;
            }
            if (!(int_parse_tmp >= 200)) {
                parse_state->current_token -= 1;
                LOG_ERROR_JSON_PARSE(CURRENT_TOKEN(parse_state).start, "Integer %" PRIi64 " in '%s' out of range. It must be >= 200.", int_parse_tmp, parse_state->current_key)
                return true;
            }
            if (!(int_parse_tmp <= 600)) {
                parse_state->current_token -= 1;
                LOG_ERROR_JSON_PARSE(CURRENT_TOKEN(parse_state).start, "Integer %" PRIi64 " in '%s' out of range. It must be <= 600.", int_parse_tmp, parse_state->current_key)
                return true;
            }
            *(&out->status_code) = int_parse_tmp;
            parse_state->current_key = saved_key;
        } else if (current_string_is(parse_state, "delay_duration")) {
            if (seen_delay_duration) {
                LOG_ERROR_JSON_PARSE(CURRENT_TOKEN(parse_state).start, "Duplicate field definition in '%s': delay_duration", parse_state->current_key)
                return true;
            }
            seen_delay_duration = true;
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "delay_duration";
            out->delay_duration = njt_palloc(pool, sizeof(njt_str_t));
            if (out->delay_duration == NULL) {
                LOG_ERROR_JSON_PARSE(0, "Failed to allocate memory from %s.", "pool")
            }
            // first get str len from TOKEN_STRING
            int token_size =  CURRENT_STRING_LENGTH(parse_state) ;
            (out->delay_duration) = njt_palloc(pool, sizeof(njt_str_t));
            if ((out->delay_duration) == NULL) {
                // TODO LOG_ERROR
                return true;
            }
            ((out->delay_duration))->data = njt_palloc(pool, (size_t)(token_size));
            ((out->delay_duration))->len = token_size;
            if ((out->delay_duration)->data == NULL) {
                // TODO LOG_ERROR
                return true;
            }
            if (builtin_parse_string(pool, parse_state, (char *)((out->delay_duration))->data, 0, ((out->delay_duration))->len, err_str)) {
                return true;
            }
            parse_state->current_key = saved_key;
        } else if (current_string_is(parse_state, "locations")) {
            if (seen_locations) {
                LOG_ERROR_JSON_PARSE(CURRENT_TOKEN(parse_state).start, "Duplicate field definition in '%s': locations", parse_state->current_key)
                return true;
            }
            seen_locations = true;
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "locations";
            out->locations = njt_array_create(pool, parse_state->tokens[parse_state->current_token].size ,sizeof(locationDef_locations_item_t*));
            if (out->locations == NULL) {
                LOG_ERROR_JSON_PARSE(0, "Failed to allocate memory from %s.", "pool")
            }
            if (parse_locationDef_locations(pool, parse_state, (out->locations), err_str)) {
                return true;
            }
            parse_state->current_key = saved_key;
        } else {
            LOG_ERROR_JSON_PARSE(CURRENT_TOKEN(parse_state).start, "Unknown field in '%s': %.*s", parse_state->current_key, CURRENT_STRING_FOR_ERROR(parse_state))
            return true;
        }
    }
    const int saved_current_token = parse_state->current_token;
    parse_state->current_token = object_start_token;
    if (!seen_location) {
        LOG_ERROR_JSON_PARSE(CURRENT_TOKEN(parse_state).start, "Missing required field in '%s': location", parse_state->current_key)
        return true;
    }
    if (!seen_fault_inject_type) {
        LOG_ERROR_JSON_PARSE(CURRENT_TOKEN(parse_state).start, "Missing required field in '%s': fault_inject_type", parse_state->current_key)
        return true;
    }
    // HAHB
    if (!seen_delay_percentage) {
        out->delay_percentage = 100LL;
    }
    // HAHB
    if (!seen_abort_percentage) {
        out->abort_percentage = 100LL;
    }
    // HAHB
    if (!seen_status_code) {
        out->status_code = 200LL;
    }
    // HAHB
    if (!seen_delay_duration) {
        out->delay_duration = njt_palloc(pool, sizeof(njt_str_t));
        if (out->delay_duration == NULL) {
            // TODO LOG_ERROR
            return true;
        }
        size_t token_size = strlen("");
        (out->delay_duration)->data = njt_palloc(pool, token_size);
        (out->delay_duration)->len = token_size;
        if (out->delay_duration->data == NULL) {
            // TODO LOG_ERROR
            return true;
        }
        njt_memcpy(out->delay_duration->data, "", token_size);
    }
    // HAHB
    if (!seen_locations) {
        out->locations = njt_palloc(pool, sizeof(njt_array_t));
        memset(out->locations, 0, sizeof(njt_array_t));
    }
    parse_state->current_token = saved_current_token;
    return false;
}


static void get_json_length_locationDef_location(locationDef_location_t *out, size_t *length, njt_int_t flags) {
    *length += (*out)->len + 2; //  "str" 
}
// BEGIN GET_JSON_LENGTH ENUM

static void get_json_length_locationDef_fault_inject_type(locationDef_fault_inject_type_t *out, size_t *length, njt_int_t flags) {
    if (*out == LOCATIONDEF_FAULT_INJECT_TYPE_NONE) {
        // "none"
        *length += 4 + 2;
        return;
    }
    if (*out == LOCATIONDEF_FAULT_INJECT_TYPE_DELAY) {
        // "delay"
        *length += 5 + 2;
        return;
    }
    if (*out == LOCATIONDEF_FAULT_INJECT_TYPE_ABORT) {
        // "abort"
        *length += 5 + 2;
        return;
    }
    if (*out == LOCATIONDEF_FAULT_INJECT_TYPE_DELAY_ABORT) {
        // "delay_abort"
        *length += 11 + 2;
        return;
    }
}

static void get_json_length_locationDef_delay_percentage(locationDef_delay_percentage_t *out, size_t *length, njt_int_t flags) {
    u_char str[24], *cur;
    cur = njt_sprintf(str, "%i", *out); // Convert integer to string
    *length += cur - str;
}

static void get_json_length_locationDef_abort_percentage(locationDef_abort_percentage_t *out, size_t *length, njt_int_t flags) {
    u_char str[24], *cur;
    cur = njt_sprintf(str, "%i", *out); // Convert integer to string
    *length += cur - str;
}

static void get_json_length_locationDef_status_code(locationDef_status_code_t *out, size_t *length, njt_int_t flags) {
    u_char str[24], *cur;
    cur = njt_sprintf(str, "%i", *out); // Convert integer to string
    *length += cur - str;
}

static void get_json_length_locationDef_delay_duration(locationDef_delay_duration_t *out, size_t *length, njt_int_t flags) {
    *length += (*out)->len + 2; //  "str" 
}
// GET_JSON_LENGTH_REF

static void get_json_length_locationDef_locations_item(locationDef_locations_item_t *out, size_t *length, njt_int_t flags) {
    get_json_length_locationDef(out, length, flags);
}

static void get_json_length_locationDef_locations(locationDef_locations_t *out, size_t *length, njt_int_t flags) {
    njt_uint_t i;
    njt_uint_t omit;
    njt_int_t count = 0;
    if (out == NULL) {
        *length += 2; // "[]"
        return;
    }
    *length += 2; // "[]"
    for (i = 0; i < out->nelts; ++i) {
        omit = 0;
        if ((flags & OMIT_NULL_OBJ) && ((locationDef_locations_item_t**)out->elts)[i] == NULL) {
            omit = 1;
        }
        if (omit == 0) {
            get_json_length_locationDef_locations_item(((locationDef_locations_item_t**)out->elts)[i], length, flags);
            *length += 1; // ","
            count++; // ","
        }
    }
    if (count != 0) {
        *length -= 1; // "\b"
    }
}

static void get_json_length_locationDef(locationDef_t *out, size_t *length, njt_int_t flags) {
    if (out == NULL) {
        *length += 4; // null
        return;
    }
    *length += 1;
    njt_int_t omit;
    njt_int_t count = 0;
    omit = 0;
    if ((flags & OMIT_NULL_STR) && (out->location) == NULL) {
        omit = 1;
    }
    if (omit == 0) {
        *length += (8 + 3); // "location": 
        get_json_length_locationDef_location((&out->location), length, flags);
        *length += 1; // ","
        count++;
    }
    omit = 0;
    if (omit == 0) {
        *length += (17 + 3); // "fault_inject_type": 
        get_json_length_locationDef_fault_inject_type((&out->fault_inject_type), length, flags);
        *length += 1; // ","
        count++;
    }
    omit = 0;
    if (omit == 0) {
        *length += (16 + 3); // "delay_percentage": 
        get_json_length_locationDef_delay_percentage((&out->delay_percentage), length, flags);
        *length += 1; // ","
        count++;
    }
    omit = 0;
    if (omit == 0) {
        *length += (16 + 3); // "abort_percentage": 
        get_json_length_locationDef_abort_percentage((&out->abort_percentage), length, flags);
        *length += 1; // ","
        count++;
    }
    omit = 0;
    if (omit == 0) {
        *length += (11 + 3); // "status_code": 
        get_json_length_locationDef_status_code((&out->status_code), length, flags);
        *length += 1; // ","
        count++;
    }
    omit = 0;
    if ((flags & OMIT_NULL_STR) && (out->delay_duration) == NULL) {
        omit = 1;
    }
    if (omit == 0) {
        *length += (14 + 3); // "delay_duration": 
        get_json_length_locationDef_delay_duration((&out->delay_duration), length, flags);
        *length += 1; // ","
        count++;
    }
    omit = 0;
    if ((flags & OMIT_NULL_ARRAY) && (out->locations) == NULL) {
        omit = 1;
    }
    if (omit == 0) {
        *length += (9 + 3); // "locations": 
        get_json_length_locationDef_locations((out->locations), length, flags);
        *length += 1; // ","
        count++;
    }
    if (count != 0) {
        *length -= 1; // "\b"
    }
    *length += 1;
}
// CHECK ARRAY not exceeding bounds before call this func

locationDef_locations_item_t get_locationDef_locations_item(locationDef_locations_t *out, size_t idx) {
    return *((locationDef_locations_item_t**)out->elts)[idx];
}

locationDef_location_t get_locationDef_location(locationDef_t *out) {
    return out->location;
}

locationDef_fault_inject_type_t get_locationDef_fault_inject_type(locationDef_t *out) {
    return out->fault_inject_type;
}

locationDef_delay_percentage_t get_locationDef_delay_percentage(locationDef_t *out) {
    return out->delay_percentage;
}

locationDef_abort_percentage_t get_locationDef_abort_percentage(locationDef_t *out) {
    return out->abort_percentage;
}

locationDef_status_code_t get_locationDef_status_code(locationDef_t *out) {
    return out->status_code;
}

locationDef_delay_duration_t get_locationDef_delay_duration(locationDef_t *out) {
    return out->delay_duration;
}

locationDef_locations_t* get_locationDef_locations(locationDef_t *out) {
    return out->locations;
}
void set_locationDef_location(locationDef_t* obj, locationDef_location_t field) {
    obj->location = field;
}
void set_locationDef_delay_duration(locationDef_t* obj, locationDef_delay_duration_t field) {
    obj->delay_duration = field;
}
int add_item_locationDef_locations(locationDef_locations_t *src, locationDef_locations_item_t* item) {
    void *new = njt_array_push(src);
    if (new == NULL) {
        return NJT_ERROR;
    }
    njt_memcpy(new, &item, src->size);
    return NJT_OK;
}

locationDef_locations_t* create_locationDef_locations(njt_pool_t *pool, size_t length) {
    return njt_array_create(pool, length, sizeof(locationDef_locations_item_t*));
}
void set_locationDef_locations(locationDef_t* obj, locationDef_locations_t* field) {
    obj->locations = field;
}
locationDef_t* create_locationDef(njt_pool_t *pool) {
    locationDef_t* out = njt_palloc(pool, sizeof(locationDef_t));
    memset(out, 0, sizeof(locationDef_t));
    return out;
}

static void to_oneline_json_locationDef_location(locationDef_location_t *out, njt_str_t *buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    njt_sprintf(cur, "\"%V\"", *out);
    buf->len += (*out)->len + 2;
}

static void to_oneline_json_locationDef_fault_inject_type(locationDef_fault_inject_type_t *out, njt_str_t* buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    if (*out == LOCATIONDEF_FAULT_INJECT_TYPE_NONE) {
        cur = njt_sprintf(cur, "\"none\"");
        buf->len += 4 + 2;
        return;
    }
    if (*out == LOCATIONDEF_FAULT_INJECT_TYPE_DELAY) {
        cur = njt_sprintf(cur, "\"delay\"");
        buf->len += 5 + 2;
        return;
    }
    if (*out == LOCATIONDEF_FAULT_INJECT_TYPE_ABORT) {
        cur = njt_sprintf(cur, "\"abort\"");
        buf->len += 5 + 2;
        return;
    }
    if (*out == LOCATIONDEF_FAULT_INJECT_TYPE_DELAY_ABORT) {
        cur = njt_sprintf(cur, "\"delay_abort\"");
        buf->len += 11 + 2;
        return;
    }
}

static void to_oneline_json_locationDef_delay_percentage(locationDef_delay_percentage_t *out, njt_str_t* buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    cur = njt_sprintf(cur, "%i", *out);
    buf->len = cur - buf->data;
}

static void to_oneline_json_locationDef_abort_percentage(locationDef_abort_percentage_t *out, njt_str_t* buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    cur = njt_sprintf(cur, "%i", *out);
    buf->len = cur - buf->data;
}

static void to_oneline_json_locationDef_status_code(locationDef_status_code_t *out, njt_str_t* buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    cur = njt_sprintf(cur, "%i", *out);
    buf->len = cur - buf->data;
}

static void to_oneline_json_locationDef_delay_duration(locationDef_delay_duration_t *out, njt_str_t *buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    njt_sprintf(cur, "\"%V\"", *out);
    buf->len += (*out)->len + 2;
}
// to_oneline_json_REF

static void to_oneline_json_locationDef_locations_item(locationDef_locations_item_t *out, njt_str_t* buf, njt_int_t flags) {
    to_oneline_json_locationDef(out, buf, flags);
}

static void to_oneline_json_locationDef_locations(locationDef_locations_t *out, njt_str_t* buf, njt_int_t flags) {
    njt_int_t omit;
    u_char *cur = buf->data + buf->len;
    njt_uint_t i;
    if (out == NULL || out->nelts == 0) {
        cur = njt_sprintf(cur, "[]");
        buf->len += 2;
        return;
    }
    cur = njt_sprintf(cur,  "[");
    buf->len ++;
    for (i = 0; i < out->nelts; ++i) {
        omit = 0;
        if ((flags & OMIT_NULL_OBJ) && ((locationDef_locations_item_t**)out->elts)[i] == NULL) {
            omit = 1;
        }
        if (omit == 0) {
            to_oneline_json_locationDef_locations_item(((locationDef_locations_item_t**)out->elts)[i], buf, flags);
            cur = buf->data + buf->len;
            cur = njt_sprintf(cur, ",");
            buf->len ++;
        }
    }
    cur--;
    if (cur[0] == ',') {
        buf->len --;
    } else {
        cur ++;
    }
    cur = njt_sprintf(cur,  "]");
    buf->len ++;
}

static void to_oneline_json_locationDef(locationDef_t *out, njt_str_t* buf, njt_int_t flags) {
    njt_int_t omit;
    u_char* cur = buf->data + buf->len;
    if (out == NULL) {
        cur = njt_sprintf(cur, "null");
        buf->len += 4;
        return;
    }
    cur = njt_sprintf(cur, "{");
    buf->len ++;
    omit = 0;
    if ((flags & OMIT_NULL_STR) && (out->location) == NULL) {
        omit = 1;
    }
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"location\":");
        buf->len = cur - buf->data;
        to_oneline_json_locationDef_location((&out->location), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    omit = 0;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"fault_inject_type\":");
        buf->len = cur - buf->data;
        to_oneline_json_locationDef_fault_inject_type((&out->fault_inject_type), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    omit = 0;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"delay_percentage\":");
        buf->len = cur - buf->data;
        to_oneline_json_locationDef_delay_percentage((&out->delay_percentage), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    omit = 0;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"abort_percentage\":");
        buf->len = cur - buf->data;
        to_oneline_json_locationDef_abort_percentage((&out->abort_percentage), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    omit = 0;
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"status_code\":");
        buf->len = cur - buf->data;
        to_oneline_json_locationDef_status_code((&out->status_code), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    omit = 0;
    if ((flags & OMIT_NULL_STR) && (out->delay_duration) == NULL) {
        omit = 1;
    }
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"delay_duration\":");
        buf->len = cur - buf->data;
        to_oneline_json_locationDef_delay_duration((&out->delay_duration), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    omit = 0;
    if ((flags & OMIT_NULL_ARRAY) && (out->locations) == NULL) {
        omit = 1;
    }
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"locations\":");
        buf->len = cur - buf->data;
        to_oneline_json_locationDef_locations((out->locations), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    cur--;
    if (cur[0] == ',') {
        buf->len --;
    } else {
        cur ++;
    }
    cur = njt_sprintf(cur, "}");
    buf->len ++;
}

static bool parse_dyn_fault_inject_servers_item_listens(njt_pool_t *pool, parse_state_t *parse_state, dyn_fault_inject_servers_item_listens_t *out, njt_str_t *err_str) {
    int i;
    if (check_type(pool, parse_state, JSMN_ARRAY, err_str)) {
        return true;
    }
    const int n = parse_state->tokens[parse_state->current_token].size;
    // memory has been allocate in njt_array_create.
    parse_state->current_token += 1;
    for (i = 0; i < n; ++i) {
        // TODO CHECK write later
        ((dyn_fault_inject_servers_item_listens_item_t*)out->elts)[i] = njt_palloc(pool, sizeof(njt_str_t));
        // first get str len from TOKEN_STRING
        int token_size =  CURRENT_STRING_LENGTH(parse_state) ;
        ((dyn_fault_inject_servers_item_listens_item_t*)out->elts)[i] = njt_palloc(pool, sizeof(njt_str_t));
        if (((dyn_fault_inject_servers_item_listens_item_t*)out->elts)[i] == NULL) {
            // TODO LOG_ERROR
            return true;
        }
        (((dyn_fault_inject_servers_item_listens_item_t*)out->elts)[i])->data = njt_palloc(pool, (size_t)(token_size));
        (((dyn_fault_inject_servers_item_listens_item_t*)out->elts)[i])->len = token_size;
        if (((dyn_fault_inject_servers_item_listens_item_t*)out->elts)[i]->data == NULL) {
            // TODO LOG_ERROR
            return true;
        }
        if (builtin_parse_string(pool, parse_state, (char *)(((dyn_fault_inject_servers_item_listens_item_t*)out->elts)[i])->data, 0, (((dyn_fault_inject_servers_item_listens_item_t*)out->elts)[i])->len, err_str)) {
            return true;
        }
        out->nelts ++;
    }
    return false;
}


static bool parse_dyn_fault_inject_servers_item_serverNames(njt_pool_t *pool, parse_state_t *parse_state, dyn_fault_inject_servers_item_serverNames_t *out, njt_str_t *err_str) {
    int i;
    if (check_type(pool, parse_state, JSMN_ARRAY, err_str)) {
        return true;
    }
    const int n = parse_state->tokens[parse_state->current_token].size;
    // memory has been allocate in njt_array_create.
    parse_state->current_token += 1;
    for (i = 0; i < n; ++i) {
        // TODO CHECK write later
        ((dyn_fault_inject_servers_item_serverNames_item_t*)out->elts)[i] = njt_palloc(pool, sizeof(njt_str_t));
        // first get str len from TOKEN_STRING
        int token_size =  CURRENT_STRING_LENGTH(parse_state) ;
        ((dyn_fault_inject_servers_item_serverNames_item_t*)out->elts)[i] = njt_palloc(pool, sizeof(njt_str_t));
        if (((dyn_fault_inject_servers_item_serverNames_item_t*)out->elts)[i] == NULL) {
            // TODO LOG_ERROR
            return true;
        }
        (((dyn_fault_inject_servers_item_serverNames_item_t*)out->elts)[i])->data = njt_palloc(pool, (size_t)(token_size));
        (((dyn_fault_inject_servers_item_serverNames_item_t*)out->elts)[i])->len = token_size;
        if (((dyn_fault_inject_servers_item_serverNames_item_t*)out->elts)[i]->data == NULL) {
            // TODO LOG_ERROR
            return true;
        }
        if (builtin_parse_string(pool, parse_state, (char *)(((dyn_fault_inject_servers_item_serverNames_item_t*)out->elts)[i])->data, 0, (((dyn_fault_inject_servers_item_serverNames_item_t*)out->elts)[i])->len, err_str)) {
            return true;
        }
        out->nelts ++;
    }
    return false;
}


static bool parse_dyn_fault_inject_servers_item_locations(njt_pool_t *pool, parse_state_t *parse_state, dyn_fault_inject_servers_item_locations_t *out, njt_str_t *err_str) {
    int i;
    if (check_type(pool, parse_state, JSMN_ARRAY, err_str)) {
        return true;
    }
    const int n = parse_state->tokens[parse_state->current_token].size;
    // memory has been allocate in njt_array_create.
    parse_state->current_token += 1;
    for (i = 0; i < n; ++i) {
        // TODO CHECK write later
        ((dyn_fault_inject_servers_item_locations_item_t**)out->elts)[i] = njt_palloc(pool, sizeof(locationDef_t));
        if (parse_locationDef(pool, parse_state, ((dyn_fault_inject_servers_item_locations_item_t**)out->elts)[i], err_str)) {
            return true;
        }
        out->nelts ++;
    }
    return false;
}


static bool parse_dyn_fault_inject_servers_item(njt_pool_t *pool, parse_state_t *parse_state, dyn_fault_inject_servers_item_t *out, njt_str_t *err_str) {
    njt_uint_t i;
    // malloc pool for object first

    if (check_type(pool, parse_state, JSMN_OBJECT, err_str)) {
        return true;
    }
    bool seen_listens = false;
    bool seen_serverNames = false;
    bool seen_locations = false;
    const int object_start_token = parse_state->current_token;
    const uint64_t n = parse_state->tokens[parse_state->current_token].size;
    parse_state->current_token += 1;
    for (i = 0; i < n; ++i) {
        if (CURRENT_TOKEN(parse_state).size > 1) {
            LOG_ERROR_JSON_PARSE(CURRENT_TOKEN(parse_state).start, "Missing separator between values in '%s', after key: %.*s", parse_state->current_key, CURRENT_STRING_FOR_ERROR(parse_state))
            return true;
        }
        if (CURRENT_TOKEN(parse_state).size < 1) {
            LOG_ERROR_JSON_PARSE(CURRENT_TOKEN(parse_state).start, "Missing value in '%s', after key: %.*s", parse_state->current_key, CURRENT_STRING_FOR_ERROR(parse_state))
            return true;
        }
        if (current_string_is(parse_state, "listens")) {
            if (seen_listens) {
                LOG_ERROR_JSON_PARSE(CURRENT_TOKEN(parse_state).start, "Duplicate field definition in '%s': listens", parse_state->current_key)
                return true;
            }
            seen_listens = true;
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "listens";
            out->listens = njt_array_create(pool, parse_state->tokens[parse_state->current_token].size ,sizeof(dyn_fault_inject_servers_item_listens_item_t*));
            if (out->listens == NULL) {
                LOG_ERROR_JSON_PARSE(0, "Failed to allocate memory from %s.", "pool")
            }
            if (parse_dyn_fault_inject_servers_item_listens(pool, parse_state, (out->listens), err_str)) {
                return true;
            }
            parse_state->current_key = saved_key;
        } else if (current_string_is(parse_state, "serverNames")) {
            if (seen_serverNames) {
                LOG_ERROR_JSON_PARSE(CURRENT_TOKEN(parse_state).start, "Duplicate field definition in '%s': serverNames", parse_state->current_key)
                return true;
            }
            seen_serverNames = true;
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "serverNames";
            out->serverNames = njt_array_create(pool, parse_state->tokens[parse_state->current_token].size ,sizeof(dyn_fault_inject_servers_item_serverNames_item_t*));
            if (out->serverNames == NULL) {
                LOG_ERROR_JSON_PARSE(0, "Failed to allocate memory from %s.", "pool")
            }
            if (parse_dyn_fault_inject_servers_item_serverNames(pool, parse_state, (out->serverNames), err_str)) {
                return true;
            }
            parse_state->current_key = saved_key;
        } else if (current_string_is(parse_state, "locations")) {
            if (seen_locations) {
                LOG_ERROR_JSON_PARSE(CURRENT_TOKEN(parse_state).start, "Duplicate field definition in '%s': locations", parse_state->current_key)
                return true;
            }
            seen_locations = true;
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "locations";
            out->locations = njt_array_create(pool, parse_state->tokens[parse_state->current_token].size ,sizeof(dyn_fault_inject_servers_item_locations_item_t*));
            if (out->locations == NULL) {
                LOG_ERROR_JSON_PARSE(0, "Failed to allocate memory from %s.", "pool")
            }
            if (parse_dyn_fault_inject_servers_item_locations(pool, parse_state, (out->locations), err_str)) {
                return true;
            }
            parse_state->current_key = saved_key;
        } else {
            LOG_ERROR_JSON_PARSE(CURRENT_TOKEN(parse_state).start, "Unknown field in '%s': %.*s", parse_state->current_key, CURRENT_STRING_FOR_ERROR(parse_state))
            return true;
        }
    }
    const int saved_current_token = parse_state->current_token;
    parse_state->current_token = object_start_token;
    if (!seen_listens) {
        LOG_ERROR_JSON_PARSE(CURRENT_TOKEN(parse_state).start, "Missing required field in '%s': listens", parse_state->current_key)
        return true;
    }
    if (!seen_serverNames) {
        LOG_ERROR_JSON_PARSE(CURRENT_TOKEN(parse_state).start, "Missing required field in '%s': serverNames", parse_state->current_key)
        return true;
    }
    if (!seen_locations) {
        LOG_ERROR_JSON_PARSE(CURRENT_TOKEN(parse_state).start, "Missing required field in '%s': locations", parse_state->current_key)
        return true;
    }
    parse_state->current_token = saved_current_token;
    return false;
}


static bool parse_dyn_fault_inject_servers(njt_pool_t *pool, parse_state_t *parse_state, dyn_fault_inject_servers_t *out, njt_str_t *err_str) {
    int i;
    if (check_type(pool, parse_state, JSMN_ARRAY, err_str)) {
        return true;
    }
    const int n = parse_state->tokens[parse_state->current_token].size;
    // memory has been allocate in njt_array_create.
    parse_state->current_token += 1;
    for (i = 0; i < n; ++i) {
        // TODO CHECK write later
        ((dyn_fault_inject_servers_item_t**)out->elts)[i] = njt_palloc(pool, sizeof(dyn_fault_inject_servers_item_t));
        if (parse_dyn_fault_inject_servers_item(pool, parse_state, ((dyn_fault_inject_servers_item_t**)out->elts)[i], err_str)) {
            return true;
        }
        out->nelts ++;
    }
    return false;
}


static bool parse_dyn_fault_inject(njt_pool_t *pool, parse_state_t *parse_state, dyn_fault_inject_t *out, njt_str_t *err_str) {
    njt_uint_t i;
    // malloc pool for object first

    if (check_type(pool, parse_state, JSMN_OBJECT, err_str)) {
        return true;
    }
    bool seen_servers = false;
    const int object_start_token = parse_state->current_token;
    const uint64_t n = parse_state->tokens[parse_state->current_token].size;
    parse_state->current_token += 1;
    for (i = 0; i < n; ++i) {
        if (CURRENT_TOKEN(parse_state).size > 1) {
            LOG_ERROR_JSON_PARSE(CURRENT_TOKEN(parse_state).start, "Missing separator between values in '%s', after key: %.*s", parse_state->current_key, CURRENT_STRING_FOR_ERROR(parse_state))
            return true;
        }
        if (CURRENT_TOKEN(parse_state).size < 1) {
            LOG_ERROR_JSON_PARSE(CURRENT_TOKEN(parse_state).start, "Missing value in '%s', after key: %.*s", parse_state->current_key, CURRENT_STRING_FOR_ERROR(parse_state))
            return true;
        }
        if (current_string_is(parse_state, "servers")) {
            if (seen_servers) {
                LOG_ERROR_JSON_PARSE(CURRENT_TOKEN(parse_state).start, "Duplicate field definition in '%s': servers", parse_state->current_key)
                return true;
            }
            seen_servers = true;
            parse_state->current_token += 1;
            const char* saved_key = parse_state->current_key;
            parse_state->current_key = "servers";
            out->servers = njt_array_create(pool, parse_state->tokens[parse_state->current_token].size ,sizeof(dyn_fault_inject_servers_item_t*));
            if (out->servers == NULL) {
                LOG_ERROR_JSON_PARSE(0, "Failed to allocate memory from %s.", "pool")
            }
            if (parse_dyn_fault_inject_servers(pool, parse_state, (out->servers), err_str)) {
                return true;
            }
            parse_state->current_key = saved_key;
        } else {
            LOG_ERROR_JSON_PARSE(CURRENT_TOKEN(parse_state).start, "Unknown field in '%s': %.*s", parse_state->current_key, CURRENT_STRING_FOR_ERROR(parse_state))
            return true;
        }
    }
    const int saved_current_token = parse_state->current_token;
    parse_state->current_token = object_start_token;
    if (!seen_servers) {
        LOG_ERROR_JSON_PARSE(CURRENT_TOKEN(parse_state).start, "Missing required field in '%s': servers", parse_state->current_key)
        return true;
    }
    parse_state->current_token = saved_current_token;
    return false;
}


static void get_json_length_dyn_fault_inject_servers_item_listens_item(dyn_fault_inject_servers_item_listens_item_t *out, size_t *length, njt_int_t flags) {
    *length += (*out)->len + 2; //  "str" 
}

static void get_json_length_dyn_fault_inject_servers_item_listens(dyn_fault_inject_servers_item_listens_t *out, size_t *length, njt_int_t flags) {
    njt_uint_t i;
    njt_uint_t omit;
    njt_int_t count = 0;
    if (out == NULL) {
        *length += 2; // "[]"
        return;
    }
    *length += 2; // "[]"
    for (i = 0; i < out->nelts; ++i) {
        omit = 0;
        if ((flags & OMIT_NULL_STR) && (&((dyn_fault_inject_servers_item_listens_item_t*)out->elts)[i]) == NULL) {
            omit = 1;
        }
        if (omit == 0) {
            get_json_length_dyn_fault_inject_servers_item_listens_item((&((dyn_fault_inject_servers_item_listens_item_t*)out->elts)[i]), length, flags);
            *length += 1; // ","
            count++; // ","
        }
    }
    if (count != 0) {
        *length -= 1; // "\b"
    }
}

static void get_json_length_dyn_fault_inject_servers_item_serverNames_item(dyn_fault_inject_servers_item_serverNames_item_t *out, size_t *length, njt_int_t flags) {
    *length += (*out)->len + 2; //  "str" 
}

static void get_json_length_dyn_fault_inject_servers_item_serverNames(dyn_fault_inject_servers_item_serverNames_t *out, size_t *length, njt_int_t flags) {
    njt_uint_t i;
    njt_uint_t omit;
    njt_int_t count = 0;
    if (out == NULL) {
        *length += 2; // "[]"
        return;
    }
    *length += 2; // "[]"
    for (i = 0; i < out->nelts; ++i) {
        omit = 0;
        if ((flags & OMIT_NULL_STR) && (&((dyn_fault_inject_servers_item_serverNames_item_t*)out->elts)[i]) == NULL) {
            omit = 1;
        }
        if (omit == 0) {
            get_json_length_dyn_fault_inject_servers_item_serverNames_item((&((dyn_fault_inject_servers_item_serverNames_item_t*)out->elts)[i]), length, flags);
            *length += 1; // ","
            count++; // ","
        }
    }
    if (count != 0) {
        *length -= 1; // "\b"
    }
}
// GET_JSON_LENGTH_REF

static void get_json_length_dyn_fault_inject_servers_item_locations_item(dyn_fault_inject_servers_item_locations_item_t *out, size_t *length, njt_int_t flags) {
    get_json_length_locationDef(out, length, flags);
}

static void get_json_length_dyn_fault_inject_servers_item_locations(dyn_fault_inject_servers_item_locations_t *out, size_t *length, njt_int_t flags) {
    njt_uint_t i;
    njt_uint_t omit;
    njt_int_t count = 0;
    if (out == NULL) {
        *length += 2; // "[]"
        return;
    }
    *length += 2; // "[]"
    for (i = 0; i < out->nelts; ++i) {
        omit = 0;
        if ((flags & OMIT_NULL_OBJ) && ((dyn_fault_inject_servers_item_locations_item_t**)out->elts)[i] == NULL) {
            omit = 1;
        }
        if (omit == 0) {
            get_json_length_dyn_fault_inject_servers_item_locations_item(((dyn_fault_inject_servers_item_locations_item_t**)out->elts)[i], length, flags);
            *length += 1; // ","
            count++; // ","
        }
    }
    if (count != 0) {
        *length -= 1; // "\b"
    }
}

static void get_json_length_dyn_fault_inject_servers_item(dyn_fault_inject_servers_item_t *out, size_t *length, njt_int_t flags) {
    if (out == NULL) {
        *length += 4; // null
        return;
    }
    *length += 1;
    njt_int_t omit;
    njt_int_t count = 0;
    omit = 0;
    if ((flags & OMIT_NULL_ARRAY) && (out->listens) == NULL) {
        omit = 1;
    }
    if (omit == 0) {
        *length += (7 + 3); // "listens": 
        get_json_length_dyn_fault_inject_servers_item_listens((out->listens), length, flags);
        *length += 1; // ","
        count++;
    }
    omit = 0;
    if ((flags & OMIT_NULL_ARRAY) && (out->serverNames) == NULL) {
        omit = 1;
    }
    if (omit == 0) {
        *length += (11 + 3); // "serverNames": 
        get_json_length_dyn_fault_inject_servers_item_serverNames((out->serverNames), length, flags);
        *length += 1; // ","
        count++;
    }
    omit = 0;
    if ((flags & OMIT_NULL_ARRAY) && (out->locations) == NULL) {
        omit = 1;
    }
    if (omit == 0) {
        *length += (9 + 3); // "locations": 
        get_json_length_dyn_fault_inject_servers_item_locations((out->locations), length, flags);
        *length += 1; // ","
        count++;
    }
    if (count != 0) {
        *length -= 1; // "\b"
    }
    *length += 1;
}

static void get_json_length_dyn_fault_inject_servers(dyn_fault_inject_servers_t *out, size_t *length, njt_int_t flags) {
    njt_uint_t i;
    njt_uint_t omit;
    njt_int_t count = 0;
    if (out == NULL) {
        *length += 2; // "[]"
        return;
    }
    *length += 2; // "[]"
    for (i = 0; i < out->nelts; ++i) {
        omit = 0;
        if ((flags & OMIT_NULL_OBJ) && ((dyn_fault_inject_servers_item_t**)out->elts)[i] == NULL) {
            omit = 1;
        }
        if (omit == 0) {
            get_json_length_dyn_fault_inject_servers_item(((dyn_fault_inject_servers_item_t**)out->elts)[i], length, flags);
            *length += 1; // ","
            count++; // ","
        }
    }
    if (count != 0) {
        *length -= 1; // "\b"
    }
}

static void get_json_length_dyn_fault_inject(dyn_fault_inject_t *out, size_t *length, njt_int_t flags) {
    if (out == NULL) {
        *length += 4; // null
        return;
    }
    *length += 1;
    njt_int_t omit;
    njt_int_t count = 0;
    omit = 0;
    if ((flags & OMIT_NULL_ARRAY) && (out->servers) == NULL) {
        omit = 1;
    }
    if (omit == 0) {
        *length += (7 + 3); // "servers": 
        get_json_length_dyn_fault_inject_servers((out->servers), length, flags);
        *length += 1; // ","
        count++;
    }
    if (count != 0) {
        *length -= 1; // "\b"
    }
    *length += 1;
}
// CHECK ARRAY not exceeding bounds before call this func

dyn_fault_inject_servers_item_listens_item_t get_dyn_fault_inject_servers_item_listens_item(dyn_fault_inject_servers_item_listens_t *out, size_t idx) {
    return ((dyn_fault_inject_servers_item_listens_item_t*)out->elts)[idx];
}
// CHECK ARRAY not exceeding bounds before call this func

dyn_fault_inject_servers_item_serverNames_item_t get_dyn_fault_inject_servers_item_serverNames_item(dyn_fault_inject_servers_item_serverNames_t *out, size_t idx) {
    return ((dyn_fault_inject_servers_item_serverNames_item_t*)out->elts)[idx];
}
// CHECK ARRAY not exceeding bounds before call this func

dyn_fault_inject_servers_item_locations_item_t get_dyn_fault_inject_servers_item_locations_item(dyn_fault_inject_servers_item_locations_t *out, size_t idx) {
    return *((dyn_fault_inject_servers_item_locations_item_t**)out->elts)[idx];
}

dyn_fault_inject_servers_item_listens_t* get_dyn_fault_inject_servers_item_listens(dyn_fault_inject_servers_item_t *out) {
    return out->listens;
}

dyn_fault_inject_servers_item_serverNames_t* get_dyn_fault_inject_servers_item_serverNames(dyn_fault_inject_servers_item_t *out) {
    return out->serverNames;
}

dyn_fault_inject_servers_item_locations_t* get_dyn_fault_inject_servers_item_locations(dyn_fault_inject_servers_item_t *out) {
    return out->locations;
}
// CHECK ARRAY not exceeding bounds before call this func

dyn_fault_inject_servers_item_t get_dyn_fault_inject_servers_item(dyn_fault_inject_servers_t *out, size_t idx) {
    return *((dyn_fault_inject_servers_item_t**)out->elts)[idx];
}

dyn_fault_inject_servers_t* get_dyn_fault_inject_servers(dyn_fault_inject_t *out) {
    return out->servers;
}
int add_item_dyn_fault_inject_servers_item_listens(dyn_fault_inject_servers_item_listens_t *src, dyn_fault_inject_servers_item_listens_item_t item) {
    void *new = njt_array_push(src);
    if (new == NULL) {
        return NJT_ERROR;
    }
    njt_memcpy(new, &item, src->size);
    return NJT_OK;
}

dyn_fault_inject_servers_item_listens_t* create_dyn_fault_inject_servers_item_listens(njt_pool_t *pool, size_t length) {
    return njt_array_create(pool, length, sizeof(dyn_fault_inject_servers_item_listens_item_t));
}
void set_dyn_fault_inject_servers_item_listens(dyn_fault_inject_servers_item_t* obj, dyn_fault_inject_servers_item_listens_t* field) {
    obj->listens = field;
}
int add_item_dyn_fault_inject_servers_item_serverNames(dyn_fault_inject_servers_item_serverNames_t *src, dyn_fault_inject_servers_item_serverNames_item_t item) {
    void *new = njt_array_push(src);
    if (new == NULL) {
        return NJT_ERROR;
    }
    njt_memcpy(new, &item, src->size);
    return NJT_OK;
}

dyn_fault_inject_servers_item_serverNames_t* create_dyn_fault_inject_servers_item_serverNames(njt_pool_t *pool, size_t length) {
    return njt_array_create(pool, length, sizeof(dyn_fault_inject_servers_item_serverNames_item_t));
}
void set_dyn_fault_inject_servers_item_serverNames(dyn_fault_inject_servers_item_t* obj, dyn_fault_inject_servers_item_serverNames_t* field) {
    obj->serverNames = field;
}
int add_item_dyn_fault_inject_servers_item_locations(dyn_fault_inject_servers_item_locations_t *src, dyn_fault_inject_servers_item_locations_item_t* item) {
    void *new = njt_array_push(src);
    if (new == NULL) {
        return NJT_ERROR;
    }
    njt_memcpy(new, &item, src->size);
    return NJT_OK;
}

dyn_fault_inject_servers_item_locations_t* create_dyn_fault_inject_servers_item_locations(njt_pool_t *pool, size_t length) {
    return njt_array_create(pool, length, sizeof(dyn_fault_inject_servers_item_locations_item_t*));
}
void set_dyn_fault_inject_servers_item_locations(dyn_fault_inject_servers_item_t* obj, dyn_fault_inject_servers_item_locations_t* field) {
    obj->locations = field;
}
dyn_fault_inject_servers_item_t* create_dyn_fault_inject_servers_item(njt_pool_t *pool) {
    dyn_fault_inject_servers_item_t* out = njt_palloc(pool, sizeof(dyn_fault_inject_servers_item_t));
    memset(out, 0, sizeof(dyn_fault_inject_servers_item_t));
    return out;
}
int add_item_dyn_fault_inject_servers(dyn_fault_inject_servers_t *src, dyn_fault_inject_servers_item_t* item) {
    void *new = njt_array_push(src);
    if (new == NULL) {
        return NJT_ERROR;
    }
    njt_memcpy(new, &item, src->size);
    return NJT_OK;
}

dyn_fault_inject_servers_t* create_dyn_fault_inject_servers(njt_pool_t *pool, size_t length) {
    return njt_array_create(pool, length, sizeof(dyn_fault_inject_servers_item_t*));
}
void set_dyn_fault_inject_servers(dyn_fault_inject_t* obj, dyn_fault_inject_servers_t* field) {
    obj->servers = field;
}
dyn_fault_inject_t* create_dyn_fault_inject(njt_pool_t *pool) {
    dyn_fault_inject_t* out = njt_palloc(pool, sizeof(dyn_fault_inject_t));
    memset(out, 0, sizeof(dyn_fault_inject_t));
    return out;
}

static void to_oneline_json_dyn_fault_inject_servers_item_listens_item(dyn_fault_inject_servers_item_listens_item_t *out, njt_str_t *buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    njt_sprintf(cur, "\"%V\"", *out);
    buf->len += (*out)->len + 2;
}

static void to_oneline_json_dyn_fault_inject_servers_item_listens(dyn_fault_inject_servers_item_listens_t *out, njt_str_t* buf, njt_int_t flags) {
    njt_int_t omit;
    u_char *cur = buf->data + buf->len;
    njt_uint_t i;
    if (out == NULL || out->nelts == 0) {
        cur = njt_sprintf(cur, "[]");
        buf->len += 2;
        return;
    }
    cur = njt_sprintf(cur,  "[");
    buf->len ++;
    for (i = 0; i < out->nelts; ++i) {
        omit = 0;
        if ((flags & OMIT_NULL_STR) && (&((dyn_fault_inject_servers_item_listens_item_t*)out->elts)[i]) == NULL) {
            omit = 1;
        }
        if (omit == 0) {
            to_oneline_json_dyn_fault_inject_servers_item_listens_item((&((dyn_fault_inject_servers_item_listens_item_t*)out->elts)[i]), buf, flags);
            cur = buf->data + buf->len;
            cur = njt_sprintf(cur, ",");
            buf->len ++;
        }
    }
    cur--;
    if (cur[0] == ',') {
        buf->len --;
    } else {
        cur ++;
    }
    cur = njt_sprintf(cur,  "]");
    buf->len ++;
}

static void to_oneline_json_dyn_fault_inject_servers_item_serverNames_item(dyn_fault_inject_servers_item_serverNames_item_t *out, njt_str_t *buf, njt_int_t flags) {
    u_char* cur = buf->data + buf->len;
    njt_sprintf(cur, "\"%V\"", *out);
    buf->len += (*out)->len + 2;
}

static void to_oneline_json_dyn_fault_inject_servers_item_serverNames(dyn_fault_inject_servers_item_serverNames_t *out, njt_str_t* buf, njt_int_t flags) {
    njt_int_t omit;
    u_char *cur = buf->data + buf->len;
    njt_uint_t i;
    if (out == NULL || out->nelts == 0) {
        cur = njt_sprintf(cur, "[]");
        buf->len += 2;
        return;
    }
    cur = njt_sprintf(cur,  "[");
    buf->len ++;
    for (i = 0; i < out->nelts; ++i) {
        omit = 0;
        if ((flags & OMIT_NULL_STR) && (&((dyn_fault_inject_servers_item_serverNames_item_t*)out->elts)[i]) == NULL) {
            omit = 1;
        }
        if (omit == 0) {
            to_oneline_json_dyn_fault_inject_servers_item_serverNames_item((&((dyn_fault_inject_servers_item_serverNames_item_t*)out->elts)[i]), buf, flags);
            cur = buf->data + buf->len;
            cur = njt_sprintf(cur, ",");
            buf->len ++;
        }
    }
    cur--;
    if (cur[0] == ',') {
        buf->len --;
    } else {
        cur ++;
    }
    cur = njt_sprintf(cur,  "]");
    buf->len ++;
}
// to_oneline_json_REF

static void to_oneline_json_dyn_fault_inject_servers_item_locations_item(dyn_fault_inject_servers_item_locations_item_t *out, njt_str_t* buf, njt_int_t flags) {
    to_oneline_json_locationDef(out, buf, flags);
}

static void to_oneline_json_dyn_fault_inject_servers_item_locations(dyn_fault_inject_servers_item_locations_t *out, njt_str_t* buf, njt_int_t flags) {
    njt_int_t omit;
    u_char *cur = buf->data + buf->len;
    njt_uint_t i;
    if (out == NULL || out->nelts == 0) {
        cur = njt_sprintf(cur, "[]");
        buf->len += 2;
        return;
    }
    cur = njt_sprintf(cur,  "[");
    buf->len ++;
    for (i = 0; i < out->nelts; ++i) {
        omit = 0;
        if ((flags & OMIT_NULL_OBJ) && ((dyn_fault_inject_servers_item_locations_item_t**)out->elts)[i] == NULL) {
            omit = 1;
        }
        if (omit == 0) {
            to_oneline_json_dyn_fault_inject_servers_item_locations_item(((dyn_fault_inject_servers_item_locations_item_t**)out->elts)[i], buf, flags);
            cur = buf->data + buf->len;
            cur = njt_sprintf(cur, ",");
            buf->len ++;
        }
    }
    cur--;
    if (cur[0] == ',') {
        buf->len --;
    } else {
        cur ++;
    }
    cur = njt_sprintf(cur,  "]");
    buf->len ++;
}

static void to_oneline_json_dyn_fault_inject_servers_item(dyn_fault_inject_servers_item_t *out, njt_str_t* buf, njt_int_t flags) {
    njt_int_t omit;
    u_char* cur = buf->data + buf->len;
    if (out == NULL) {
        cur = njt_sprintf(cur, "null");
        buf->len += 4;
        return;
    }
    cur = njt_sprintf(cur, "{");
    buf->len ++;
    omit = 0;
    if ((flags & OMIT_NULL_ARRAY) && (out->listens) == NULL) {
        omit = 1;
    }
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"listens\":");
        buf->len = cur - buf->data;
        to_oneline_json_dyn_fault_inject_servers_item_listens((out->listens), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    omit = 0;
    if ((flags & OMIT_NULL_ARRAY) && (out->serverNames) == NULL) {
        omit = 1;
    }
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"serverNames\":");
        buf->len = cur - buf->data;
        to_oneline_json_dyn_fault_inject_servers_item_serverNames((out->serverNames), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    omit = 0;
    if ((flags & OMIT_NULL_ARRAY) && (out->locations) == NULL) {
        omit = 1;
    }
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"locations\":");
        buf->len = cur - buf->data;
        to_oneline_json_dyn_fault_inject_servers_item_locations((out->locations), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    cur--;
    if (cur[0] == ',') {
        buf->len --;
    } else {
        cur ++;
    }
    cur = njt_sprintf(cur, "}");
    buf->len ++;
}

static void to_oneline_json_dyn_fault_inject_servers(dyn_fault_inject_servers_t *out, njt_str_t* buf, njt_int_t flags) {
    njt_int_t omit;
    u_char *cur = buf->data + buf->len;
    njt_uint_t i;
    if (out == NULL || out->nelts == 0) {
        cur = njt_sprintf(cur, "[]");
        buf->len += 2;
        return;
    }
    cur = njt_sprintf(cur,  "[");
    buf->len ++;
    for (i = 0; i < out->nelts; ++i) {
        omit = 0;
        if ((flags & OMIT_NULL_OBJ) && ((dyn_fault_inject_servers_item_t**)out->elts)[i] == NULL) {
            omit = 1;
        }
        if (omit == 0) {
            to_oneline_json_dyn_fault_inject_servers_item(((dyn_fault_inject_servers_item_t**)out->elts)[i], buf, flags);
            cur = buf->data + buf->len;
            cur = njt_sprintf(cur, ",");
            buf->len ++;
        }
    }
    cur--;
    if (cur[0] == ',') {
        buf->len --;
    } else {
        cur ++;
    }
    cur = njt_sprintf(cur,  "]");
    buf->len ++;
}

static void to_oneline_json_dyn_fault_inject(dyn_fault_inject_t *out, njt_str_t* buf, njt_int_t flags) {
    njt_int_t omit;
    u_char* cur = buf->data + buf->len;
    if (out == NULL) {
        cur = njt_sprintf(cur, "null");
        buf->len += 4;
        return;
    }
    cur = njt_sprintf(cur, "{");
    buf->len ++;
    omit = 0;
    if ((flags & OMIT_NULL_ARRAY) && (out->servers) == NULL) {
        omit = 1;
    }
    if (omit == 0) {
        cur = njt_sprintf(cur, "\"servers\":");
        buf->len = cur - buf->data;
        to_oneline_json_dyn_fault_inject_servers((out->servers), buf, flags);
        cur = buf->data + buf->len;
        cur = njt_sprintf(cur, ",");
        buf->len ++;
    }
    cur--;
    if (cur[0] == ',') {
        buf->len --;
    } else {
        cur ++;
    }
    cur = njt_sprintf(cur, "}");
    buf->len ++;
}
dyn_fault_inject_t* json_parse_dyn_fault_inject(njt_pool_t *pool, const njt_str_t *json_string, njt_str_t *err_str) {
    dyn_fault_inject_t* out;
    parse_state_t parse_state_var;
    parse_state_t *parse_state = &parse_state_var;
    uint64_t max_token_number = 1024;
    jsmntok_t *token_buffer;
    int parse_result;
    for ( ; /* parse unsuccessful */; ) {
        token_buffer = njt_palloc(pool, sizeof(jsmntok_t)*max_token_number);
        parse_result = builtin_parse_json_string(pool, parse_state, token_buffer, max_token_number, (char *)json_string->data, json_string->len, err_str);
        if (parse_result == JSMN_ERROR_INVAL || parse_result == JSMN_ERROR_PART) {
            // njt_pfree(pool, token_buffer);
            return NULL;
        }
        if (parse_result == JSMN_ERROR_NOMEM) {
            max_token_number += max_token_number;
            printf("max_token_number: %ld\n", max_token_number);
            continue;
        }
        if (parse_result == 0) {
            LOG_ERROR_JSON_PARSE(0, "String did not contain %s JSON tokens", "any");
            return NULL;
        }
        break; // parse success
    }
    out = njt_palloc(pool, sizeof(dyn_fault_inject_t));;
    if (parse_dyn_fault_inject(pool, parse_state, out, err_str)) {
        return NULL;
    }
    return out;
}

njt_str_t* to_json_dyn_fault_inject(njt_pool_t *pool, dyn_fault_inject_t* out, njt_int_t flags) {
    njt_str_t *json_str;
    json_str = njt_palloc(pool, sizeof(njt_str_t));
    size_t str_len = 0;
    get_json_length_dyn_fault_inject(out, &str_len, flags);
    json_str->data = njt_palloc(pool, str_len + 1);
    json_str->len = 0;
    to_oneline_json_dyn_fault_inject(out, json_str, flags);
    return json_str;
}
